// ─────────────────────────────────────────────────────────────
//  FAMILY RECIPES  (imported from Kandy's OneNote "My Cookbook 2026")
//
//  Everyday family recipes, NOT low-FODMAP. They carry the 'family' tag so
//  they sit alongside (not mixed into) the FODMAP recipes and show under the
//  🍽️ Family filter. Each recipe is also tagged with the OneNote SECTION
//  (tab) it came from, so you can filter/search by section.
//
//  • Hand-typed recipes are imported in full.
//  • Web-clipped recipes are saved as link cards (title + source link),
//    since the original pages can't be fetched from this environment.
// ─────────────────────────────────────────────────────────────

const FAMILY_RECIPES = [

  // ── Hand-typed recipes — Holidays › Thanksgiving (full) ────
  {
    id: 'fam-cornbread',
    name: 'Cornbread',
    emoji: '🍞',
    category: 'dinner',
    time: '40 min',
    serves: 9,
    difficulty: 'easy',
    tags: ['family', 'thanksgiving', 'vegetarian'],
    ingredients: [
      { qty: '1 cup',  item: 'flour' },
      { qty: '1 cup',  item: 'cornmeal' },
      { qty: '1 cup',  item: 'sugar' },
      { qty: '3 tsp',  item: 'baking powder' },
      { qty: '1 cup',  item: 'milk' },
      { qty: '1',      item: 'egg' },
    ],
    steps: [
      'Sift the dry ingredients together.',
      'Stir in the liquids until just combined.',
      'Pour into a greased 9x9 pan.',
      'Bake at 350°F for 30–40 minutes, until golden and a toothpick comes out clean.',
    ],
    fodmapNote: 'Family recipe from the Holidays › Thanksgiving section.',
  },

  {
    id: 'fam-candied-yams',
    name: 'Candied Yams',
    emoji: '🍠',
    category: 'dinner',
    time: '40 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['family', 'thanksgiving', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '2 cans', item: 'yams, drained' },
      { qty: 'to taste', item: 'brown sugar' },
      { qty: '2 tbsp', item: 'butter' },
      { qty: '1 bag',  item: 'marshmallows' },
    ],
    steps: [
      'Drain the yams and arrange in a single layer in a casserole dish.',
      'Melt the butter and sprinkle brown sugar over the yams.',
      'Bake at 350°F for 30 minutes.',
      'Top with marshmallows and return to the oven until golden and melted.',
    ],
    fodmapNote: 'Family recipe from the Holidays › Thanksgiving section.',
  },

  {
    id: 'fam-chocolate-pie',
    name: 'Chocolate Pie',
    emoji: '🥧',
    category: 'desserts',
    time: '10 min + chill',
    serves: 8,
    difficulty: 'easy',
    tags: ['family', 'thanksgiving', 'vegetarian', 'no-cook'],
    ingredients: [
      { qty: '1 box', item: 'instant chocolate pudding mix' },
      { qty: 'per package', item: 'milk' },
      { qty: '1',     item: 'prepared pie crust' },
      { qty: '1 tub', item: 'Cool Whip' },
    ],
    steps: [
      'Whisk the instant pudding mix with milk per the package directions.',
      'Pour into the pie crust.',
      'Chill until set.',
      'Top with Cool Whip before serving.',
    ],
    fodmapNote: 'Family recipe from the Holidays › Thanksgiving section.',
  },

  {
    id: 'fam-broccoli-cheese-rice',
    name: 'Broccoli, Cheese & Rice',
    emoji: '🥦',
    category: 'dinner',
    time: '25 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['family', 'thanksgiving', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1 bag', item: 'broccoli' },
      { qty: 'to taste', item: 'Velveeta' },
      { qty: '1 cup (uncooked)', item: 'rice' },
    ],
    steps: [
      'Boil the broccoli until tender.',
      'Cube the Velveeta so it melts easily.',
      'Cook the rice.',
      'Add everything together and stir to your desired consistency.',
    ],
    fodmapNote: 'Family recipe from the Holidays › Thanksgiving section.',
  },

];

// Build a card for a saved web recipe. Each card carries the 'family' tag plus
// the OneNote section (tab) it lives in, and preserves Kandy's notes.
//
// If `ingredients` + `steps` are supplied, the FULL recipe shows in the app
// (no longer truncated). The original page is still linked via `source` so you
// can tap "View original recipe" for photos and extra tips. If they're omitted,
// the card falls back to a link/placeholder stub (used when the source site
// blocks automated fetching, or the recipe lives only in OneNote).
function familyLinkCard(o) {
  const section = o.section || '';
  const tags = ['family'];
  if (section) tags.push(section);
  const hasFullRecipe = Array.isArray(o.ingredients) && o.ingredients.length > 0;
  return {
    id: o.id,
    name: o.name,
    emoji: o.emoji || '🍽️',
    category: o.category || 'dinner',
    time: o.time || '',
    serves: o.serves || 4,
    difficulty: o.difficulty || 'easy',
    tags,
    source: o.source,
    ingredients: hasFullRecipe ? o.ingredients : [{
      qty: '',
      item: o.source ? 'See the original recipe for the full ingredient list →'
                     : 'The full recipe lives in your OneNote cookbook.',
    }],
    steps: hasFullRecipe ? o.steps : [
      o.source ? 'Saved web recipe — tap “View original recipe” below for the full ingredients and method.'
               : 'Saved in your OneNote cookbook — the full recipe lives there.',
    ],
    fodmapNote: o.note
      ? `From your “${section}” section. Your note: “${o.note}”`
      : (section ? `Saved from your “${section}” section.` : 'Saved from your cookbook.'),
  };
}

FAMILY_RECIPES.push(

  // ── Previously saved clips (now filled in with the full recipe) ──
  familyLinkCard({ id: 'fam-cajun-sausage-pasta', name: 'One Pot Creamy Cajun Sausage Pasta', emoji: '🍝', category: 'dinner', section: 'make agains', source: 'https://thestayathomechef.com/creamy-cajun-sausage-pasta/',
    time: '40 min', serves: 6,
    ingredients: [
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 medium', item: 'yellow onion, diced' },
      { qty: '1 medium', item: 'red bell pepper, diced' },
      { qty: '12 oz', item: 'andouille sausage, sliced into ¼-inch rounds' },
      { qty: '1 tbsp', item: 'minced garlic' },
      { qty: '1 tbsp', item: 'Cajun seasoning' },
      { qty: '1 lb', item: 'rigatoni or penne' },
      { qty: '4 cups', item: 'chicken broth' },
      { qty: '2 (14.5 oz) cans', item: 'diced tomatoes, undrained' },
      { qty: '2 tbsp', item: 'cornstarch' },
      { qty: '1 cup', item: 'heavy cream' },
      { qty: '1 cup', item: 'shredded Parmesan cheese' },
      { qty: '2 tbsp', item: 'chopped fresh parsley (optional)' },
    ],
    steps: [
      'Heat olive oil in a large deep skillet or Dutch oven over medium heat. Add sausage and cook 3–4 minutes until browned.',
      'Add diced onion and bell pepper; cook 3–4 minutes until vegetables soften.',
      'Stir in garlic and Cajun seasoning; cook 1 minute to toast.',
      'Add broth, tomatoes, and pasta. Stir and press the pasta under the liquid.',
      'Bring to a boil, then reduce heat to medium-low, cover, and simmer 15–18 minutes, stirring occasionally, until pasta is tender.',
      'Remove ½ cup liquid and whisk with cornstarch to make a slurry; stir back into the pot.',
      'Add cream and Parmesan; simmer uncovered 2–3 minutes until the sauce thickens.',
      'Remove from heat, garnish with parsley if desired, and serve.',
    ] }),
  familyLinkCard({ id: 'fam-swedish-meatballs', name: 'Swedish Meatballs', emoji: '🧆', category: 'dinner', difficulty: 'medium', section: 'quick notes', source: 'https://www.thecookierookie.com/swedish-meatballs/',
    time: '40 min', serves: 8,
    ingredients: [
      { qty: 'For the meatballs', item: '—' },
      { qty: '⅓ cup', item: 'breadcrumbs' },
      { qty: '½ cup', item: 'milk' },
      { qty: '2 tbsp', item: 'heavy cream' },
      { qty: '1 large', item: 'egg' },
      { qty: '½ tsp', item: 'kosher salt' },
      { qty: '¼ tsp', item: 'ground black pepper' },
      { qty: '¼ tsp', item: 'ground allspice' },
      { qty: '¼ tsp', item: 'ground nutmeg' },
      { qty: '1 tbsp', item: 'minced fresh parsley' },
      { qty: '1 tbsp', item: 'unsalted butter' },
      { qty: '1 tbsp', item: 'vegetable oil' },
      { qty: '½', item: 'yellow onion, minced' },
      { qty: '1 clove', item: 'garlic, minced' },
      { qty: '1 lb', item: 'ground chicken' },
      { qty: '1½ lbs', item: 'ground chuck' },
      { qty: 'For the sauce', item: '—' },
      { qty: '6 tbsp', item: 'unsalted butter' },
      { qty: '⅓ cup', item: 'all-purpose flour' },
      { qty: '14.5 oz', item: 'low-sodium beef broth' },
      { qty: '14.5 oz', item: 'low-sodium chicken broth' },
      { qty: '1 cup', item: 'heavy cream' },
      { qty: '¾ cup', item: 'sour cream' },
      { qty: '1 tsp', item: 'beef bouillon granules' },
      { qty: '1 tbsp', item: 'low-sodium soy sauce' },
      { qty: '1 tsp', item: 'Dijon mustard' },
      { qty: '1 tsp', item: 'Worcestershire sauce' },
      { qty: '1 tsp', item: 'apple cider vinegar' },
      { qty: '1 tbsp', item: 'granulated sugar' },
      { qty: '½ tsp', item: 'black pepper (plus salt to taste)' },
      { qty: '1–2 tbsp', item: 'minced fresh parsley' },
    ],
    steps: [
      'Preheat oven to 400°F; line two baking sheets with foil and spray with nonstick spray.',
      'Combine breadcrumbs, milk, cream, egg, salt, pepper, allspice, nutmeg, and parsley; let sit 10 minutes.',
      'Heat butter and oil in a skillet; sauté minced onion until translucent, add garlic for 30 seconds, then add to the breadcrumb mixture.',
      'Mix in ground chicken and chuck until just combined. Roll into 1½-inch balls and place on the sheets 1 inch apart.',
      'Bake 20 minutes until no longer pink inside.',
      'Meanwhile, melt 6 tbsp butter in a large skillet; whisk in flour and cook over medium-low until slightly darkened.',
      'Add both broths, cream, sour cream, bouillon, soy sauce, mustard, Worcestershire, vinegar, sugar, and pepper; bring to a boil.',
      'Reduce heat to low; add meatballs and simmer gently until the gravy thickens. Stir in parsley and serve over egg noodles or mashed potatoes.',
    ] }),
  familyLinkCard({ id: 'fam-oreo-cheesecake', name: 'Oreo Cheesecake', emoji: '🍰', category: 'desserts', serves: 12, difficulty: 'medium', section: 'to be filed', source: 'https://www.southernliving.com/oreo-cheesecake-8425253',
    time: '55 min + chill',
    ingredients: [
      { qty: '1 (14.3 oz) pkg', item: 'Oreos, divided' },
      { qty: '3 tbsp', item: 'butter, melted' },
      { qty: '4 (8 oz) pkgs', item: 'cream cheese, softened' },
      { qty: '1¼ cups', item: 'sugar' },
      { qty: '2 tsp', item: 'vanilla extract' },
      { qty: '4 large', item: 'eggs' },
    ],
    steps: [
      'Preheat oven to 350°F and lightly spray a 9-inch springform pan.',
      'Crush about half the Oreos and mix with the melted butter; press into the bottom of the pan to form the crust.',
      'Beat softened cream cheese, sugar, and vanilla until smooth. Add eggs and mix until just combined.',
      'Roughly break the remaining cookies and fold most into the batter (reserve some). Pour over the crust and tap to release air bubbles.',
      'Sprinkle reserved Oreos on top and bake 40–50 minutes until the center is almost set.',
      'Cool, then refrigerate at least 3 hours (overnight is best) before serving.',
    ] }),

  // ── MAKE AGAINS — your tried-and-true favorites ────────────
  familyLinkCard({ id: 'fam-green-chile-chicken-enchiladas', name: 'Green Chile Chicken Enchiladas', emoji: '🌶️', section: 'make agains', source: 'https://keviniscooking.com/green-chile-chicken-enchiladas/', note: 'Good — figure out how to keep the tortillas from getting soggy',
    time: '1 hr', serves: 8,
    ingredients: [
      { qty: '4 cups', item: 'shredded cooked chicken breast' },
      { qty: '4 cups', item: 'salsa verde or green enchilada sauce, divided' },
      { qty: '2 cups', item: 'cooked pinto beans' },
      { qty: '1 cup', item: 'corn kernels (fresh or frozen)' },
      { qty: '4 oz', item: 'chopped green chiles' },
      { qty: '3 cups', item: 'shredded Pepper Jack cheese, divided' },
      { qty: '8', item: 'corn or flour tortillas' },
      { qty: '1 cup', item: 'shredded Monterey Jack cheese' },
      { qty: 'to garnish', item: 'fresh cilantro, chopped' },
    ],
    steps: [
      'Preheat oven to 350°F and spray a baking pan with cooking spray.',
      'Combine shredded chicken, 1 cup salsa verde, beans, corn, green chiles, and 2 cups Pepper Jack in a bowl.',
      'Distribute the filling among the tortillas and roll up lengthwise.',
      'Spread 1 cup salsa verde on the bottom of the pan and arrange the rolled enchiladas on top.',
      'Pour the remaining sauce over and top with remaining Pepper Jack and the Monterey Jack.',
      'Bake uncovered 30 minutes, cool slightly, and garnish with cilantro.',
    ] }),
  familyLinkCard({ id: 'fam-greek-salad-dressing', name: 'Greek Salad Dressing (for pasta)', emoji: '🥗', category: 'lunch', section: 'make agains', source: 'https://www.spendwithpennies.com/greek-salad-dressing/', note: 'My fave Greek salad dressing for pasta',
    time: '5 min + chill', serves: 8,
    ingredients: [
      { qty: '¼ cup', item: 'red wine vinegar' },
      { qty: '2 tbsp', item: 'fresh lemon juice' },
      { qty: '2 tsp', item: 'Dijon mustard' },
      { qty: '1 tsp', item: 'honey' },
      { qty: '¼ tsp', item: 'seasoned salt' },
      { qty: '¼ tsp', item: 'garlic powder' },
      { qty: '½ tsp', item: 'dried oregano' },
      { qty: '½ tsp', item: 'dried basil' },
      { qty: '⅔ cup', item: 'olive oil' },
      { qty: '½ oz', item: 'crumbled feta cheese (optional)' },
      { qty: 'to taste', item: 'black pepper' },
    ],
    steps: [
      'Combine all ingredients except the olive oil.',
      'Blend or whisk on low speed while slowly drizzling in the oil.',
      'Once the oil is incorporated, add feta and blend until combined.',
      'Refrigerate at least 30 minutes before serving.',
    ] }),
  familyLinkCard({ id: 'fam-chili-mac', name: 'Chili Mac', emoji: '🧀', section: 'make agains', source: 'https://www.gonnawantseconds.com/one-skillet-cheesy-chili-mac/',
    time: '30 min', serves: 4,
    ingredients: [
      { qty: '1 tbsp', item: 'vegetable oil' },
      { qty: '1 medium', item: 'yellow onion, chopped' },
      { qty: '1 tbsp', item: 'chili powder' },
      { qty: '1 tbsp', item: 'cumin' },
      { qty: '4 large cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'brown sugar, packed' },
      { qty: '1 lb', item: 'lean ground beef' },
      { qty: '2 cups', item: 'water' },
      { qty: '1 (15 oz) can', item: 'tomato sauce' },
      { qty: '8 oz', item: 'elbow macaroni (about 2 cups)' },
      { qty: '1 (8 oz) pkg', item: 'shredded Mexican cheese blend' },
      { qty: 'to taste', item: 'salt & black pepper' },
      { qty: '2 tbsp', item: 'fresh parsley or cilantro, chopped' },
    ],
    steps: [
      'Heat oil in a 12-inch nonstick skillet; add onion, chili powder, cumin, and ½ tsp salt. Cook over medium until soft, 5–7 minutes.',
      'Add garlic and brown sugar; stir about 30 seconds.',
      'Add ground beef and brown, breaking it apart, until no pink remains; drain excess grease.',
      'Add water, ¾ tsp salt, and tomato sauce; stir to combine.',
      'Stir in the pasta, cover, and increase heat to medium-high. Cook, stirring often, until pasta is tender, 9–12 minutes.',
      'Off heat, stir in 1 cup cheese; season with salt and pepper. Top with remaining cheese and let rest until melted. Sprinkle with parsley and serve.',
    ] }),
  familyLinkCard({ id: 'fam-seafood-paella', name: 'Easy Seafood Paella', emoji: '🥘', section: 'make agains', source: 'https://www.themediterraneandish.com/easy-seafood-paella-recipe/',
    time: '1 hr', serves: 6,
    ingredients: [
      { qty: '4 small', item: 'lobster tails (4–6 oz each)' },
      { qty: '3 tbsp', item: 'extra virgin olive oil' },
      { qty: '1 large', item: 'yellow onion, chopped' },
      { qty: '2 cups', item: 'Spanish Bomba rice, soaked 20 min & drained' },
      { qty: '4 cloves', item: 'garlic, chopped' },
      { qty: '2 large pinches', item: 'saffron threads, soaked in ½ cup water' },
      { qty: '1 tsp', item: 'sweet Spanish paprika' },
      { qty: '1 tsp', item: 'cayenne pepper' },
      { qty: '½ tsp', item: 'Aleppo / chili pepper flakes' },
      { qty: 'to taste', item: 'kosher salt' },
      { qty: '2 large', item: 'Roma tomatoes, finely chopped' },
      { qty: '6 oz', item: 'green beans, trimmed' },
      { qty: '1 lb', item: 'large shrimp, peeled & deveined' },
      { qty: '¼ cup', item: 'fresh parsley, chopped' },
    ],
    steps: [
      'Boil 3 cups water and add lobster tails (1–2 minutes until pink); remove, cool, and reserve the cooking water. Shell and cut into pieces.',
      'Heat olive oil in a large skillet over medium-high; sauté onions 2 minutes, add rice and cook 3 minutes, stirring.',
      'Add garlic, the reserved lobster water, saffron with its liquid, paprika, cayenne, Aleppo pepper, and salt.',
      'Stir in tomatoes and green beans; bring to a boil, reduce slightly, cover, and cook on low 20 minutes.',
      'Uncover and gently push the shrimp into the rice; add water if needed, cover, and cook 10 minutes until shrimp turn pink.',
      'Add the cooked lobster, warm through, then turn off the heat and garnish with parsley.',
    ] }),
  familyLinkCard({ id: 'fam-chicken-enchilada-soup', name: "Copycat Chili's Chicken Enchilada Soup", emoji: '🍲', section: 'make agains', source: 'https://thefoodcharlatan.com/chicken-enchilada-soup/',
    time: '50 min', serves: 10,
    ingredients: [
      { qty: '2 tsp', item: 'olive oil' },
      { qty: '1 large', item: 'onion, diced' },
      { qty: '1 tsp', item: 'salt' },
      { qty: '1½ tsp', item: 'chili powder' },
      { qty: '1½ tsp', item: 'cumin' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '5 cups', item: 'chicken broth' },
      { qty: '2 cups', item: 'water' },
      { qty: '1 cup', item: 'masa harina' },
      { qty: '1 (10 oz) can', item: 'enchilada sauce' },
      { qty: '1 lb', item: 'Velveeta, chopped' },
      { qty: '1 lb', item: 'shredded chicken' },
      { qty: 'to serve', item: 'cheddar, tortilla chips, avocado, pico de gallo' },
    ],
    steps: [
      'Heat oil in a large soup pot over medium-high; sauté onion ~4 minutes until translucent.',
      'Add salt, chili powder, and cumin, then the garlic; sauté 30 seconds until fragrant.',
      'Add the chicken broth. Whisk masa harina into 2 cups water, then stir the mixture into the pot.',
      'Add enchilada sauce and Velveeta; bring to a boil over high heat, stirring occasionally.',
      'Reduce to medium-low, add the shredded chicken, and simmer 30–40 minutes until thickened.',
      'Serve topped with pico de gallo, shredded cheddar, tortilla chips, and avocado.',
    ] }),
  familyLinkCard({ id: 'fam-naan', name: 'Naan (chewy & fluffy)', emoji: '🫓', category: 'snacks', section: 'make agains', source: 'https://www.recipetineats.com/naan-recipe/',
    time: '2 hr 30 min', serves: 6,
    ingredients: [
      { qty: '1 tsp', item: 'instant / rapid-rise yeast' },
      { qty: '½ cup', item: 'warm tap water' },
      { qty: '1 tbsp', item: 'white sugar' },
      { qty: '2 tbsp', item: 'full-fat milk' },
      { qty: '1½ tbsp', item: 'whisked egg' },
      { qty: '½ tsp', item: 'salt' },
      { qty: '1¾ cups', item: 'bread flour (or all-purpose)' },
      { qty: '2 tbsp', item: 'melted ghee or butter' },
      { qty: '2 tbsp', item: 'ghee or butter, for finishing' },
      { qty: 'to finish', item: 'nigella seeds & fresh coriander (optional garlic)' },
    ],
    steps: [
      'Mix yeast with the warm water and sugar; cover and let sit 10 minutes until foamy.',
      'Whisk the milk and egg together. Sift flour and salt into a bowl.',
      'Make a well in the flour; add the yeast mixture, melted butter, and egg mixture. Mix, then bring together by hand into a ball.',
      'Cover and proof 1–1.5 hours in a warm place until doubled.',
      'Turn out, cut into 6 pieces, and shape into smooth balls. Cover loosely and rest 15 minutes.',
      'Roll each ball into a 3–4 mm thick round (~16 cm).',
      'Heat a well-seasoned cast iron skillet over high heat until smoking. Cook each naan 60–90 seconds until golden and bubbly, flip, and cook 45–60 seconds more.',
      'Brush with melted ghee/butter and sprinkle with nigella seeds and coriander. Repeat.',
    ] }),
  familyLinkCard({ id: 'fam-instant-pot-chili', name: 'Instant Pot Chili', emoji: '🌶️', section: 'make agains', source: 'https://thestayathomechef.com/instant-pot-chili/', note: 'Super good',
    time: '1 hr 10 min', serves: 6,
    ingredients: [
      { qty: '2 lbs', item: 'beef chuck roast, cut into 1-inch pieces' },
      { qty: '1 tsp', item: 'salt' },
      { qty: '1 tsp', item: 'black pepper' },
      { qty: '2–4 tbsp', item: 'vegetable oil' },
      { qty: '1 cup', item: 'diced onion' },
      { qty: '2 cloves', item: 'garlic' },
      { qty: '1 (14.5 oz) can', item: 'beef broth' },
      { qty: '2 (15 oz) cans', item: 'red kidney beans, drained & rinsed' },
      { qty: '1 (14.5 oz) can', item: 'crushed tomatoes' },
      { qty: '2 (4.5 oz) cans', item: 'diced green chiles' },
      { qty: '3 tbsp', item: 'chili powder' },
      { qty: '2 tbsp', item: 'tomato paste' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '⅔ cup', item: 'finely crushed tortilla chips' },
      { qty: 'to serve', item: 'shredded cheese, cilantro, sour cream' },
    ],
    steps: [
      'Season beef with salt and pepper; brown in batches on Sauté with oil (~5 minutes each). Set aside.',
      'Add oil and onion to the pot; sauté 3 minutes, then add garlic for 1 minute.',
      'Stir in broth, tomatoes, beans, chiles, chili powder, tomato paste, cumin, and the beef.',
      'Lock the lid and cook on high pressure 25 minutes.',
      'Natural release 10 minutes, then quick release.',
      'Stir in the crushed tortilla chips and let rest uncovered 10 minutes to thicken. Serve with cheese, cilantro, and sour cream.',
    ] }),
  familyLinkCard({ id: 'fam-natchitoches-meat-pies', name: 'Natchitoches Meat Pies', emoji: '🥟', section: 'make agains', source: 'https://www.emerils.com/128002/natchitoches-meat-pies', note: 'Good',
    time: '2½ hr', serves: 8,
    ingredients: [
      { qty: 'For the filling', item: '—' },
      { qty: '1 tsp', item: 'vegetable oil' },
      { qty: '1 lb', item: 'ground beef' },
      { qty: '8 oz', item: 'ground pork' },
      { qty: '1 medium', item: 'yellow onion, chopped' },
      { qty: '2', item: 'green onions, chopped' },
      { qty: '½ medium', item: 'bell pepper, chopped' },
      { qty: '2 ribs', item: 'celery, chopped' },
      { qty: '1½ tsp', item: 'salt' },
      { qty: '½ tsp', item: 'black pepper' },
      { qty: '¼ tsp', item: 'cayenne pepper' },
      { qty: '2 tbsp', item: 'chopped garlic' },
      { qty: '1 tbsp', item: 'all-purpose flour' },
      { qty: '1 cup', item: 'beef stock' },
      { qty: '1 tbsp', item: 'hot sauce' },
      { qty: 'For the dough', item: '—' },
      { qty: '3 cups', item: 'all-purpose flour' },
      { qty: '1½ tsp', item: 'salt' },
      { qty: '¾ tsp', item: 'baking powder' },
      { qty: '6 tbsp', item: 'vegetable shortening' },
      { qty: '1', item: 'egg' },
      { qty: '¾ cup', item: 'whole milk' },
      { qty: 'for frying', item: 'vegetable oil' },
    ],
    steps: [
      'Brown the beef and pork; add the vegetables and seasonings and cook until soft.',
      'Add garlic, flour, and stock; simmer until thickened, stir in hot sauce, and cool.',
      'For the dough, mix flour, salt, and baking powder; cut in the shortening, then combine with the beaten egg and milk.',
      'Roll the dough into 24 rounds and fill each with about 2 tbsp of the meat mixture.',
      'Fold and crimp the edges; fry at 375°F until golden (~3 minutes) and drain on paper towels.',
    ] }),
  familyLinkCard({ id: 'fam-greek-chicken-orzo', name: 'Greek Baked Chicken Orzo', emoji: '🍗', section: 'make agains', source: 'https://www.themediterraneandish.com/greek-baked-chicken-orzo-recipe/',
    time: '40 min', serves: 6,
    ingredients: [
      { qty: 'For the chicken', item: '—' },
      { qty: '2 tsp', item: 'dried oregano' },
      { qty: '1 tsp', item: 'sweet paprika' },
      { qty: '1 tsp', item: 'ground coriander' },
      { qty: '1 tsp', item: 'kosher salt' },
      { qty: '1 tsp', item: 'black pepper' },
      { qty: '1½ lbs', item: 'boneless, skinless chicken thighs' },
      { qty: '½', item: 'lemon, juiced' },
      { qty: 'as needed', item: 'extra virgin olive oil' },
      { qty: 'For the orzo', item: '—' },
      { qty: '2', item: 'bell peppers, cored & sliced into rounds' },
      { qty: '1 large', item: 'yellow onion, chopped' },
      { qty: '6 cloves', item: 'garlic, minced' },
      { qty: '2 cups', item: 'canned peeled plum tomatoes with juice' },
      { qty: '2 cups', item: 'chicken broth' },
      { qty: '1 tsp', item: 'dried oregano' },
      { qty: '1 tsp', item: 'sweet paprika' },
      { qty: 'to taste', item: 'kosher salt & black pepper' },
      { qty: '2 cups', item: 'uncooked orzo' },
      { qty: 'to garnish', item: 'parsley & feta (optional)' },
    ],
    steps: [
      'Preheat oven to 350°F.',
      'Combine oregano, paprika, coriander, salt, and pepper; coat the dried chicken thighs, then add lemon juice and olive oil.',
      'Heat 2 tbsp olive oil in a Dutch oven over medium-high; brown the chicken 8–10 minutes per side and transfer to a plate.',
      'Sear the bell peppers in the same pot, then set aside with the chicken.',
      'Add onions and cook 5 minutes; add garlic for 30 seconds.',
      'Add tomatoes with juice, broth, oregano, paprika, salt, and pepper; bring to a boil.',
      'Stir in the orzo, nestle the chicken back in, and top with the peppers.',
      'Bake uncovered 20–25 minutes until the orzo is tender. Rest 5 minutes, then garnish with parsley and feta.',
    ] }),
  familyLinkCard({ id: 'fam-sun-dried-tomato-chicken', name: 'Sun-Dried Tomato Chicken', emoji: '🍗', section: 'make agains', source: 'https://www.themediterraneandish.com/sun-dried-tomato-chicken/',
    time: '30 min', serves: 6,
    ingredients: [
      { qty: '1½ lbs', item: 'chicken breasts' },
      { qty: '1 tbsp', item: 'Italian seasoning' },
      { qty: '1¼ tsp', item: 'kosher salt' },
      { qty: '2 tbsp', item: 'extra virgin olive oil' },
      { qty: '3 oz', item: 'sun-dried tomatoes, sliced' },
      { qty: '1 small', item: 'yellow onion, thinly sliced' },
      { qty: '4 large cloves', item: 'garlic, minced' },
      { qty: '⅓ cup', item: 'white wine' },
      { qty: '1¾ cups', item: 'whole milk' },
      { qty: '1½ tbsp', item: 'cornstarch' },
      { qty: '2 cups', item: 'baby spinach' },
      { qty: '¼ cup', item: 'sliced Kalamata olives' },
    ],
    steps: [
      'Slice the chicken breasts horizontally into cutlets; season with Italian seasoning and ¾ tsp salt.',
      'Heat olive oil in a large skillet over medium-high; cook the cutlets 4–6 minutes per side until 165°F. Transfer to a board.',
      'Add sun-dried tomatoes, onion, garlic, white wine, and ½ tsp salt to the skillet; scrape up the fond and cook 2–3 minutes.',
      'Add the milk. Make a slurry with the cornstarch and 3 tbsp cold water; stir into the simmering milk until thickened.',
      'Reduce heat to low; stir in spinach and olives until wilted. Slice the chicken, return to the pan to warm through, and serve.',
    ] }),
  familyLinkCard({ id: 'fam-creole-gumbo', name: 'New Orleans Creole Gumbo', emoji: '🍤', section: 'make agains', source: 'https://www.allrecipes.com/recipe/216888/good-new-orleans-creole-gumbo/', note: 'Good' }),
  familyLinkCard({ id: 'fam-air-fryer-greek-chicken', name: 'Air Fryer Greek Chicken & Veggies', emoji: '🍗', section: 'make agains', source: 'https://thestayathomechef.com/air-fryer-greek-chicken/', note: 'LOVED it!',
    time: '1 hr 25 min (incl. marinade)', serves: 2,
    ingredients: [
      { qty: '1 lb', item: 'boneless skinless chicken breast' },
      { qty: '¼ cup', item: 'olive oil' },
      { qty: '2 tbsp', item: 'white wine vinegar' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '1 tbsp', item: 'minced garlic' },
      { qty: '1 tbsp', item: 'Greek seasoning' },
      { qty: '1 tsp', item: 'salt' },
      { qty: '½ tsp', item: 'black pepper' },
      { qty: '1 medium', item: 'zucchini' },
      { qty: '½ medium', item: 'red onion' },
      { qty: '1 cup', item: 'cherry or grape tomatoes' },
      { qty: '½ cup', item: 'crumbled feta cheese' },
    ],
    steps: [
      'Pound the chicken to even thickness and place in a dish or sealable bag.',
      'Whisk olive oil, vinegar, lemon juice, garlic, Greek seasoning, salt, and pepper.',
      'Pour half the marinade over the chicken, coat, seal, and refrigerate 1–8 hours.',
      'Cut zucchini and red onion into ½-inch pieces; toss with the tomatoes and the remaining marinade.',
      'Preheat air fryer to 400°F. Cook the chicken 7 minutes.',
      'Flip the chicken, add the vegetables, and cook 7–8 minutes more until the chicken reaches 165°F. Serve topped with feta.',
    ] }),
  familyLinkCard({ id: 'fam-chicken-lazone', name: "Chef John's Chicken Lazone", emoji: '🍗', section: 'make agains', source: 'https://www.allrecipes.com/chicken-lazone-recipe-8621050', note: 'Five stars! Beat out the chicken, double the sauce using broth, double the seasoning & green onion, and cook the sauce down before adding',
    time: '30 min', serves: 4,
    ingredients: [
      { qty: '2 large', item: 'chicken breasts, halved lengthwise into cutlets' },
      { qty: '½ tsp', item: 'garlic powder' },
      { qty: 'to taste', item: 'salt & pepper' },
      { qty: 'for dredging', item: 'flour' },
      { qty: '2 tbsp', item: 'butter' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 cup', item: 'heavy / whipping cream' },
      { qty: '½ tsp', item: 'smoked paprika' },
      { qty: '½ tsp', item: 'onion powder' },
      { qty: '½ tsp', item: 'chili powder' },
      { qty: '¼ tsp', item: 'cayenne pepper' },
      { qty: '⅛ tsp', item: 'Italian seasoning' },
      { qty: 'to garnish', item: 'fresh parsley (or green onion)' },
    ],
    steps: [
      'Cut the chicken into 4 thin cutlets; season both sides with garlic powder, salt, and pepper, then coat in flour.',
      'Heat butter and oil in a skillet over medium-high; cook the chicken 4–5 minutes per side until golden. Transfer to a plate.',
      'Stir the cream into the skillet, scraping up the browned bits.',
      'Add the smoked paprika, onion powder, chili powder, cayenne, and Italian seasoning; whisk until smooth.',
      'Return the chicken and cook ~5 minutes until cooked through (165°F) and the sauce thickens. Garnish with parsley. (Per your note: double the sauce with a splash of broth and reduce before adding the chicken back.)',
    ] }),
  familyLinkCard({ id: 'fam-fiesta-chili', name: 'Slow Cooker Fiesta Chili Supper', emoji: '🌶️', section: 'make agains', source: 'https://skinnyms.com/slow-cooker-fiesta-chili-supper-recipe/',
    time: '6 hr 15 min', serves: 6,
    ingredients: [
      { qty: '1 lb', item: 'lean ground turkey' },
      { qty: '15 oz', item: 'red kidney beans, drained & rinsed' },
      { qty: '1 clove', item: 'garlic, minced' },
      { qty: '½ cup', item: 'chopped onion' },
      { qty: '3 cups', item: 'low-sodium chicken or vegetable broth' },
      { qty: '1½ cups', item: 'frozen corn kernels' },
      { qty: '½ cup', item: 'diced red bell pepper' },
      { qty: '2 tbsp', item: 'chili powder (plus more to taste)' },
      { qty: '1 tsp', item: 'cumin' },
      { qty: '1', item: 'chipotle chili in adobo, minced' },
      { qty: '2 tbsp', item: 'adobo sauce from the can' },
      { qty: '1', item: 'lime, cut into wedges' },
      { qty: '½ tsp', item: 'kosher or sea salt' },
      { qty: '½ tsp', item: 'black pepper' },
    ],
    steps: [
      'Brown the ground turkey in a skillet until no longer pink; drain and transfer to a slow cooker.',
      'Add all remaining ingredients (except the lime) to the slow cooker.',
      'Cook on low 6–8 hours.',
      'Serve with lime wedges and optional toppings like Greek yogurt, cilantro, or scallions.',
    ] }),
  familyLinkCard({ id: 'fam-taco-casserole', name: 'Tasty Taco Casserole', emoji: '🌮', section: 'make agains', source: 'https://thestayathomechef.com/taco-casserole/',
    time: '50 min', serves: 8,
    ingredients: [
      { qty: '2 tbsp', item: 'salted butter' },
      { qty: '1 medium', item: 'white onion, diced' },
      { qty: '1½ lbs', item: 'ground beef (80/20 or leaner)' },
      { qty: '1 (7 oz) can', item: 'diced green chiles' },
      { qty: '1 tbsp', item: 'ground cumin' },
      { qty: '2 tsp', item: 'salt' },
      { qty: '2 tsp', item: 'chili powder' },
      { qty: '2 tsp', item: 'garlic powder' },
      { qty: '12 (6-inch)', item: 'corn tortillas' },
      { qty: '2 tbsp', item: 'olive oil, divided' },
      { qty: '1 (14.5 oz) can', item: 'black beans, rinsed & drained' },
      { qty: '2 cups', item: 'salsa, divided' },
      { qty: '2 cups', item: 'corn kernels, divided' },
      { qty: '12 oz', item: 'shredded cheddar cheese (~3 cups), divided' },
    ],
    steps: [
      'Preheat oven to 350°F and grease a 9×13-inch baking dish.',
      'Melt the butter in a large skillet; cook onion 3–5 minutes until softened.',
      'Add beef, green chiles, cumin, salt, chili powder, and garlic powder; cook 6–8 minutes until browned.',
      'In a separate skillet, lightly fry the tortillas in olive oil ~1 minute per side; cut each in half.',
      'Layer half the tortillas in the dish; top with 1 cup cheese and half the beef.',
      'Add the beans, 1 cup salsa, and the remaining tortillas.',
      'Top with remaining beef, the corn, and remaining 1 cup salsa, then the remaining 2 cups cheese.',
      'Bake uncovered 25–30 minutes until bubbly. Cool slightly before serving.',
    ] }),
  familyLinkCard({ id: 'fam-tortellini-pasta-salad', name: 'Tortellini Pasta Salad', emoji: '🥗', category: 'lunch', section: 'make agains', source: 'https://thestayathomechef.com/tortellini-pasta-salad/',
    time: '1 hr 30 min (incl. chill)', serves: 8,
    ingredients: [
      { qty: 'Italian dressing', item: '—' },
      { qty: '⅔ cup', item: 'olive oil' },
      { qty: '2 tbsp', item: 'distilled white vinegar' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '1 tsp', item: 'salt' },
      { qty: '1 tsp', item: 'dried basil' },
      { qty: '1 tsp', item: 'dried oregano' },
      { qty: '½ tsp', item: 'onion powder' },
      { qty: '½ tsp', item: 'garlic powder' },
      { qty: '½ tsp', item: 'granulated sugar' },
      { qty: '½ tsp', item: 'dried parsley' },
      { qty: '¼ tsp', item: 'black pepper' },
      { qty: 'Pasta salad', item: '—' },
      { qty: '20 oz', item: 'cheese tortellini' },
      { qty: '1 medium', item: 'green bell pepper, diced' },
      { qty: '1 medium', item: 'zucchini, diced' },
      { qty: '½ pint', item: 'cherry/grape tomatoes, halved' },
      { qty: '½ cup', item: 'diced red onion' },
      { qty: '¼ cup', item: 'sliced pepperoncinis' },
      { qty: '8 oz', item: 'fresh mozzarella pearls' },
      { qty: '4 oz', item: 'sliced black olives' },
      { qty: '4 oz', item: 'cubed salami' },
    ],
    steps: [
      'Whisk all the dressing ingredients together in a small bowl.',
      'Cook the tortellini to al dente, rinse with cold water, and drain.',
      'Transfer the pasta to a serving bowl; pour over half the dressing and stir gently.',
      'Add the bell pepper, zucchini, tomatoes, red onion, pepperoncinis, mozzarella, olives, and salami.',
      'Pour over the remaining dressing and stir; cover and refrigerate 1 hour before serving cold.',
    ] }),
  familyLinkCard({ id: 'fam-black-bean-soup', name: 'Easy Black Bean Soup', emoji: '🍲', section: 'make agains', source: 'https://thestayathomechef.com/black-bean-soup/', note: 'Good — added pressure-cooked chicken breasts',
    time: '30 min', serves: 6,
    ingredients: [
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 medium', item: 'white onion, diced' },
      { qty: '1 medium', item: 'red bell pepper, diced' },
      { qty: '5 tsp', item: 'minced garlic' },
      { qty: '2 tsp', item: 'chili powder' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'paprika' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '3 (15 oz) cans', item: 'black beans, drained & rinsed' },
      { qty: '1 (15 oz) can', item: 'fire-roasted diced tomatoes' },
      { qty: '1 (7 oz) can', item: 'diced green chiles' },
      { qty: '1–2 tbsp', item: 'Mexican hot sauce (optional)' },
      { qty: '2 tbsp', item: 'lime juice' },
      { qty: '½ tsp', item: 'salt' },
    ],
    steps: [
      'Heat oil in a large pot over medium-high. Add onion and bell pepper; cook 5 minutes until softened.',
      'Add garlic, chili powder, cumin, and paprika; cook 1 minute to toast the spices.',
      'Pour in broth, beans, tomatoes, and green chiles; simmer 5 minutes.',
      'Partially blend with an immersion blender for thickness while keeping some texture.',
      'Off heat, stir in hot sauce, lime juice, and salt to taste. Serve with your favorite toppings.',
    ] }),

  // MAKE AGAINS favorites typed/annotated without a clean source link
  familyLinkCard({ id: 'fam-white-chicken-chili', name: 'Creamy White Chicken Chili', emoji: '🍲', section: 'make agains', note: 'I like this one — add a whole breast to cook in it' }),
  familyLinkCard({ id: 'fam-chicken-stew', name: 'Chicken Stew', emoji: '🍲', section: 'make agains', note: 'VERY GOOD' }),
  familyLinkCard({ id: 'fam-three-bean-power-soup', name: 'Three Bean Power Soup', emoji: '🍲', section: 'make agains', note: 'SUPER GOOD — high-protein with lentils, chickpeas & black beans' }),
  familyLinkCard({ id: 'fam-baked-ziti-turkey', name: 'Best Baked Ziti with Ground Turkey', emoji: '🍝', section: 'make agains' }),
  familyLinkCard({ id: 'fam-goat-cheese-pasta', name: 'Goat Cheese Pasta (one pot)', emoji: '🧀', section: 'make agains' }),

  // ── Full Meal Recipes + more clips (Sides / To Be Filed / Quick Notes) ──
  familyLinkCard({ id: 'fam-tuscan-tortellini', name: 'Tuscan Tortellini Skillet', emoji: '🍝', section: 'full meal recipes', source: 'https://www.thekitchn.com/tuscan-tortellini-pasta-260311',
    time: '20 min', serves: 4,
    ingredients: [
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 lb', item: 'fresh tomatoes, chopped' },
      { qty: '¾ tsp', item: 'salt' },
      { qty: '¼ tsp', item: 'black pepper' },
      { qty: 'pinch', item: 'red pepper flakes (optional)' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '20 oz', item: 'cheese tortellini' },
      { qty: '5 oz', item: 'baby spinach' },
      { qty: 'to serve', item: 'grated Parmesan cheese' },
    ],
    steps: [
      'Heat the oil in a heavy 10–12-inch skillet over medium until shimmering. Add the tomatoes, salt, pepper, and red pepper flakes; cook until the tomatoes soften and release their juices, 5–6 minutes.',
      'Stir in the garlic and cook until fragrant, about 1 minute.',
      'Increase heat to medium-high, stir in the tortellini, and cook until plump and tender, 3–5 minutes.',
      'Off the heat, stir in the spinach until just wilted, about 1 minute.',
      'Serve immediately with plenty of grated Parmesan.',
    ] }),
  familyLinkCard({ id: 'fam-animal-style-smashburger', name: 'Animal Style Smash Burger', emoji: '🍔', section: 'full meal recipes', note: 'THESE WERE GOOD — sauce: ~3 tbsp mayo, ~1 tbsp ketchup, 2 tsp sweet pickle relish' }),
  familyLinkCard({ id: 'fam-greek-breasts-mash', name: 'Greek Chicken Breasts with Mash', emoji: '🍗', section: 'full meal recipes', note: 'Typed recipe — tuned to go easy on the lemon' }),
  familyLinkCard({ id: 'fam-salmon-garlic-orzo', name: 'Salmon Fillets & Garlic Orzo', emoji: '🐟', section: 'full meal recipes', note: 'Garlic & chilli confit orzo; ~75g orzo, prep 5 min' }),
  familyLinkCard({ id: 'fam-churro-cheesecake-bars', name: 'Churro Cheesecake Bars', emoji: '🍰', category: 'desserts', section: 'to be filed', source: 'https://www.allrecipes.com/churro-cheesecake-bars-recipe-7554374' }),
  familyLinkCard({ id: 'fam-skillet-garlic-knot-chicken', name: 'Skillet Garlic Knot Chicken', emoji: '🍗', section: 'to be filed', source: 'https://www.allrecipes.com/skillet-garlic-knot-chicken-recipe-8762106' }),
  familyLinkCard({ id: 'fam-cod-provencal', name: 'Cod Provençal', emoji: '🐟', section: 'to be filed', source: 'https://www.themediterraneandish.com/cod-provencal/',
    time: '30 min', serves: 4,
    ingredients: [
      { qty: '1¼ lb', item: 'cod fillets, cut into 4 portions' },
      { qty: '1 tsp', item: 'kosher salt, divided (plus more)' },
      { qty: '½ tsp', item: 'black pepper (plus more)' },
      { qty: '2 tbsp', item: 'extra virgin olive oil' },
      { qty: '½ large', item: 'yellow onion, thinly sliced' },
      { qty: '½ bulb', item: 'fennel, cored & thinly sliced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1 (14.5 oz) can', item: 'crushed tomatoes' },
      { qty: '¼ cup', item: 'pitted Kalamata olives, halved' },
      { qty: '1 tbsp', item: 'fresh thyme leaves' },
      { qty: '1 tbsp', item: 'chopped parsley (plus more)' },
      { qty: '1', item: 'lemon, zested' },
    ],
    steps: [
      'Preheat oven to 350°F. Pat the cod dry and season with salt and pepper.',
      'Heat olive oil in a large cast iron skillet over medium-low. Add onion, fennel, and ½ tsp salt; cook 7–9 minutes until softened.',
      'Add garlic and cook 1 minute until fragrant.',
      'Stir in crushed tomatoes, olives, thyme, parsley, lemon zest, ½ tsp salt, and ¼ tsp pepper; cook 2 minutes until thickened.',
      'Nestle the cod into the sauce, spooning some over the top. Bake 6–8 minutes until the fish flakes easily.',
      'Season to taste, garnish with parsley, and serve.',
    ] }),
  familyLinkCard({ id: 'fam-sous-vide-teriyaki-salmon', name: 'Sous Vide Teriyaki Salmon', emoji: '🐟', section: 'quick notes', source: 'https://www.simplyrecipes.com/recipes/sous_vide_teriyaki_salmon/' }),
  familyLinkCard({ id: 'fam-grilled-salmon-avocado-salsa', name: 'Grilled Salmon with Avocado Salsa', emoji: '🐟', section: 'quick notes', source: 'https://www.thecookierookie.com/salmon-with-avocado/',
    time: '10 min + marinate', serves: 4,
    ingredients: [
      { qty: 'For the salmon', item: '—' },
      { qty: '2 lbs', item: 'salmon fillets' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'kosher salt' },
      { qty: '½ tsp', item: 'ancho chili powder' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'ground paprika' },
      { qty: '1 tsp', item: 'onion powder' },
      { qty: '1 tsp', item: 'ground black pepper' },
      { qty: 'For the avocado salsa', item: '—' },
      { qty: '1', item: 'avocado, cubed' },
      { qty: '½', item: 'red onion, diced' },
      { qty: '2', item: 'limes, juiced' },
      { qty: '1 tbsp', item: 'fresh cilantro, chopped' },
    ],
    steps: [
      'Combine the salt, chili powder, cumin, paprika, onion powder, and black pepper. Rub the salmon with olive oil and the seasoning.',
      'Refrigerate at least 30 minutes.',
      'Mix the avocado, onion, lime juice, and cilantro; chill until serving.',
      'Preheat a grill to medium (350–375°F).',
      'Grill the salmon 3–4 minutes per side until it flakes easily (145°F).',
      'Top with the avocado salsa and serve.',
    ] }),
  familyLinkCard({ id: 'fam-enchilada-stuffed-peppers', name: 'Cheesy Enchilada Stuffed Peppers', emoji: '🫑', section: 'quick notes', source: 'https://www.thecookierookie.com/cheesy-enchilada-stuffed-peppers/',
    time: '50 min', serves: 4,
    ingredients: [
      { qty: '1 lb', item: 'lean ground beef' },
      { qty: '1 oz', item: 'taco seasoning' },
      { qty: '½', item: 'onion, diced' },
      { qty: '1 (4.5 oz) can', item: 'chopped green chiles' },
      { qty: '¼ cup', item: 'red enchilada sauce' },
      { qty: '4 large', item: 'bell peppers' },
      { qty: '2 cups', item: 'shredded Mexican blend cheese' },
    ],
    steps: [
      'Preheat oven to 350°F and line a baking sheet with foil.',
      'Brown the ground beef over medium-high, crumbling as it cooks; drain.',
      'Stir in the taco seasoning, add the onion, and cook until translucent.',
      'Mix in the green chiles and enchilada sauce; turn off the heat.',
      'Cut the tops off the peppers, remove ribs and seeds, and place on the sheet.',
      'Layer each pepper with the beef mixture and cheese, starting and ending with cheese.',
      'Replace the tops and bake 30–40 minutes until the peppers are tender and the cheese melts. Serve with sour cream and cilantro if desired.',
    ] }),
  familyLinkCard({ id: 'fam-shirazi-salad', name: 'Simple Shirazi Salad', emoji: '🥗', category: 'lunch', section: 'to be filed', source: 'https://www.themediterraneandish.com/shirazi-salad-recipe/',
    time: '15 min', serves: 4,
    ingredients: [
      { qty: '3', item: 'Roma tomatoes, small diced' },
      { qty: '1', item: 'English cucumber (or 4 Persian), small diced' },
      { qty: '¼–½ cup', item: 'finely chopped red or yellow onion' },
      { qty: '½', item: 'green bell pepper, chopped small (optional)' },
      { qty: '2–3 tbsp each', item: 'chopped fresh parsley, cilantro & dill' },
      { qty: '1 tbsp', item: 'dried mint (or ½ cup fresh)' },
      { qty: 'to taste', item: 'salt, pepper & sumac' },
      { qty: '2 large', item: 'limes, juiced (~4 tbsp)' },
      { qty: '3 tbsp', item: 'extra virgin olive oil' },
    ],
    steps: [
      'Place the diced tomatoes in a colander a few minutes to drain excess liquid.',
      'Combine the tomatoes, cucumbers, onions, and bell pepper in a large bowl.',
      'Add the fresh herbs, dried mint, salt, pepper, and sumac.',
      'Add the lime juice and olive oil; toss to combine.',
      'Chill 30 minutes to 1 hour for best flavor (optional).',
    ] }),
  familyLinkCard({ id: 'fam-sheet-pan-gnocchi', name: 'Sheet Pan Gnocchi with Roasted Vegetables', emoji: '🥘', section: 'to be filed', source: 'https://www.themediterraneandish.com/sheet-pan-gnocchi-with-roasted-vegetables/',
    time: '55 min', serves: 4,
    ingredients: [
      { qty: '16 oz', item: 'gnocchi' },
      { qty: '1', item: 'red bell pepper, chopped' },
      { qty: '1', item: 'yellow bell pepper, chopped' },
      { qty: '1', item: 'red onion, chopped' },
      { qty: '1 pint', item: 'cherry tomatoes' },
      { qty: '6 cloves', item: 'garlic, minced' },
      { qty: '¼ cup', item: 'olive oil' },
      { qty: '1½ tsp', item: 'dried oregano' },
      { qty: '1½ tsp', item: 'dried basil' },
      { qty: '1 tsp', item: 'kosher salt' },
      { qty: '½ tsp', item: 'dried thyme' },
      { qty: '¼ tsp', item: 'red pepper flakes' },
      { qty: 'to taste', item: 'black pepper' },
      { qty: '3–4 handfuls', item: 'baby spinach' },
      { qty: 'to serve', item: 'Parmesan cheese' },
    ],
    steps: [
      'Preheat oven to 425°F.',
      'On a sheet pan, toss the gnocchi, peppers, onion, tomatoes, garlic, olive oil, and seasonings until well coated.',
      'Bake 40 minutes, stirring halfway through.',
      'Five minutes before the end, stir in the spinach and return to the oven until wilted.',
      'Serve with shaved Parmesan and a drizzle of olive oil.',
    ] }),
  familyLinkCard({ id: 'fam-southwest-chicken-bake', name: 'Southwest Chicken Bake', emoji: '🍗', section: 'quick notes', source: 'https://www.thecookierookie.com/southwest-chicken-enchilada-baked-chicken/' }),
  familyLinkCard({ id: 'fam-one-pot-italian-pasta-chicken', name: 'One-Pot Cheesy Italian Pasta & Chicken', emoji: '🍝', section: 'quick notes', source: 'http://www.theslowroasteditalian.com/2016/10/one-pot-cheesy-Italian-Pasta-Chicken-recipe.html',
    time: '20 min', serves: 6,
    ingredients: [
      { qty: '8 oz', item: 'baby spinach leaves, divided' },
      { qty: '1 cup', item: 'sun-dried tomatoes in oil, drained' },
      { qty: '1 large', item: 'yellow onion, sliced' },
      { qty: '1 lb', item: 'chicken breasts, cut into ½-inch pieces' },
      { qty: '6 cloves', item: 'garlic, sliced' },
      { qty: '1 lb', item: 'dry linguine' },
      { qty: '2 tsp', item: 'Italian seasoning' },
      { qty: '2 tsp', item: 'kosher salt' },
      { qty: '1 tsp', item: 'fresh ground pepper' },
      { qty: '1 tsp', item: 'crushed red pepper flakes' },
      { qty: '32 oz (4 cups)', item: 'reduced-sodium chicken stock' },
      { qty: '8 oz (1 cup)', item: 'chardonnay wine' },
      { qty: '4 oz', item: 'fresh Parmesan, shredded' },
    ],
    steps: [
      'In a 5-quart Dutch oven over medium-high, combine half the spinach with the tomatoes, onion, chicken, garlic, pasta, Italian seasoning, salt, pepper, and red pepper flakes. Pour the stock and wine over top.',
      'Cover and bring to a boil.',
      'Cook 7–9 minutes until the pasta is al dente, tossing occasionally with tongs so it doesn’t stick.',
      'Turn off the heat and add the Parmesan, tossing until melted. Stir in the remaining spinach and serve.',
    ] }),
  familyLinkCard({ id: 'fam-honey-roasted-chickpeas', name: 'Honey Roasted Chickpeas', emoji: '🌰', category: 'snacks', section: 'quick notes', source: 'https://skinnyms.com/honey-roasted-chickpeas-recipe/',
    time: '50 min', serves: 8,
    ingredients: [
      { qty: '15 oz', item: 'chickpeas, drained & rinsed' },
      { qty: '1½ tsp', item: 'coconut oil, melted' },
      { qty: '2 tbsp', item: 'honey' },
      { qty: '½ tsp', item: 'cinnamon' },
      { qty: '⅛ tsp', item: 'nutmeg' },
      { qty: '¼ tsp', item: 'ground clove' },
      { qty: '¼ tsp', item: 'cayenne pepper' },
      { qty: '½ tsp', item: 'kosher or sea salt' },
    ],
    steps: [
      'Preheat oven to 375°F.',
      'Pat the chickpeas dry, toss with the coconut oil, and spread on a parchment-lined baking sheet.',
      'Bake 30–40 minutes until crispy.',
      'Mix the honey, spices, and salt; toss the hot chickpeas in the blend and return to the sheet.',
      'Bake 10 more minutes until glazed. Cool completely before serving.',
    ] }),
  familyLinkCard({ id: 'fam-delish-white-chicken-chili', name: 'Best White Chicken Chili (Delish)', emoji: '🍲', section: 'quick notes', source: 'https://www.delish.com/cooking/recipe-ideas/a57946/easy-white-chicken-chili/', note: 'Super good, super easy — 5*' }),
  familyLinkCard({ id: 'fam-oven-roasted-potatoes', name: 'Easy Oven Roasted Potatoes', emoji: '🥔', section: 'quick notes', source: 'https://www.spendwithpennies.com/simple-herb-oven-roasted-potatoes/',
    time: '45 min', serves: 6,
    ingredients: [
      { qty: '2 lbs', item: 'red, yellow, or Yukon gold potatoes' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'garlic powder' },
      { qty: '3 tbsp', item: 'fresh herbs (or 2 tsp dried)' },
      { qty: '½ tsp', item: 'paprika' },
      { qty: 'to taste', item: 'kosher salt & black pepper' },
    ],
    steps: [
      'Heat the oven to 425°F.',
      'Clean and cut the potatoes into 1-inch cubes. Optionally soak in cold water 20 min–1 hr, then drain and dry well.',
      'Toss the potatoes with the olive oil, garlic powder, herbs, paprika, salt, and pepper.',
      'Spread in a single layer on a baking sheet.',
      'Roast 30–35 minutes until browned and tender.',
    ] }),
  familyLinkCard({ id: 'fam-bacon-mozzarella-sticks', name: 'Bacon-Crusted Mozzarella Sticks', emoji: '🧀', category: 'snacks', section: 'quick notes', source: 'https://pomanmeals.com/crispy-bacon-crusted-mozzarella-cheese-sticks/',
    time: '20 min', serves: 12,
    ingredients: [
      { qty: '1 pkg', item: 'string cheese, cut in half' },
      { qty: '2', item: 'eggs, beaten' },
      { qty: '1 cup', item: 'bacon bits' },
      { qty: '1 cup', item: 'panko breadcrumbs' },
      { qty: '1 tbsp', item: 'dried parsley' },
      { qty: '1 tsp', item: 'garlic powder' },
      { qty: 'for frying', item: 'oil' },
    ],
    steps: [
      'Beat the eggs in a bowl and set aside.',
      'Pulse the bacon bits in a food processor until fine; add the panko, parsley, and garlic powder and pulse to combine. Pour into a dish.',
      'Dip each mozzarella stick in egg, then roll in the bacon mixture until coated.',
      'Place on a tray and freeze completely.',
      'Heat oil to 350°F and fry the sticks until golden brown. Cool slightly before serving. (Can also be baked.)',
    ] }),

);
