// ════════════════════════════════════════════
//  Built-in content for the 📚 Guides tab:
//  high-protein foods, vitamins & minerals
//  reference, and tips & guides.
//  FODMAP flags: green = low-FODMAP as listed,
//  yellow = fine in the portion shown, red = avoid.
// ════════════════════════════════════════════

const HIGH_PROTEIN_GUIDE = [
  {
    id: 'meat',
    label: '🥩 Meat & Poultry',
    blurb: 'Plain, unseasoned meat has zero FODMAPs — watch marinades, crumbing and sausages instead.',
    items: [
      { emoji: '🍗', name: 'Chicken breast',        protein: 31, serving: 'per 100 g cooked (palm-size)', fodmap: 'green' },
      { emoji: '🦃', name: 'Turkey breast',         protein: 30, serving: 'per 100 g cooked',             fodmap: 'green' },
      { emoji: '🥩', name: 'Lean beef (sirloin)',   protein: 27, serving: 'per 100 g cooked',             fodmap: 'green', note: 'also loaded with iron, zinc & B12' },
      { emoji: '🐖', name: 'Pork tenderloin',       protein: 26, serving: 'per 100 g cooked',             fodmap: 'green' },
      { emoji: '🍗', name: 'Chicken thigh',         protein: 24, serving: 'per 100 g cooked',             fodmap: 'green', note: 'more iron than breast' },
      { emoji: '🍖', name: 'Lamb',                  protein: 25, serving: 'per 100 g cooked',             fodmap: 'green' },
      { emoji: '🥓', name: 'Beef jerky (plain)',    protein: 10, serving: 'per 30 g (small handful)',     fodmap: 'yellow', note: 'check the label — skip garlic & onion flavors' },
      { emoji: '🌭', name: 'Sausages & burgers, pre-made', protein: 12, serving: 'per 100 g', fodmap: 'red', note: 'usually contain garlic/onion — make your own instead' },
    ],
  },
  {
    id: 'fish',
    label: '🐟 Fish & Seafood',
    blurb: 'All plain fish and shellfish are FODMAP-free, and the oily ones bring omega-3s too.',
    items: [
      { emoji: '🐟', name: 'Salmon',                 protein: 25, serving: 'per 100 g cooked', fodmap: 'green', note: 'best everyday source of omega-3 + vitamin D' },
      { emoji: '🥫', name: 'Canned tuna (in water)', protein: 24, serving: 'per 100 g (1 small can)', fodmap: 'green', note: 'cheapest protein in the pantry' },
      { emoji: '🍤', name: 'Shrimp',                 protein: 24, serving: 'per 100 g cooked', fodmap: 'green' },
      { emoji: '🐟', name: 'Sardines (canned)',      protein: 23, serving: 'per 100 g',        fodmap: 'green', note: 'eat the soft bones for a big calcium boost' },
      { emoji: '🐟', name: 'Cod / white fish',       protein: 20, serving: 'per 100 g cooked', fodmap: 'green', note: 'very lean and easy on the gut' },
      { emoji: '🦀', name: 'Crab',                   protein: 19, serving: 'per 100 g cooked', fodmap: 'green' },
    ],
  },
  {
    id: 'eggs-dairy',
    label: '🥚 Eggs & Dairy',
    blurb: 'The FODMAP in dairy is lactose — lactose-free versions and hard cheeses keep all the protein.',
    items: [
      { emoji: '🥛', name: 'Greek yogurt, lactose-free', protein: 17, serving: 'per ¾ cup (170 g)', fodmap: 'green', note: 'regular Greek yogurt is moderate-high in lactose' },
      { emoji: '🧀', name: 'Cottage cheese, lactose-free', protein: 12, serving: 'per ½ cup', fodmap: 'green', note: 'regular cottage cheese only in small (2 tbsp) amounts' },
      { emoji: '🥛', name: 'Lactose-free milk',      protein: 8,  serving: 'per 1 cup',          fodmap: 'green' },
      { emoji: '🧀', name: 'Hard cheese (cheddar, parmesan, swiss)', protein: 7, serving: 'per 30 g slice', fodmap: 'green', note: 'naturally almost lactose-free' },
      { emoji: '🥚', name: 'Eggs',                   protein: 6,  serving: 'each',               fodmap: 'green', note: '2–3 eggs = a real protein serving + choline' },
      { emoji: '🧀', name: 'String cheese',          protein: 7,  serving: 'per stick',          fodmap: 'green', note: 'great grab-and-go snack' },
    ],
  },
  {
    id: 'plant',
    label: '🌱 Plant Proteins',
    blurb: 'Portions matter most here — canned and rinsed legumes carry far fewer FODMAPs than dried.',
    items: [
      { emoji: '🌱', name: 'Tempeh',                 protein: 19, serving: 'per 100 g',            fodmap: 'green' },
      { emoji: '🌱', name: 'Firm / extra-firm tofu', protein: 17, serving: 'per 170 g',            fodmap: 'green', note: 'silken tofu is HIGH FODMAP — always pick firm' },
      { emoji: '🎃', name: 'Pumpkin seeds (pepitas)',protein: 9,  serving: 'per ¼ cup',            fodmap: 'green', note: 'also a top magnesium & zinc source' },
      { emoji: '🌱', name: 'Canned lentils, rinsed', protein: 9,  serving: 'per ½ cup',            fodmap: 'yellow', note: 'stay at ½ cup — dried lentils are much higher FODMAP' },
      { emoji: '🥜', name: 'Peanut butter',          protein: 8,  serving: 'per 2 tbsp',           fodmap: 'green', note: 'check the label for added honey/inulin' },
      { emoji: '🌾', name: 'Quinoa, cooked',         protein: 8,  serving: 'per 1 cup',            fodmap: 'green', note: 'a complete protein grain' },
      { emoji: '🥜', name: 'Roasted peanuts',        protein: 7,  serving: 'per ¼ cup (32 nuts)',  fodmap: 'green' },
      { emoji: '🌱', name: 'Edamame',                protein: 9,  serving: 'per ½ cup',            fodmap: 'yellow', note: 'keep to ½ cup' },
      { emoji: '🌱', name: 'Canned chickpeas, rinsed', protein: 3, serving: 'per ¼ cup',           fodmap: 'yellow', note: '¼ cup is the safe portion' },
      { emoji: '🌰', name: 'Hemp seeds',             protein: 10, serving: 'per 3 tbsp',           fodmap: 'green', note: 'stir into yogurt or oatmeal' },
      { emoji: '🌰', name: 'Almonds',                protein: 3,  serving: 'per 10 nuts',          fodmap: 'yellow', note: '10 nuts is the safe portion; a big handful is high' },
    ],
  },
  {
    id: 'boosters',
    label: '⚡ Easy Protein Boosters',
    blurb: 'Sneaky ways to raise the protein of meals you already make.',
    items: [
      { emoji: '🥤', name: 'Whey protein isolate powder', protein: 24, serving: 'per scoop', fodmap: 'yellow', note: 'isolate is low-lactose; skip whey concentrate and anything with inulin/chicory' },
      { emoji: '🥚', name: 'Egg whites (carton)',    protein: 11, serving: 'per ⅓ cup', fodmap: 'green', note: 'whisk into oatmeal or scrambles' },
      { emoji: '🧀', name: 'Grated parmesan',        protein: 8,  serving: 'per 2 tbsp', fodmap: 'green', note: 'over veg, eggs, rice, pasta' },
      { emoji: '🥛', name: 'Ultra-filtered lactose-free milk (e.g. Fairlife)', protein: 13, serving: 'per 1 cup', fodmap: 'green', note: '~60% more protein than regular milk' },
      { emoji: '🥫', name: 'Tuna or salmon pouch',   protein: 16, serving: 'per pouch', fodmap: 'green', note: 'no can-opener needed — desk-drawer friendly' },
      { emoji: '🌰', name: 'Chia seeds',             protein: 5,  serving: 'per 2 tbsp', fodmap: 'green', note: 'plus fiber and omega-3 ALA' },
    ],
  },
];

// Superfoods that stay friendly on low-FODMAP. "portion" is the
// FODMAP-safe serve where it matters; "why" is the nutrition payoff;
// "use" is the easiest way to actually eat it.
const SUPERFOODS_GUIDE = [
  {
    id: 'fruit',
    label: '🫐 Fruits & Berries',
    blurb: 'Antioxidant heavyweights that don’t upset the gut — portions noted where they matter.',
    items: [
      { emoji: '🥝', name: 'Kiwi', fodmap: 'green', portion: '2 kiwis',
        why: 'A full day of vitamin C in one fruit, plus fiber and actinidin — clinically shown to help regularity.',
        use: 'Halve and scoop with a spoon; two a day is the gut-health classic.' },
      { emoji: '🫐', name: 'Blueberries', fodmap: 'yellow', portion: '¼ cup safe; keep to a small handful',
        why: 'Among the highest-antioxidant everyday foods — anthocyanins linked to brain and heart health.',
        use: 'On lactose-free yogurt or oatmeal; frozen are just as good and cheaper.' },
      { emoji: '🍓', name: 'Strawberries', fodmap: 'green', portion: '~10 medium berries',
        why: 'More vitamin C than an orange per cup, with folate and polyphenols.',
        use: 'Straight snack, or sliced over oats with chia.' },
      { emoji: '🍊', name: 'Oranges', fodmap: 'green', portion: '1 medium',
        why: 'Vitamin C, folate, potassium — and the whole fruit brings fiber that juice loses.',
        use: 'Eat the fruit, skip the juice; segments brighten spinach salads.' },
      { emoji: '🍌', name: 'Firm banana', fodmap: 'yellow', portion: 'firm/just-ripe only — very ripe is higher FODMAP',
        why: 'Potassium, B6 and resistant starch that feeds good gut bacteria.',
        use: 'With peanut butter, or sliced into oatmeal.' },
      { emoji: '🍈', name: 'Papaya', fodmap: 'green', portion: '½ cup',
        why: 'Vitamins A and C plus papain, an enzyme that helps digestion.',
        use: 'Cubed with a squeeze of lime.' },
    ],
  },
  {
    id: 'veg',
    label: '🥬 Greens & Vegetables',
    blurb: 'The most nutrient-dense veg that stay low-FODMAP in real portions.',
    items: [
      { emoji: '🥬', name: 'Baby spinach', fodmap: 'green', portion: '1½ cups raw',
        why: 'Folate, vitamin K, magnesium, iron and lutein for eye health — all in a handful.',
        use: 'Sauté in olive oil with lemon (the C doubles iron absorption), or blend into smoothies.' },
      { emoji: '🥬', name: 'Kale', fodmap: 'green', portion: '1 cup',
        why: 'A week of vitamin K per serve, plus calcium your body absorbs unusually well from greens.',
        use: 'Massage with olive oil for salads, or crisp in the air fryer.' },
      { emoji: '🥕', name: 'Carrots', fodmap: 'green', portion: 'unlimited — FODMAP-free',
        why: 'Beta-carotene for eyes, skin and immunity; one of the only truly unlimited vegetables.',
        use: 'Roast in olive oil to unlock far more vitamin A than raw.' },
      { emoji: '🫑', name: 'Red bell pepper', fodmap: 'yellow', portion: '⅓ cup',
        why: 'Weight-for-weight more vitamin C than citrus, plus carotenoids.',
        use: 'Strips with a cheese slice, or roasted alongside dinner.' },
      { emoji: '🥦', name: 'Broccoli (heads)', fodmap: 'yellow', portion: '¾ cup heads — stalks are higher FODMAP',
        why: 'Sulforaphane — the most studied anti-inflammatory plant compound — plus C, K and folate.',
        use: 'Steam or roast the florets; go easy on the stalks.' },
      { emoji: '🍠', name: 'Sweet potato', fodmap: 'yellow', portion: '½ cup (75 g)',
        why: 'Beta-carotene, potassium and gentle fiber.',
        use: 'Roasted cubes; pair the half-cup with regular potato to fill the plate.' },
      { emoji: '🎃', name: 'Kabocha / Japanese pumpkin', fodmap: 'green', portion: '½ cup (75 g)',
        why: 'Beta-carotene dense and naturally sweet without the FODMAPs of butternut.',
        use: 'Roast wedges, or mash with a little butter.' },
    ],
  },
  {
    id: 'seeds',
    label: '🌰 Seeds, Nuts & Healthy Fats',
    blurb: 'Small portions, big returns — most of these cover a nutrient for the whole day.',
    items: [
      { emoji: '🌱', name: 'Chia seeds', fodmap: 'green', portion: '2 tbsp',
        why: 'Omega-3 ALA, 8 g of fiber, calcium and protein in two spoonfuls.',
        use: 'Overnight chia pudding with lactose-free milk, or stir into oatmeal.' },
      { emoji: '🎃', name: 'Pumpkin seeds', fodmap: 'green', portion: '¼ cup',
        why: 'The everyday champion for magnesium and zinc, with iron and protein too.',
        use: 'Toast and sprinkle on yogurt, salads and soups.' },
      { emoji: '🌰', name: 'Walnuts', fodmap: 'green', portion: '10 halves',
        why: 'The only common nut rich in omega-3s — consistently linked to brain and heart health.',
        use: 'A small handful with fruit, or chopped over oatmeal.' },
      { emoji: '🌾', name: 'Ground flaxseed', fodmap: 'yellow', portion: '1 tbsp',
        why: 'Omega-3s, lignans and gentle fiber; must be ground to absorb.',
        use: 'A spoonful into smoothies, oats or yogurt — buy ground or grind fresh.' },
      { emoji: '🫒', name: 'Extra-virgin olive oil', fodmap: 'green', portion: 'FODMAP-free',
        why: 'The backbone fat of the Mediterranean diet — polyphenols and vitamin E.',
        use: 'Your default cooking and dressing oil; finish vegetables with a drizzle.' },
      { emoji: '🌰', name: 'Brazil nuts', fodmap: 'green', portion: '1–2 nuts (don’t exceed 3–4/day)',
        why: 'One nut carries a full day of selenium for thyroid and antioxidant defense.',
        use: 'One a day, done — the easiest superfood habit there is.' },
      { emoji: '🍫', name: 'Dark chocolate (85%+)', fodmap: 'green', portion: '~20 g (a couple of squares)',
        why: 'Flavanols for blood pressure, plus magnesium and iron.',
        use: 'A square after dinner with peppermint tea.' },
    ],
  },
  {
    id: 'protein',
    label: '🐟 Protein Superfoods',
    blurb: 'Protein that pulls double duty — omega-3s, calcium, B12 and probiotics come along free.',
    items: [
      { emoji: '🐟', name: 'Salmon', fodmap: 'green', portion: 'FODMAP-free',
        why: 'The standout single food: omega-3s, vitamin D, B12, selenium and 25 g protein per 100 g.',
        use: 'Twice a week; canned counts and costs a third of fresh.' },
      { emoji: '🐟', name: 'Sardines', fodmap: 'green', portion: 'FODMAP-free',
        why: 'Omega-3s plus a major calcium hit from the soft bones — and very low in mercury.',
        use: 'On sourdough spelt or GF toast with lemon and pepper.' },
      { emoji: '🥚', name: 'Eggs', fodmap: 'green', portion: 'FODMAP-free',
        why: 'Choline for memory, lutein for eyes, vitamin D and complete protein — mostly in the yolk.',
        use: 'Keep hard-boiled ones in the fridge for snacks and salads.' },
      { emoji: '🌱', name: 'Tempeh', fodmap: 'green', portion: '100 g',
        why: 'Fermented soy: 19 g protein plus iron, calcium and fermentation-friendly compounds.',
        use: 'Pan-fry slices in olive oil until golden; takes on any glaze.' },
      { emoji: '🥛', name: 'Lactose-free kefir / yogurt', fodmap: 'green', portion: 'lactose-free versions only',
        why: 'Live probiotic cultures plus calcium and protein — regular kefir is high-FODMAP, lactose-free is not.',
        use: 'Breakfast base for berries, chia and pumpkin seeds.' },
    ],
  },
  {
    id: 'pantry',
    label: '🍵 Healing Pantry',
    blurb: 'The seasonings and sips with real evidence behind them — all low-FODMAP.',
    items: [
      { emoji: '🫚', name: 'Fresh ginger', fodmap: 'green', portion: 'FODMAP-free',
        why: 'One of the best-evidenced natural remedies for nausea and sluggish digestion.',
        use: 'Grate into stir-fries, or steep slices as tea after heavy meals.' },
      { emoji: '🟡', name: 'Turmeric', fodmap: 'green', portion: '1 tsp',
        why: 'Curcumin, a well-studied anti-inflammatory — absorbed far better with black pepper and fat.',
        use: 'Into rice, eggs or a golden-milk latte with lactose-free milk + a pinch of pepper.' },
      { emoji: '🍂', name: 'Cinnamon', fodmap: 'green', portion: '1 tsp',
        why: 'Polyphenols linked to steadier blood sugar after meals.',
        use: 'On oatmeal, yogurt and roasted sweet potato.' },
      { emoji: '🍵', name: 'Green tea', fodmap: 'green', portion: 'brewed weak-to-normal',
        why: 'EGCG catechins tied to heart and brain health; gentler caffeine than coffee.',
        use: '1–3 cups a day; avoid oolong, which is high-FODMAP.' },
      { emoji: '🌾', name: 'Oats', fodmap: 'green', portion: '½ cup dry',
        why: 'Beta-glucan fiber with the strongest cholesterol-lowering evidence of any everyday food.',
        use: 'Oatmeal or overnight oats — the base that carries half the foods on this list.' },
      { emoji: '🌾', name: 'Quinoa & buckwheat', fodmap: 'green', portion: '1 cup cooked',
        why: 'Complete-protein whole grains with magnesium, iron and B vitamins.',
        use: 'Batch-cook and use as the ¼-plate carb all week.' },
    ],
  },
];

// RDA values are for healthy adults (NIH Office of Dietary Supplements).
// "over50" carries the age-specific change where there is one.
const NUTRIENTS_GUIDE = [
  {
    emoji: '💪', name: 'Protein', kind: 'Macronutrient',
    rda: 'Women: ~46 g/day · Men: ~56 g/day (0.8 g per kg body weight — the minimum, not the ideal)',
    over50: 'Over 50, most experts suggest 1.0–1.2 g per kg to protect muscle — e.g. ~68–82 g for a 150 lb person.',
    why: 'Builds and preserves muscle, keeps you full, supports immune function and healing. Muscle loss accelerates after 50, and protein is the main defense.',
    low: 'Losing strength, constant hunger, slow recovery, hair/nail changes, getting sick often.',
    sources: [
      'Chicken breast — 31 g per 100 g',
      'Salmon or canned tuna — 24–25 g per 100 g',
      'Lactose-free Greek yogurt — 17 g per ¾ cup',
      'Firm tofu — 17 g per 170 g',
      'Eggs — 6 g each',
    ],
    tip: 'Spread it out: aim for 25–30 g at each meal rather than one big dinner. Breakfast is where most people fall short.',
  },
  {
    emoji: '🌾', name: 'Fiber', kind: 'Macronutrient',
    rda: 'Women: 25 g/day · Men: 38 g/day',
    over50: 'Over 50: 21 g (women) / 30 g (men).',
    why: 'Feeds good gut bacteria, keeps digestion regular, steadies blood sugar and lowers cholesterol. Extra important — and extra tricky — on low-FODMAP.',
    low: 'Constipation, energy crashes after meals, always hungry again quickly.',
    sources: [
      'Oats — 4 g per ½ cup dry',
      'Chia seeds — 8 g per 2 tbsp',
      'Kiwi fruit — 4 g per 2 kiwis',
      'Quinoa — 5 g per cup cooked',
      'Carrots, potatoes with skin, green beans',
      'Oranges & strawberries',
    ],
    tip: 'Increase slowly (a few grams per week) and drink more water as you go, or fiber itself will bloat you.',
  },
  {
    emoji: '🦴', name: 'Calcium', kind: 'Mineral',
    rda: 'Adults: 1,000 mg/day',
    over50: 'Women 51+: 1,200 mg/day.',
    why: 'Bone strength — plus muscle contractions, nerves and heart rhythm. Cutting regular dairy on low-FODMAP makes this the #1 nutrient to watch.',
    low: 'No early symptoms — it silently comes out of your bones. Long-term: osteoporosis, fractures, brittle nails.',
    sources: [
      'Lactose-free milk — 300 mg per cup',
      'Lactose-free yogurt — 300 mg per ¾ cup',
      'Canned sardines/salmon with bones — 240–320 mg per 100 g',
      'Hard cheese — 200 mg per 30 g slice',
      'Calcium-set firm tofu — ~250 mg per 100 g (check the label for "calcium sulfate")',
      'Kale, cooked — 130 mg per cup',
      'Fortified almond milk — 300–450 mg per cup',
    ],
    tip: 'Your body absorbs ~500 mg at a time, so split sources across the day rather than one big hit.',
  },
  {
    emoji: '🩸', name: 'Iron', kind: 'Mineral',
    rda: 'Women 19–50: 18 mg/day · Women 51+ & men: 8 mg/day',
    why: 'Carries oxygen in your blood. The most common nutrient deficiency in women.',
    low: 'Fatigue that sleep doesn’t fix, breathlessness on stairs, pale skin, feeling cold, brain fog.',
    sources: [
      'Lean beef — 2.7 mg per 100 g (best-absorbed form)',
      'Chicken thigh — 1.3 mg per 100 g',
      'Canned lentils, rinsed — 3 mg per ½ cup',
      'Pumpkin seeds — 2.5 mg per ¼ cup',
      'Baby spinach — 1 mg per cup (pair with vitamin C)',
      'Quinoa — 2.8 mg per cup cooked',
    ],
    tip: 'Vitamin C doubles plant-iron absorption — squeeze lemon on spinach, add strawberries to oatmeal. Tea and coffee block it, so keep them an hour away from iron-rich meals.',
  },
  {
    emoji: '✨', name: 'Magnesium', kind: 'Mineral',
    rda: 'Women: 310–320 mg/day · Men: 400–420 mg/day',
    why: 'Involved in 300+ body processes: muscle relaxation, sleep quality, blood pressure, blood sugar, mood. Roughly half of adults fall short.',
    low: 'Muscle cramps and eye twitches, poor sleep, fatigue, headaches, constipation.',
    sources: [
      'Pumpkin seeds — 156 mg per ¼ cup (the champion)',
      'Chia seeds — 95 mg per 2 tbsp',
      'Baby spinach, cooked — 78 mg per ½ cup',
      'Quinoa — 118 mg per cup cooked',
      'Peanuts — 63 mg per ¼ cup',
      'Dark chocolate 85% — 65 mg per 20 g (small square is low-FODMAP)',
      'Firm banana — 32 mg',
    ],
    tip: 'A daily sprinkle of pumpkin + chia seeds on yogurt or oatmeal quietly covers a third of your day.',
  },
  {
    emoji: '🫀', name: 'Potassium', kind: 'Mineral',
    rda: 'Women: 2,600 mg/day · Men: 3,400 mg/day',
    why: 'Balances sodium to keep blood pressure down, prevents muscle cramps, supports heart rhythm. Most people get barely half.',
    low: 'Muscle weakness and cramps, fatigue, high blood pressure creeping up.',
    sources: [
      'Potato with skin — 900 mg per medium potato (the champion)',
      'Salmon — 490 mg per 100 g',
      'Baby spinach, cooked — 420 mg per ½ cup',
      'Firm (just-ripe) banana — 420 mg (very ripe = more FODMAPs)',
      'Lactose-free milk — 380 mg per cup',
      'Orange — 240 mg',
      'Kiwi — 215 mg each',
    ],
    tip: 'Potatoes are FODMAP-free in any amount — a baked potato is one of the best potassium moves you can make.',
  },
  {
    emoji: '🛡️', name: 'Zinc', kind: 'Mineral',
    rda: 'Women: 8 mg/day · Men: 11 mg/day',
    why: 'Immune defense, wound healing, taste and smell, skin health.',
    low: 'Frequent colds, slow-healing cuts, dulled taste/smell, hair shedding.',
    sources: [
      'Beef — 4.8 mg per 100 g (by far the best source)',
      'Pork — 2.9 mg per 100 g',
      'Pumpkin seeds — 2.2 mg per ¼ cup',
      'Shrimp/crab — 1.5–6 mg per 100 g',
      'Oats — 1.5 mg per ½ cup dry',
      'Eggs — 0.6 mg each',
    ],
    tip: 'A palm of beef or pork twice a week plus daily seeds covers most people without a supplement.',
  },
  {
    emoji: '👁️', name: 'Vitamin A', kind: 'Vitamin',
    rda: 'Women: 700 mcg RAE/day · Men: 900 mcg RAE/day',
    why: 'Night vision, immune function, skin repair.',
    low: 'Poor night vision, dry eyes and skin, more infections.',
    sources: [
      'Carrots — 500 mcg per medium carrot (FODMAP-free!)',
      'Sweet potato — 960 mcg per ½ cup (stay at ½ cup / 75 g)',
      'Baby spinach, cooked — 570 mcg per ½ cup',
      'Cantaloupe — 135 mcg per ¾ cup (keep portion modest)',
      'Eggs — 80 mcg each',
    ],
    tip: 'It’s fat-soluble: roast carrots in olive oil rather than steaming them plain, and you’ll absorb far more.',
  },
  {
    emoji: '⚡', name: 'Vitamin B12', kind: 'Vitamin',
    rda: 'Adults: 2.4 mcg/day',
    over50: 'After 50, stomach acid drops and B12 absorbs poorly from food — fortified foods or a supplement are officially recommended.',
    why: 'Nerve function, red blood cells, DNA, energy metabolism.',
    low: 'Fatigue, tingling hands/feet, memory slips, low mood, sore tongue. Develops slowly over years.',
    sources: [
      'Sardines — 8.9 mcg per 100 g',
      'Salmon — 4.8 mcg per 100 g',
      'Beef — 2.6 mcg per 100 g',
      'Canned tuna — 2.5 mcg per 100 g',
      'Eggs — 0.5 mcg each',
      'Lactose-free milk — 1.2 mcg per cup',
    ],
    tip: 'Only found naturally in animal foods — if you’re mostly plant-based, this is the one supplement that’s non-negotiable.',
  },
  {
    emoji: '🍃', name: 'Folate (B9)', kind: 'Vitamin',
    rda: 'Adults: 400 mcg DFE/day',
    why: 'Cell renewal, red blood cells, works with B12 to manage homocysteine (heart health).',
    low: 'Fatigue, irritability, mouth sores, greying hair.',
    sources: [
      'Baby spinach, cooked — 130 mcg per ½ cup',
      'Broccoli heads — 84 mcg per ¾ cup (heads are lower-FODMAP than stalks)',
      'Peanuts — 88 mcg per ¼ cup',
      'Orange — 55 mcg',
      'Eggs — 22 mcg each',
      'Many GF breads & cereals are fortified — check the label',
    ],
    tip: 'Folate is destroyed by long boiling — steam or sauté greens briefly instead.',
  },
  {
    emoji: '🧠', name: 'Vitamin B6', kind: 'Vitamin',
    rda: 'Adults: 1.3 mg/day',
    over50: 'Women 51+: 1.5 mg · Men 51+: 1.7 mg.',
    why: 'Brain chemistry (serotonin, dopamine), immune support, protein metabolism — the more protein you eat, the more B6 you need.',
    low: 'Low mood, irritability, cracked lip corners, weakened immunity.',
    sources: [
      'Chicken breast — 0.9 mg per 100 g',
      'Salmon — 0.9 mg per 100 g',
      'Potato with skin — 0.6 mg per medium',
      'Firm banana — 0.4 mg',
      'Beef — 0.4 mg per 100 g',
    ],
    tip: 'A chicken-and-potato dinner covers your whole day.',
  },
  {
    emoji: '🍊', name: 'Vitamin C', kind: 'Vitamin',
    rda: 'Women: 75 mg/day · Men: 90 mg/day',
    why: 'Collagen production (skin, joints, blood vessels), iron absorption, antioxidant, immune support.',
    low: 'Slow healing, easy bruising, bleeding gums, fatigue.',
    sources: [
      'Kiwi — 64 mg each (one kiwi ≈ a full day!)',
      'Strawberries — 85 mg per cup',
      'Orange — 70 mg',
      'Red bell pepper — 38 mg per ⅓ cup (stick to ⅓ cup)',
      'Broccoli heads — 60 mg per ¾ cup',
      'Potato — 30 mg per medium',
    ],
    tip: 'Your body can’t store it — a little every day beats a lot occasionally.',
  },
  {
    emoji: '☀️', name: 'Vitamin D', kind: 'Vitamin',
    rda: 'Adults: 600 IU (15 mcg)/day',
    over50: 'Adults 70+: 800 IU (20 mcg). Many doctors test levels and recommend 1,000–2,000 IU in winter.',
    why: 'Calcium absorption (bones), muscle strength, immune function, mood. Very hard to get from food alone.',
    low: 'Bone/muscle aches, low mood (especially winter), frequent illness, fatigue.',
    sources: [
      'Salmon — 570 IU per 100 g (the standout)',
      'Canned sardines — 190 IU per 100 g',
      'Egg yolks — 44 IU each',
      'Fortified lactose-free milk — 120 IU per cup',
      'Sunshine — 10–30 min on arms/face, a few times a week',
    ],
    tip: 'If you’re rarely in midday sun, this is the most worthwhile supplement to ask your doctor about.',
  },
  {
    emoji: '🌻', name: 'Vitamin E', kind: 'Vitamin',
    rda: 'Adults: 15 mg/day',
    why: 'Protects cell membranes from oxidation; supports skin and immune health.',
    low: 'Rare, but shows as muscle weakness and slow healing.',
    sources: [
      'Sunflower seeds — 7.4 mg per ¼ cup (half your day)',
      'Almonds — 2.7 mg per 10 nuts',
      'Peanut butter — 2.9 mg per 2 tbsp',
      'Olive oil — 1.9 mg per tbsp',
      'Kiwi — 1 mg each',
    ],
    tip: 'Cooking with olive oil and snacking on seeds quietly gets you there — no supplement needed.',
  },
  {
    emoji: '🥬', name: 'Vitamin K', kind: 'Vitamin',
    rda: 'Women: 90 mcg/day · Men: 120 mcg/day',
    why: 'Blood clotting and moving calcium into bones (works alongside vitamin D).',
    low: 'Easy bruising, heavy bleeding from small cuts.',
    sources: [
      'Kale, cooked — 500+ mcg per ½ cup (a week’s worth)',
      'Baby spinach — 145 mcg per cup raw',
      'Broccoli heads — 110 mcg per ¾ cup',
      'Green beans — 43 mcg per cup',
      'Cucumber, lettuce — small but steady amounts',
    ],
    tip: 'On blood thinners like warfarin? Keep your greens intake steady day to day rather than cutting them out — and tell your doctor.',
  },
  {
    emoji: '🐟', name: 'Omega-3 (EPA/DHA & ALA)', kind: 'Healthy fat',
    rda: 'ALA: women 1.1 g · men 1.6 g/day. For EPA/DHA: two servings of oily fish per week.',
    why: 'Heart health, brain function, and dialing down body-wide inflammation.',
    low: 'Dry skin, joint stiffness, low mood, poor concentration.',
    sources: [
      'Salmon — 2.2 g per 100 g (the gold standard)',
      'Sardines — 1.5 g per 100 g',
      'Canned tuna — 0.3 g per 100 g',
      'Chia seeds — 5 g ALA per 2 tbsp',
      'Walnuts — 2.5 g ALA per 10 halves (10 halves is the low-FODMAP portion)',
      'Ground flaxseed — 1.6 g ALA per tbsp (1 tbsp max)',
    ],
    tip: 'Canned salmon and sardines give you the same omega-3s as fresh for a third of the price.',
  },
  {
    emoji: '🌰', name: 'Selenium', kind: 'Mineral',
    rda: 'Adults: 55 mcg/day',
    why: 'Thyroid hormone production and antioxidant defense.',
    low: 'Fatigue, hair thinning, weakened immunity — often alongside thyroid issues.',
    sources: [
      'Brazil nuts — ~90 mcg per single nut (1–2 nuts = done; don’t exceed 3–4/day)',
      'Canned tuna — 80 mcg per 100 g',
      'Sardines — 53 mcg per 100 g',
      'Chicken — 27 mcg per 100 g',
      'Eggs — 15 mcg each',
    ],
    tip: 'One Brazil nut a day is the easiest nutrient win in this entire guide.',
  },
  {
    emoji: '🧂', name: 'Iodine', kind: 'Mineral',
    rda: 'Adults: 150 mcg/day',
    why: 'Thyroid hormones — which set your metabolism, energy and temperature.',
    low: 'Sluggishness, feeling cold, weight creep, dry skin, brain fog.',
    sources: [
      'Iodized salt — 76 mcg per ¼ tsp (check yours is iodized — many sea/kosher salts aren’t)',
      'Cod — 158 mcg per 100 g',
      'Shrimp — 41 mcg per 100 g',
      'Eggs — 26 mcg each',
      'Lactose-free milk & yogurt — 60–85 mcg per cup',
    ],
    tip: 'Switched to fancy sea salt? You may have quietly lost your main iodine source — keep iodized salt for everyday cooking.',
  },
  {
    emoji: '🥚', name: 'Choline', kind: 'Other',
    rda: 'Women: 425 mg/day · Men: 550 mg/day',
    why: 'Memory and brain-cell membranes, liver fat processing, muscle control. Most people have never heard of it — and most fall short.',
    low: 'Brain fog, memory slips, fatty-liver risk.',
    sources: [
      'Eggs — 147 mg each (the champion — it’s all in the yolk)',
      'Beef — 85 mg per 100 g',
      'Salmon — 79 mg per 100 g',
      'Chicken breast — 72 mg per 100 g',
      'Potatoes — 57 mg per medium',
    ],
    tip: 'Two eggs at breakfast gets you most of the way — eat the whole egg, not just whites.',
  },
];

const GUIDE_TIPS = [
  {
    emoji: '🥨', title: 'Best grab-and-go snacks',
    sub: 'The snacks worth keeping in your bag, desk and car — full portable list lives in Tools → Snacks.',
    blocks: [
      { title: '💪 Protein-forward (keeps you full)', list: [
        'Hard-boiled eggs — 6 g protein each, prep a batch on Sunday',
        'String cheese — 7 g protein, no fridge needed for a few hours',
        'Lactose-free Greek yogurt cup + pumpkin seeds',
        'Tuna or salmon pouch — 16 g protein, no can opener',
        'Plain beef jerky — check for garlic/onion in the ingredients',
        'Roasted peanuts or a 10-almond pack',
      ]},
      { title: '🍓 Sweet but safe', list: [
        'Firm banana with 2 tbsp peanut butter',
        'Kiwi or mandarin — portable and vitamin C loaded',
        'Strawberries or grapes (about 1 cup)',
        'Rice cakes with peanut butter and banana slices',
        'A square of dark chocolate (85%, ~20 g)',
      ]},
      { title: '🧂 Salty & crunchy', list: [
        'Plain popcorn — up to 7 cups popped is low-FODMAP',
        'Plain potato chips or corn chips (small bag)',
        'Rice crackers with a slice of cheddar',
        'Carrot sticks — FODMAP-free in any amount',
      ]},
    ],
  },
  {
    emoji: '💪', title: 'How much protein do you actually need?',
    sub: 'Almost everyone over 50 needs more than the official minimum.',
    blocks: [
      { title: 'The numbers', list: [
        'Official minimum: 0.8 g per kg of body weight — for a 150 lb (68 kg) person that’s just 54 g/day',
        'Better target over 50: 1.0–1.2 g per kg — that same person should aim for 68–82 g/day',
        'Strength training or recovering from illness: up to 1.2–1.6 g per kg',
      ]},
      { title: 'How to hit it without thinking', list: [
        'Aim for 25–30 g per meal — one palm-sized portion of meat/fish, or eggs + dairy + seeds combined',
        'Fix breakfast first: most people eat 10 g at breakfast and 50 g at dinner. Your muscles prefer it spread out',
        'Easy breakfast upgrades: 2 eggs (12 g) + LF Greek yogurt (17 g), or oatmeal made with LF milk + chia + peanut butter (~20 g)',
        'Keep "emergency protein" around: tuna pouches, string cheese, boiled eggs',
      ]},
    ],
  },
  {
    emoji: '🏷️', title: 'Reading labels like a pro',
    sub: 'The FODMAPs hiding in ingredient lists — and the words that give them away.',
    blocks: [
      { title: '🚩 Red-flag ingredients', list: [
        'Inulin / chicory root fiber — added to "high fiber" bars, yogurts and protein powders; a major bloater',
        'Garlic powder, onion powder, "dehydrated vegetables" — in almost every seasoning blend, stock cube and chip flavor',
        'Honey, agave, high-fructose corn syrup — excess fructose',
        'Sorbitol, mannitol, xylitol, maltitol (anything ending in -ol) — sugar-free gum and candy',
        'Whey (unless "isolate"), milk solids, buttermilk — lactose',
        'Wheat as a main ingredient — small amounts (e.g. soy sauce) are usually fine',
      ]},
      { title: '✅ Usually fine despite sounding scary', list: [
        'Maltodextrin, dextrose, glucose, plain cane sugar (sucrose)',
        'Maple syrup and rice malt syrup',
        '"Natural flavors" — usually fine, but if a savory product tastes garlicky, trust your tongue',
        'Firm tofu, tempeh, sourdough spelt bread — processing removes FODMAPs',
      ]},
      { title: '💡 Fast rules', list: [
        'The further down the ingredient list, the smaller the amount — a FODMAP in position 8 of 10 is usually tolerable',
        '"Gluten-free" does NOT mean low-FODMAP (may contain honey, inulin, apple juice)',
        'Certified low-FODMAP logos (Monash, FODMAP Friendly) do the checking for you',
      ]},
    ],
  },
  {
    emoji: '🌾', title: 'Fiber without the bloat',
    sub: 'Low-FODMAP cuts many fiber sources — here’s how to get enough anyway.',
    blocks: [
      { title: 'Gentlest high-fiber foods', list: [
        'Chia seeds — 8 g per 2 tbsp; make overnight chia pudding with LF milk',
        'Oats — 4 g per ½ cup; oatmeal or overnight oats',
        'Kiwi — 4 g per 2 fruit; also clinically shown to help regularity',
        'Potato & sweet potato with skin (sweet potato: ½ cup)',
        'Quinoa, brown rice, buckwheat',
        'Carrots, green beans, zucchini, eggplant',
        'Oranges & strawberries',
      ]},
      { title: 'The rules that make fiber work', list: [
        'Go up slowly — add one new fiber source every few days, not all at once',
        'Water is half the equation — fiber without fluid makes constipation worse',
        'Movement counts — a 10-minute walk after meals genuinely helps digestion',
        'If bloated, check portions of the yellow-light foods before blaming fiber itself',
      ]},
    ],
  },
  {
    emoji: '🦴', title: 'Strong bones after 50',
    sub: 'The four-part formula — diet is only half of it.',
    blocks: [
      { title: 'The formula', list: [
        'Calcium 1,200 mg/day (women 51+) — see the Vitamins & Minerals tab for the best sources',
        'Vitamin D 600–800 IU — salmon, eggs, fortified milk, sunshine; ask your doctor about testing',
        'Protein at every meal — bone is ~50% protein by volume',
        'Resistance + impact exercise — walking, stairs, weights, resistance bands 2–3× a week; bones only strengthen when loaded',
      ]},
      { title: 'Bone-friendly, FODMAP-safe day', list: [
        'Breakfast: LF Greek yogurt + chia + strawberries (calcium + protein)',
        'Lunch: canned salmon (with bones!) on sourdough spelt or GF bread',
        'Dinner: any protein + potato + kale sautéed in olive oil',
        'Snack: string cheese or a LF milk latte',
      ]},
    ],
  },
  {
    emoji: '🥗', title: 'Building a balanced low-FODMAP plate',
    sub: 'The simple template that covers nutrition without a spreadsheet.',
    blocks: [
      { title: 'The plate', list: [
        '½ plate: low-FODMAP vegetables — carrots, zucchini, green beans, spinach, bell pepper (⅓ cup), eggplant, cucumber, tomato',
        '¼ plate: protein — meat, fish, eggs, firm tofu, tempeh',
        '¼ plate: hearty carbs — potato, rice, quinoa, GF pasta, oats',
        'Plus: a thumb of healthy fat (olive oil, seeds, nuts in portion) and a calcium source most meals',
      ]},
      { title: 'Daily checkpoints', list: [
        '2+ pieces of low-FODMAP fruit (kiwi, orange, strawberries, firm banana, grapes)',
        '3 calcium hits (LF dairy, hard cheese, fortified milk, canned fish with bones)',
        'Protein at all three meals, not just dinner',
        'Oily fish twice a week for omega-3s',
        'One Brazil nut (selenium — done)',
      ]},
    ],
  },
  {
    emoji: '💧', title: 'Hydration & electrolytes',
    sub: 'Half of "hungry", "tired" and "headachy" is actually thirsty.',
    blocks: [
      { title: 'Targets', list: [
        'Roughly 8–10 cups (2–2.5 L) of fluid a day — more in heat or with exercise',
        'Water, sparkling water, and most herbal teas (peppermint, ginger) are low-FODMAP',
        'Coffee is low-FODMAP but a gut stimulant — 1–2 cups, ideally not on an empty stomach',
        'Watch: chamomile and oolong tea are high-FODMAP; fruit juices concentrate fructose',
      ]},
      { title: 'Electrolytes without a sports drink', list: [
        'Potassium: potatoes, bananas, oranges, spinach (see Vitamins & Minerals)',
        'Sodium: normal iodized salt on food is fine for most people',
        'Magnesium: pumpkin seeds, chia, quinoa',
        'DIY rehydrator: water + squeeze of orange/lemon + pinch of salt',
      ]},
    ],
  },
];
