// SuperAge Lunch Recipes
// Healthy, high-fiber "longevity carb" lunches based on a SuperAge article
// covering a 30-year study (JAMA Network Open) linking high-quality, fiber-rich
// carbohydrates to healthier aging. Star foods: whole grains, fruits,
// vegetables, and legumes.

const SUPERAGE_LUNCH = [
  {
    id: 'sa-lu-lentil-carrot-quinoa-bowl',
    name: 'Lentil & Roasted Carrot Quinoa Bowl',
    emoji: '🥗',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1 cup', item: 'cooked brown or green lentils' },
      { qty: '3 medium', item: 'carrots, cut into coins' },
      { qty: '2 cups', item: 'baby spinach' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '2 tbsp', item: 'tahini' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss carrot coins with 1 tbsp olive oil, cumin, salt, and pepper.',
      'Roast carrots 20-25 minutes until caramelized and tender, flipping once.',
      'Whisk tahini, lemon juice, remaining olive oil, and 2-3 tbsp water into a pourable dressing.',
      'Divide quinoa and lentils between two bowls. Top with roasted carrots and fresh spinach.',
      'Drizzle with lemon-tahini dressing and serve.',
    ],
    superAgeNote: 'Lentils and quinoa are exactly the fiber-rich, minimally processed carbs the JAMA Network Open study links to healthier aging, keeping the carb-to-fiber ratio well under 10:1.',
    nutrition: { cal: 480, protein: 18, fiber: 15 },
    airfryer: [
      'Air fry carrot coins at 380F (193C) for 14-16 minutes, shaking halfway, until caramelized and tender.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chickpea-broccoli-kale-lemon-tahini',
    name: 'Chickpea, Broccoli & Kale Salad with Lemon-Tahini Dressing',
    emoji: '🥬',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '2 cups', item: 'broccoli florets' },
      { qty: '3 cups', item: 'chopped kale, stems removed' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '1 clove', item: 'garlic, grated' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Steam or blanch broccoli florets 3-4 minutes until bright green and crisp-tender, then cool.',
      'Place chopped kale in a bowl, drizzle with 1 tbsp olive oil, and massage 1-2 minutes until softened.',
      'Whisk tahini, lemon juice, garlic, remaining oil, salt, pepper, and 2-3 tbsp water into a creamy dressing.',
      'Add chickpeas and broccoli to the kale. Pour dressing over and toss to coat.',
      'Serve immediately or chill for later.',
    ],
    superAgeNote: 'Chickpeas plus kale and broccoli stack legume and vegetable fiber, the high-quality carbohydrate pattern the 30-year study associates with healthier aging.',
    nutrition: { cal: 440, protein: 17, fiber: 16 },
    airfryer: [
      'For a warm version, air fry broccoli florets at 380F (193C) for 8-10 minutes until edges crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-black-bean-barley-roasted-broccoli',
    name: 'Black Bean & Barley Bowl with Roasted Broccoli',
    emoji: '🥦',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked pearl barley' },
      { qty: '1.5 cups', item: 'cooked black beans' },
      { qty: '3 cups', item: 'broccoli florets' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 tbsp', item: 'lime juice' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss broccoli with 1 tbsp olive oil, paprika, salt, and pepper.',
      'Roast broccoli 18-20 minutes until edges are browned and crisp.',
      'Warm black beans in a small pan with a splash of water and a pinch of salt.',
      'Divide barley between two bowls and top with beans and roasted broccoli.',
      'Whisk remaining oil with lime juice, drizzle over the bowls, and serve.',
    ],
    superAgeNote: 'Pearl barley and black beans are both fiber-dense whole carbs; barley beta-glucan and bean fiber reflect the low carb-to-fiber ratio tied to healthier aging.',
    nutrition: { cal: 470, protein: 18, fiber: 17 },
    airfryer: [
      'Air fry broccoli at 390F (199C) for 10-12 minutes, shaking halfway, until charred at the edges.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-quinoa-tabbouleh-chickpeas-spinach',
    name: 'Quinoa Tabbouleh with Chickpeas & Spinach',
    emoji: '🥗',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'cooked quinoa, cooled' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '2 cups', item: 'baby spinach, chopped' },
      { qty: '1 cup', item: 'flat-leaf parsley, chopped' },
      { qty: '1 cup', item: 'cherry tomatoes, halved' },
      { qty: '3 tbsp', item: 'lemon juice' },
      { qty: '3 tbsp', item: 'olive oil' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'In a large bowl, combine cooled quinoa, chickpeas, chopped spinach, parsley, and tomatoes.',
      'Whisk lemon juice, olive oil, salt, and pepper into a bright dressing.',
      'Pour dressing over the salad and toss well to combine.',
      'Let sit 10 minutes so flavors meld, then serve.',
    ],
    superAgeNote: 'This no-cook bowl leans on quinoa and chickpeas, the whole-grain and legume carbs the JAMA Network Open study links with better odds of healthy aging.',
    nutrition: { cal: 450, protein: 16, fiber: 13 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-lentil-soup-carrots-greens',
    name: 'Lentil Soup with Carrots & Leafy Greens',
    emoji: '🍲',
    category: 'lunch',
    time: '40 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'dried brown lentils, rinsed' },
      { qty: '2 medium', item: 'carrots, diced' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '3 cups', item: 'chopped kale or Swiss chard' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat olive oil in a pot and cook onion, carrots, and garlic 5 minutes until softened.',
      'Stir in cumin, then add lentils and vegetable broth. Bring to a boil.',
      'Reduce heat and simmer 25-30 minutes until lentils are tender.',
      'Stir in chopped greens and cook 5 more minutes until wilted.',
      'Season with salt and pepper and serve hot.',
    ],
    superAgeNote: 'A bowl of lentils with carrots and greens delivers the fiber-rich, minimally refined carbohydrates associated with healthier aging in the 30-year study.',
    nutrition: { cal: 420, protein: 20, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-millet-black-bean-roasted-carrots',
    name: 'Millet & Black Bean Salad with Roasted Carrots',
    emoji: '🥕',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked millet, cooled' },
      { qty: '1.5 cups', item: 'cooked black beans' },
      { qty: '3 medium', item: 'carrots, cut into coins' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'ground coriander' },
      { qty: '2 tbsp', item: 'lime juice' },
      { qty: '2 tbsp', item: 'chopped cilantro' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss carrots with 1 tbsp oil, coriander, salt, and pepper.',
      'Roast carrots 20-25 minutes until tender and caramelized.',
      'In a bowl, combine millet and black beans.',
      'Whisk remaining oil with lime juice, then toss through the millet and beans.',
      'Fold in roasted carrots and cilantro, then serve warm or chilled.',
    ],
    superAgeNote: 'Millet and black beans pair a gluten-free whole grain with legume fiber, matching the high-quality carbohydrate pattern linked to healthier aging.',
    nutrition: { cal: 460, protein: 16, fiber: 15 },
    airfryer: [
      'Air fry carrot coins at 380F (193C) for 14-16 minutes, shaking once, until tender and browned.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chickpea-broccoli-grain-bowl-tahini',
    name: 'Chickpea & Broccoli Grain Bowl with Tahini Dressing',
    emoji: '🥣',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '3 cups', item: 'broccoli florets' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss broccoli and chickpeas with 1 tbsp oil, cumin, salt, and pepper.',
      'Roast 18-22 minutes until broccoli is crisp-tender and chickpeas are golden.',
      'Whisk tahini, lemon juice, remaining oil, and 2-3 tbsp water into a smooth dressing.',
      'Divide quinoa between bowls and top with roasted broccoli and chickpeas.',
      'Drizzle generously with tahini dressing and serve.',
    ],
    superAgeNote: 'Chickpeas, quinoa, and broccoli together keep the carb-to-fiber ratio low, reflecting the fiber-rich carbohydrate quality the study ties to healthier aging.',
    nutrition: { cal: 500, protein: 19, fiber: 16 },
    airfryer: [
      'Air fry chickpeas and broccoli together at 390F (199C) for 12-14 minutes, shaking halfway, until crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-barley-black-bean-minestrone-kale',
    name: 'Barley & Black Bean Minestrone with Kale',
    emoji: '🍲',
    category: 'lunch',
    time: '45 min',
    serves: 2,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '0.5 cup', item: 'pearl barley, rinsed' },
      { qty: '1.5 cups', item: 'cooked black beans' },
      { qty: '2 medium', item: 'carrots, diced' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 can (14 oz)', item: 'diced tomatoes' },
      { qty: '3 cups', item: 'chopped kale' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'dried oregano' },
    ],
    steps: [
      'Heat olive oil in a pot and cook onion, carrots, and garlic 5 minutes until softened.',
      'Stir in oregano and barley, then add tomatoes and broth. Bring to a boil.',
      'Reduce heat and simmer 25-30 minutes until barley is tender.',
      'Add black beans and kale; cook 5-7 minutes more until kale is wilted.',
      'Season to taste and serve hot.',
    ],
    superAgeNote: 'Barley and black beans anchor this minestrone in the whole-grain and legume fiber the JAMA Network Open study links to healthier aging.',
    nutrition: { cal: 430, protein: 17, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-quinoa-lentil-stuffed-peppers-spinach',
    name: 'Quinoa & Lentil Stuffed Peppers with Spinach',
    emoji: '🫑',
    category: 'lunch',
    time: '50 min',
    serves: 2,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '2 large', item: 'bell peppers, halved and seeded' },
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1 cup', item: 'cooked brown lentils' },
      { qty: '2 cups', item: 'baby spinach, chopped' },
      { qty: '0.5 cup', item: 'tomato sauce' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 400F (204C). Rub pepper halves with olive oil and place in a baking dish.',
      'In a bowl, mix quinoa, lentils, spinach, tomato sauce, paprika, salt, and pepper.',
      'Spoon the filling into the pepper halves, mounding slightly.',
      'Cover with foil and bake 30 minutes, then uncover and bake 10 more minutes.',
      'Let rest 5 minutes and serve.',
    ],
    superAgeNote: 'Quinoa and lentils packed into peppers deliver the fiber-rich whole grains and legumes the 30-year study associates with healthier aging.',
    nutrition: { cal: 440, protein: 18, fiber: 16 },
    airfryer: [
      'Air fry stuffed pepper halves at 360F (182C) for 14-16 minutes until peppers are tender and tops are set.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chickpea-salad-sandwich-spinach',
    name: 'Chickpea Salad Sandwich with Spinach',
    emoji: '🥪',
    category: 'lunch',
    time: '15 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '2 tbsp', item: 'tahini' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '1 stalk', item: 'celery, finely diced' },
      { qty: '1 tbsp', item: 'Dijon mustard' },
      { qty: '2 cups', item: 'baby spinach' },
      { qty: '4 slices', item: 'whole-grain bread' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Mash chickpeas in a bowl with a fork, leaving some texture.',
      'Stir in tahini, lemon juice, celery, mustard, salt, and pepper.',
      'Pile spinach onto two slices of whole-grain bread.',
      'Top with the chickpea salad, close the sandwiches, and serve.',
    ],
    superAgeNote: 'Chickpeas on whole-grain bread combine legume and whole-wheat fiber, the higher-quality carbohydrates linked to healthier aging.',
    nutrition: { cal: 430, protein: 18, fiber: 14 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-broccoli-cheddar-barley-soup',
    name: 'Broccoli-Cheddar Barley Soup',
    emoji: '🍲',
    category: 'lunch',
    time: '40 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian'],
    ingredients: [
      { qty: '0.5 cup', item: 'pearl barley, rinsed' },
      { qty: '3 cups', item: 'broccoli florets, chopped' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '0.75 cup', item: 'shredded sharp cheddar' },
      { qty: '0.5 cup', item: 'milk' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat olive oil in a pot and cook onion and garlic 4 minutes until soft.',
      'Add barley and broth, bring to a boil, then simmer 25 minutes.',
      'Stir in broccoli and cook 8-10 minutes until tender.',
      'Lower heat, stir in milk and cheddar until melted and creamy.',
      'Season to taste and serve hot.',
    ],
    superAgeNote: 'Barley and broccoli supply beta-glucan and vegetable fiber, the fiber-rich carbohydrates the study links to healthier aging, even in a comforting cheesy soup.',
    nutrition: { cal: 450, protein: 18, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-black-bean-quinoa-taco-bowl-carrots',
    name: 'Black Bean & Quinoa Taco Bowl with Shredded Carrots',
    emoji: '🌮',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1.5 cups', item: 'cooked black beans' },
      { qty: '1.5 cups', item: 'shredded carrots' },
      { qty: '1 cup', item: 'shredded romaine or cabbage' },
      { qty: '1 tsp', item: 'chili powder' },
      { qty: '0.5 tsp', item: 'ground cumin' },
      { qty: '2 tbsp', item: 'lime juice' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '2 tbsp', item: 'chopped cilantro' },
    ],
    steps: [
      'Warm black beans in a pan with chili powder, cumin, and a splash of water.',
      'Whisk lime juice and olive oil into a quick dressing.',
      'Divide quinoa between bowls and top with spiced beans.',
      'Add shredded carrots and lettuce, drizzle with dressing, and scatter cilantro.',
    ],
    superAgeNote: 'Black beans and quinoa give this taco bowl a low carb-to-fiber ratio, the high-quality carbohydrate profile associated with healthier aging.',
    nutrition: { cal: 460, protein: 17, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-lentil-kale-buddha-bowl-millet',
    name: 'Lentil & Kale Buddha Bowl with Millet',
    emoji: '🥣',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked millet' },
      { qty: '1 cup', item: 'cooked brown lentils' },
      { qty: '3 cups', item: 'chopped kale' },
      { qty: '1 cup', item: 'shredded carrots' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Massage kale with 1 tbsp olive oil and a pinch of salt until softened.',
      'Whisk tahini, lemon juice, remaining oil, and 2-3 tbsp water into a dressing.',
      'Divide millet and lentils between bowls.',
      'Top with massaged kale and shredded carrots, then drizzle with tahini dressing.',
    ],
    superAgeNote: 'Millet, lentils, and kale layer whole-grain, legume, and leafy-green fiber, the carbohydrate quality the 30-year study links to healthier aging.',
    nutrition: { cal: 480, protein: 18, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chickpea-carrot-curry-barley',
    name: 'Chickpea & Carrot Curry over Barley',
    emoji: '🍛',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked pearl barley' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '3 medium', item: 'carrots, sliced' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'curry powder' },
      { qty: '1 cup', item: 'canned coconut milk' },
      { qty: '1 cup', item: 'crushed tomatoes' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat oil in a pan and cook onion, garlic, and carrots 6 minutes until softened.',
      'Stir in curry powder and cook 1 minute until fragrant.',
      'Add chickpeas, coconut milk, and crushed tomatoes. Simmer 15 minutes until carrots are tender.',
      'Season to taste and spoon over warm barley.',
    ],
    superAgeNote: 'Chickpeas and barley provide the legume and whole-grain fiber the study connects to healthier aging, while carrots add vegetable fiber.',
    nutrition: { cal: 520, protein: 17, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-spinach-chickpea-curry-quinoa',
    name: 'Spinach & Chickpea Curry over Quinoa',
    emoji: '🍛',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '4 cups', item: 'baby spinach' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'garam masala' },
      { qty: '1 cup', item: 'crushed tomatoes' },
      { qty: '0.5 cup', item: 'canned coconut milk' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat oil in a pan and cook onion and garlic 5 minutes until soft.',
      'Stir in garam masala, then add chickpeas, tomatoes, and coconut milk.',
      'Simmer 10 minutes until slightly thickened.',
      'Add spinach and cook 2-3 minutes until wilted.',
      'Serve over warm quinoa.',
    ],
    superAgeNote: 'Chickpeas, quinoa, and spinach together supply the fiber-rich carbohydrates the JAMA Network Open study links to healthier aging.',
    nutrition: { cal: 490, protein: 18, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-millet-black-bean-roasted-broccoli-salad',
    name: 'Millet, Black Bean & Roasted Broccoli Salad',
    emoji: '🥗',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked millet, cooled' },
      { qty: '1.5 cups', item: 'cooked black beans' },
      { qty: '3 cups', item: 'broccoli florets' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '2 tbsp', item: 'lime juice' },
      { qty: '0.5 tsp', item: 'ground cumin' },
      { qty: '2 tbsp', item: 'chopped cilantro' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss broccoli with 1 tbsp oil, cumin, salt, and pepper.',
      'Roast broccoli 18-20 minutes until crisp-tender and browned.',
      'In a bowl, combine millet and black beans.',
      'Whisk remaining oil with lime juice and toss through the millet and beans.',
      'Fold in roasted broccoli and cilantro, then serve warm or chilled.',
    ],
    superAgeNote: 'Millet and black beans plus roasted broccoli give this salad the low carb-to-fiber ratio the study associates with healthier aging.',
    nutrition: { cal: 470, protein: 17, fiber: 16 },
    airfryer: [
      'Air fry broccoli at 390F (199C) for 10-12 minutes, shaking halfway, until edges char.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-lentil-carrot-soup-barley',
    name: 'Lentil & Carrot Soup with Barley',
    emoji: '🍲',
    category: 'lunch',
    time: '45 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '0.75 cup', item: 'dried brown lentils, rinsed' },
      { qty: '0.33 cup', item: 'pearl barley, rinsed' },
      { qty: '3 medium', item: 'carrots, diced' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '5 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat oil in a pot and cook onion, carrots, and garlic 5 minutes until softened.',
      'Stir in cumin, then add lentils, barley, and broth. Bring to a boil.',
      'Reduce heat and simmer 30-35 minutes until lentils and barley are tender.',
      'Season with salt and pepper and serve hot.',
    ],
    superAgeNote: 'Lentils and barley together make this soup especially fiber-dense, matching the high-quality carbohydrate pattern linked to healthier aging.',
    nutrition: { cal: 430, protein: 19, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chickpea-shawarma-bowl-quinoa-greens',
    name: 'Chickpea Shawarma Bowl with Quinoa & Greens',
    emoji: '🥙',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '3 cups', item: 'baby greens or chopped kale' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1.5 tsp', item: 'shawarma spice blend' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss chickpeas with 1 tbsp oil, shawarma spice, salt, and pepper.',
      'Roast chickpeas 18-22 minutes until golden and slightly crisp.',
      'Whisk tahini, lemon juice, remaining oil, and 2-3 tbsp water into a sauce.',
      'Divide quinoa and greens between bowls and top with spiced chickpeas.',
      'Drizzle with tahini sauce and serve.',
    ],
    superAgeNote: 'Spiced chickpeas over quinoa and greens deliver the legume and whole-grain fiber the JAMA Network Open study links to healthier aging.',
    nutrition: { cal: 500, protein: 19, fiber: 15 },
    airfryer: [
      'Air fry seasoned chickpeas at 390F (199C) for 12-14 minutes, shaking halfway, until crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-kale-caesar-chickpeas-barley-croutons',
    name: 'Kale Caesar-Style Salad with Chickpeas & Barley Croutons',
    emoji: '🥗',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'high-protein'],
    ingredients: [
      { qty: '4 cups', item: 'chopped kale' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '1 cup', item: 'cooked pearl barley' },
      { qty: '3 tbsp', item: 'plain Greek yogurt' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '1 tsp', item: 'Dijon mustard' },
      { qty: '2 tbsp', item: 'grated Parmesan' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss cooked barley with 1 tbsp oil, salt, and pepper; spread on a tray.',
      'Roast barley 15-18 minutes, stirring once, until dried and crunchy like croutons.',
      'Massage kale with a little oil until softened.',
      'Whisk yogurt, lemon juice, mustard, Parmesan, remaining oil, salt, and pepper into a dressing.',
      'Toss kale and chickpeas with dressing, then top with barley croutons.',
    ],
    superAgeNote: 'Barley croutons and chickpeas replace refined bread with whole-grain and legume fiber, the higher-quality carbohydrates associated with healthier aging.',
    nutrition: { cal: 470, protein: 20, fiber: 14 },
    airfryer: [
      'Air fry oiled cooked barley at 380F (193C) for 10-12 minutes, shaking twice, until crunchy.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-black-bean-broccoli-stir-fry-quinoa',
    name: 'Black Bean & Broccoli Stir-Fry over Quinoa',
    emoji: '🥦',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1.5 cups', item: 'cooked black beans' },
      { qty: '3 cups', item: 'broccoli florets' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'grated fresh ginger' },
      { qty: '2 tbsp', item: 'low-sodium soy sauce' },
      { qty: '1 tsp', item: 'toasted sesame oil' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat olive oil in a wok or large pan over high heat.',
      'Add broccoli and stir-fry 4-5 minutes until bright green and crisp-tender.',
      'Add garlic and ginger, cook 1 minute, then stir in black beans.',
      'Pour in soy sauce and sesame oil, tossing 2 minutes to coat.',
      'Serve over warm quinoa.',
    ],
    superAgeNote: 'Black beans, broccoli, and quinoa keep the carb-to-fiber ratio low, reflecting the fiber-rich carbohydrate quality the study links to healthier aging.',
    nutrition: { cal: 450, protein: 18, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-lentil-spinach-carrot-dal-millet',
    name: 'Lentil, Spinach & Carrot Dal over Millet',
    emoji: '🍛',
    category: 'lunch',
    time: '40 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'dried red lentils, rinsed' },
      { qty: '1 cup', item: 'cooked millet' },
      { qty: '2 medium', item: 'carrots, diced' },
      { qty: '3 cups', item: 'baby spinach' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'curry powder' },
      { qty: '3.5 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat oil in a pot and cook onion, carrots, and garlic 5 minutes until softened.',
      'Stir in curry powder, then add lentils and broth. Bring to a boil.',
      'Simmer 18-22 minutes until lentils break down into a thick dal.',
      'Stir in spinach and cook 2-3 minutes until wilted.',
      'Serve the dal over warm millet.',
    ],
    superAgeNote: 'Red lentils and millet combine legume and whole-grain fiber, the high-quality carbohydrates the 30-year study links to healthier aging.',
    nutrition: { cal: 480, protein: 21, fiber: 17 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chickpea-broccoli-orange-tahini',
    name: 'Chickpea & Roasted Broccoli Bowl with Orange-Tahini Dressing',
    emoji: '🍊',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '3 cups', item: 'broccoli florets' },
      { qty: '1', item: 'orange, segmented' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '3 tbsp', item: 'fresh orange juice' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss broccoli and chickpeas with 1 tbsp oil, salt, and pepper.',
      'Roast 18-22 minutes until broccoli is crisp-tender and chickpeas are golden.',
      'Whisk tahini, orange juice, remaining oil, and a splash of water into a smooth dressing.',
      'Divide quinoa between bowls and top with broccoli, chickpeas, and orange segments.',
      'Drizzle with orange-tahini dressing and serve.',
    ],
    superAgeNote: 'Chickpeas, broccoli, and quinoa deliver fiber-rich carbs while orange adds fruit fiber and vitamin C, mirroring the star foods tied to healthier aging.',
    nutrition: { cal: 510, protein: 18, fiber: 16 },
    airfryer: [
      'Air fry chickpeas and broccoli at 390F (199C) for 12-14 minutes, shaking halfway, until crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-barley-black-bean-chili-kale',
    name: 'Barley & Black Bean Chili with Kale',
    emoji: '🌶️',
    category: 'lunch',
    time: '45 min',
    serves: 2,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '0.5 cup', item: 'pearl barley, rinsed' },
      { qty: '1.5 cups', item: 'cooked black beans' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 can (14 oz)', item: 'diced tomatoes' },
      { qty: '3 cups', item: 'chopped kale' },
      { qty: '1 tbsp', item: 'chili powder' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '3 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat oil in a pot and cook onion and garlic 5 minutes until soft.',
      'Stir in chili powder and cumin, then add barley, tomatoes, and broth.',
      'Bring to a boil, then simmer 25-30 minutes until barley is tender.',
      'Add black beans and kale; cook 7-8 minutes more until kale is tender.',
      'Season to taste and serve hot.',
    ],
    superAgeNote: 'Barley and black beans make this chili rich in whole-grain and legume fiber, the high-quality carbohydrates the study associates with healthier aging.',
    nutrition: { cal: 440, protein: 18, fiber: 17 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-quinoa-chickpea-carrot-salad-lemon',
    name: 'Quinoa, Chickpea & Carrot Salad with Lemon',
    emoji: '🥗',
    category: 'lunch',
    time: '20 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'cooked quinoa, cooled' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '1.5 cups', item: 'shredded carrots' },
      { qty: '0.5 cup', item: 'chopped parsley' },
      { qty: '3 tbsp', item: 'lemon juice' },
      { qty: '3 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'lemon zest' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'In a large bowl, combine quinoa, chickpeas, shredded carrots, and parsley.',
      'Whisk lemon juice, olive oil, lemon zest, salt, and pepper into a dressing.',
      'Pour dressing over the salad and toss well.',
      'Let sit 10 minutes, then serve chilled or at room temperature.',
    ],
    superAgeNote: 'Quinoa, chickpeas, and carrots give this quick salad the fiber-rich, minimally processed carbohydrates linked to healthier aging.',
    nutrition: { cal: 470, protein: 16, fiber: 14 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-lentil-broccoli-fried-rice-millet',
    name: 'Lentil & Broccoli Fried "Rice" with Millet',
    emoji: '🍚',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'cooked millet, cooled' },
      { qty: '1 cup', item: 'cooked brown lentils' },
      { qty: '2 cups', item: 'broccoli florets, finely chopped' },
      { qty: '1 cup', item: 'shredded carrots' },
      { qty: '2', item: 'eggs, beaten' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '2 tbsp', item: 'low-sodium soy sauce' },
      { qty: '1 tbsp', item: 'toasted sesame oil' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat olive oil in a large pan over high heat and stir-fry broccoli and carrots 4 minutes.',
      'Push vegetables aside, pour beaten eggs into the pan, and scramble until just set.',
      'Add garlic, millet, and lentils, stir-frying 3-4 minutes until heated through.',
      'Pour in soy sauce and sesame oil, toss to coat, and serve hot.',
    ],
    superAgeNote: 'Millet stands in for white rice while lentils and broccoli boost fiber, reflecting the higher-quality carbohydrates the study ties to healthier aging.',
    nutrition: { cal: 460, protein: 20, fiber: 14 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-black-bean-spinach-quesadilla-quinoa',
    name: 'Black Bean & Spinach Quesadilla with Quinoa Side',
    emoji: '🫓',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'high-protein'],
    ingredients: [
      { qty: '2 large', item: 'whole-wheat tortillas' },
      { qty: '1.5 cups', item: 'cooked black beans, lightly mashed' },
      { qty: '2 cups', item: 'baby spinach' },
      { qty: '0.75 cup', item: 'shredded cheese' },
      { qty: '0.5 tsp', item: 'ground cumin' },
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1 tbsp', item: 'lime juice' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Mash black beans with cumin and a pinch of salt.',
      'Spread beans over half of each tortilla, then top with spinach and cheese and fold over.',
      'Cook quesadillas in a dry or lightly oiled pan 2-3 minutes per side until golden.',
      'Toss quinoa with lime juice and olive oil for a simple side.',
      'Slice quesadillas into wedges and serve with the quinoa.',
    ],
    superAgeNote: 'Black beans, whole-wheat tortillas, and a quinoa side stack legume and whole-grain fiber, the carbohydrate quality linked to healthier aging.',
    nutrition: { cal: 520, protein: 22, fiber: 15 },
    airfryer: [
      'Air fry each folded quesadilla at 375F (190C) for 6-8 minutes, flipping once, until crisp and golden.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chickpea-carrot-barley-soup',
    name: 'Chickpea, Carrot & Barley Soup',
    emoji: '🍲',
    category: 'lunch',
    time: '45 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '0.5 cup', item: 'pearl barley, rinsed' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '3 medium', item: 'carrots, diced' },
      { qty: '1 medium', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '5 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'dried thyme' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Heat oil in a pot and cook onion, carrots, and garlic 5 minutes until softened.',
      'Stir in thyme and barley, then add broth. Bring to a boil.',
      'Reduce heat and simmer 25-30 minutes until barley is tender.',
      'Add chickpeas and warm through 5 minutes.',
      'Season with salt and pepper and serve hot.',
    ],
    superAgeNote: 'Barley and chickpeas make this soup a fiber-forward bowl of whole-grain and legume carbohydrates, the pattern the study links to healthier aging.',
    nutrition: { cal: 420, protein: 17, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-lentil-kale-grain-bowl-roasted-carrots',
    name: 'Lentil & Kale Grain Bowl with Roasted Carrots',
    emoji: '🥣',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1 cup', item: 'cooked brown lentils' },
      { qty: '3 medium', item: 'carrots, cut into sticks' },
      { qty: '3 cups', item: 'chopped kale' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss carrot sticks with 1 tbsp oil, cumin, salt, and pepper.',
      'Roast carrots 20-25 minutes until tender and caramelized.',
      'Massage kale with a little oil until softened.',
      'Divide quinoa and lentils between bowls, then top with kale and roasted carrots.',
      'Whisk remaining oil with lemon juice, drizzle over the bowls, and serve.',
    ],
    superAgeNote: 'Lentils, quinoa, kale, and carrots layer legume, whole-grain, and vegetable fiber, the star carbohydrates the study links to healthier aging.',
    nutrition: { cal: 470, protein: 18, fiber: 16 },
    airfryer: [
      'Air fry carrot sticks at 380F (193C) for 14-16 minutes, shaking once, until caramelized.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-millet-chickpea-power-bowl-broccoli',
    name: 'Millet & Chickpea Power Bowl with Broccoli',
    emoji: '💪',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked millet' },
      { qty: '1.5 cups', item: 'cooked chickpeas' },
      { qty: '3 cups', item: 'broccoli florets' },
      { qty: '1 cup', item: 'shredded carrots' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss broccoli and chickpeas with 1 tbsp oil, salt, and pepper.',
      'Roast 18-22 minutes until broccoli is crisp-tender and chickpeas are golden.',
      'Whisk tahini, lemon juice, remaining oil, and 2-3 tbsp water into a dressing.',
      'Divide millet between bowls and top with roasted broccoli, chickpeas, and carrots.',
      'Drizzle with tahini dressing and serve.',
    ],
    superAgeNote: 'Millet and chickpeas anchor this power bowl in whole-grain and legume fiber, the high-quality carbohydrates linked to healthier aging.',
    nutrition: { cal: 500, protein: 19, fiber: 16 },
    airfryer: [
      'Air fry chickpeas and broccoli at 390F (199C) for 12-14 minutes, shaking halfway, until crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-black-bean-barley-salad-spinach-orange',
    name: 'Black Bean & Barley Salad with Spinach & Orange Vinaigrette',
    emoji: '🍊',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked pearl barley, cooled' },
      { qty: '1.5 cups', item: 'cooked black beans' },
      { qty: '3 cups', item: 'baby spinach' },
      { qty: '1', item: 'orange, segmented' },
      { qty: '3 tbsp', item: 'fresh orange juice' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tbsp', item: 'red wine vinegar' },
      { qty: '1 pinch', item: 'salt and pepper' },
    ],
    steps: [
      'In a large bowl, combine barley, black beans, spinach, and orange segments.',
      'Whisk orange juice, olive oil, vinegar, salt, and pepper into a vinaigrette.',
      'Pour vinaigrette over the salad and toss gently to combine.',
      'Serve right away or chill briefly.',
    ],
    superAgeNote: 'Barley and black beans plus orange and spinach combine whole-grain, legume, fruit, and vegetable fiber, the star foods the study links to healthier aging.',
    nutrition: { cal: 450, protein: 16, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
];

(function () {
  if (typeof KANDY_RECIPES !== 'undefined') KANDY_RECIPES.push(...SUPERAGE_LUNCH);
  SUPERAGE_LUNCH.forEach(function (r) {
    if (r.airfryer && typeof AIRFRYER !== 'undefined') AIRFRYER[r.id] = r.airfryer;
    if (r.nutrition && typeof RECIPE_NUTRITION !== 'undefined') RECIPE_NUTRITION[r.id] = r.nutrition;
  });
})();
