// SuperAge Lunch Recipes
// Real, everyday cookbook-style lunches built around high-quality, fiber-rich
// "longevity carbs" (whole grains, fruits, vegetables, legumes) highlighted in a
// SuperAge article on a 30-year JAMA Network Open study linking fiber-rich,
// minimally processed carbohydrates to healthier aging. Every dish stars at
// least one hero carb; lean proteins added where they make a normal lunch.

const SUPERAGE_LUNCH = [
  {
    id: 'sa-lu-hearty-lentil-vegetable-soup',
    name: 'Hearty Lentil and Vegetable Soup',
    emoji: '🍲',
    category: 'lunch',
    time: '40 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 small', item: 'yellow onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '2', item: 'carrots, diced' },
      { qty: '1 stalk', item: 'celery, diced' },
      { qty: '3/4 cup', item: 'dried brown or green lentils, rinsed' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1/2 tsp', item: 'smoked paprika' },
      { qty: '1', item: 'bay leaf' },
      { qty: '1 can (14 oz)', item: 'diced tomatoes' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '2 cups', item: 'chopped kale, stems removed' },
      { qty: '1 tbsp', item: 'red wine vinegar' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Warm olive oil in a pot over medium heat. Cook onion, carrots, and celery 6-7 minutes until softened.',
      'Add garlic, cumin, and smoked paprika; stir 1 minute until fragrant.',
      'Add lentils, bay leaf, diced tomatoes, and broth. Bring to a boil, then simmer partially covered 25 minutes until lentils are tender.',
      'Stir in kale and cook 5 minutes until wilted. Discard the bay leaf.',
      'Finish with red wine vinegar, season with salt and pepper, and serve.',
    ],
    superAgeNote: 'Lentils are the fiber-rich, minimally processed legume the JAMA Network Open study links to healthier aging, and the kale and carrots keep this bowl well under a 10:1 carb-to-fiber ratio.',
    nutrition: { cal: 380, protein: 20, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chicken-kale-chickpea-soup',
    name: 'Chicken, Kale and Chickpea Soup',
    emoji: '🍲',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 small', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1', item: 'carrot, diced' },
      { qty: '1 tsp', item: 'dried oregano' },
      { qty: '1/4 tsp', item: 'red pepper flakes' },
      { qty: '4 cups', item: 'low-sodium chicken broth' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1', item: 'cooked chicken breast, shredded (about 1.5 cups)' },
      { qty: '3 cups', item: 'chopped kale' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '2 tbsp', item: 'grated Parmesan' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Heat olive oil in a pot over medium heat and cook onion and carrot 5 minutes until soft.',
      'Add garlic, oregano, and red pepper flakes; stir 1 minute.',
      'Pour in broth and chickpeas, bring to a simmer, and cook 10 minutes to build flavor.',
      'Add shredded chicken and kale; simmer 5 minutes until kale is tender and chicken is heated through.',
      'Stir in lemon juice, season with salt and pepper, and top each bowl with Parmesan.',
    ],
    superAgeNote: 'Chickpeas and kale supply the high-quality fiber tied to healthier aging in the JAMA Network Open study, while the chicken makes it a satisfying everyday lunch.',
    nutrition: { cal: 430, protein: 38, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-curried-carrot-chickpea-soup',
    name: 'Curried Carrot and Chickpea Soup',
    emoji: '🥕',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 tbsp', item: 'coconut or olive oil' },
      { qty: '1 small', item: 'onion, chopped' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tsp', item: 'grated fresh ginger' },
      { qty: '1 lb', item: 'carrots, sliced' },
      { qty: '1 tbsp', item: 'mild curry powder' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained (reserve 1/2 cup)' },
      { qty: '3 cups', item: 'vegetable broth' },
      { qty: '1/2 cup', item: 'light coconut milk' },
      { qty: '1 tbsp', item: 'lime juice' },
      { qty: '2 tbsp', item: 'chopped cilantro' },
      { qty: '1 pinch', item: 'salt' },
    ],
    steps: [
      'Heat oil in a pot and cook onion 4 minutes. Add garlic and ginger; cook 1 minute.',
      'Stir in carrots and curry powder and cook 2 minutes to toast the spices.',
      'Add most of the chickpeas and the broth. Simmer 18-20 minutes until carrots are very soft.',
      'Blend smooth with an immersion blender, then stir in coconut milk and lime juice.',
      'Season with salt, ladle into bowls, and top with the reserved chickpeas and cilantro.',
    ],
    superAgeNote: 'Carrots and chickpeas are exactly the vegetable and legume carbs the JAMA Network Open study associates with healthier aging, delivering plenty of fiber per serving.',
    nutrition: { cal: 400, protein: 15, fiber: 13 },
    added: '2026-07-27',
    isCustom: true,
    airfryer: [
      'For a roasted-carrot depth, air fry the sliced carrots at 380F (193C) for 14 minutes before adding them to the pot with the broth.',
    ],
  },
  {
    id: 'sa-lu-barley-minestrone',
    name: 'Barley Minestrone',
    emoji: '🍲',
    category: 'lunch',
    time: '45 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan'],
    ingredients: [
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 small', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1', item: 'carrot, diced' },
      { qty: '1 stalk', item: 'celery, diced' },
      { qty: '1/2 cup', item: 'pearl barley, rinsed' },
      { qty: '1 tsp', item: 'dried Italian herbs' },
      { qty: '1 can (14 oz)', item: 'diced tomatoes' },
      { qty: '1 can (15 oz)', item: 'cannellini beans, drained' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '1 cup', item: 'chopped green beans or zucchini' },
      { qty: '2 cups', item: 'baby spinach' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Heat olive oil and cook onion, carrot, and celery 6 minutes until softened.',
      'Add garlic and Italian herbs; stir 1 minute.',
      'Add barley, tomatoes, beans, and broth. Bring to a boil, then simmer 25 minutes until barley is tender.',
      'Add green beans and cook 5 minutes, then stir in spinach until wilted.',
      'Season with salt and pepper and serve, adding a splash of broth if it thickens too much.',
    ],
    superAgeNote: 'Whole-grain barley plus cannellini beans give this minestrone the high-fiber, high-quality carbohydrates the JAMA Network Open study links to healthier aging.',
    nutrition: { cal: 420, protein: 17, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-smoky-black-bean-soup',
    name: 'Smoky Black Bean Soup',
    emoji: '🫘',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 small', item: 'onion, diced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '2 cans (15 oz each)', item: 'black beans, drained (reserve some)' },
      { qty: '2.5 cups', item: 'vegetable broth' },
      { qty: '1', item: 'chipotle in adobo, minced (optional)' },
      { qty: '1 tbsp', item: 'lime juice' },
      { qty: '1/4 cup', item: 'chopped cilantro' },
      { qty: '2 tbsp', item: 'diced avocado, for topping' },
      { qty: '1 pinch', item: 'salt' },
    ],
    steps: [
      'Heat oil and cook onion 4 minutes; add garlic, cumin, and paprika and stir 1 minute.',
      'Add most of the black beans, the broth, and chipotle. Simmer 12 minutes.',
      'Blend about two-thirds of the soup smooth, then return it to the pot with the whole beans for texture.',
      'Stir in lime juice and salt; warm through.',
      'Ladle into bowls and top with cilantro, avocado, and the reserved whole beans.',
    ],
    superAgeNote: 'Black beans are a standout high-fiber legume from the JAMA Network Open study, keeping the carb-to-fiber ratio low while making a filling, protein-rich lunch.',
    nutrition: { cal: 440, protein: 22, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-broccoli-cheddar-soup',
    name: 'Lighter Broccoli Cheddar Soup',
    emoji: '🥦',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1 tbsp', item: 'butter or olive oil' },
      { qty: '1 small', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1', item: 'carrot, grated' },
      { qty: '1', item: 'russet potato, peeled and diced' },
      { qty: '4 cups', item: 'broccoli florets' },
      { qty: '3 cups', item: 'vegetable broth' },
      { qty: '1/2 cup', item: 'milk' },
      { qty: '3/4 cup', item: 'shredded sharp cheddar' },
      { qty: '1/2 tsp', item: 'Dijon mustard' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Melt butter and cook onion and carrot 5 minutes. Add garlic and cook 1 minute.',
      'Add potato and broth; simmer 10 minutes until the potato is nearly tender.',
      'Add broccoli and simmer 6-8 minutes until soft.',
      'Blend about half the soup for a creamy body while leaving plenty of broccoli whole.',
      'Off the heat, stir in milk, cheddar, and Dijon until melted. Season with salt and pepper.',
    ],
    superAgeNote: 'Broccoli and potato deliver the vegetable fiber the JAMA Network Open study ties to healthier aging; blending a potato instead of using flour keeps it naturally gluten-free.',
    nutrition: { cal: 400, protein: 20, fiber: 10 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-turkey-white-bean-chili',
    name: 'Turkey and White Bean Chili',
    emoji: '🌶️',
    category: 'lunch',
    time: '40 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 small', item: 'onion, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '8 oz', item: 'ground turkey' },
      { qty: '1', item: 'carrot, diced' },
      { qty: '1 tbsp', item: 'chili powder' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'dried oregano' },
      { qty: '2 cans (15 oz each)', item: 'white beans, drained' },
      { qty: '1 can (4 oz)', item: 'diced green chiles' },
      { qty: '2.5 cups', item: 'chicken broth' },
      { qty: '2 cups', item: 'chopped spinach' },
      { qty: '2 tbsp', item: 'chopped cilantro' },
      { qty: '1 pinch', item: 'salt' },
    ],
    steps: [
      'Heat oil and brown the turkey with the onion and carrot, 6-7 minutes, breaking it up.',
      'Add garlic, chili powder, cumin, and oregano; stir 1 minute until fragrant.',
      'Add white beans, green chiles, and broth. Simmer 20 minutes, mashing some beans to thicken.',
      'Stir in spinach and cook 3 minutes until wilted. Season with salt.',
      'Top with cilantro and serve.',
    ],
    superAgeNote: 'White beans provide the fiber-rich legume carbs the JAMA Network Open study links to healthier aging, and lean turkey makes this a hearty, high-protein lunch.',
    nutrition: { cal: 470, protein: 40, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-mediterranean-chickpea-salad',
    name: 'Mediterranean Chickpea Salad with Feta',
    emoji: '🥗',
    category: 'lunch',
    time: '15 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1', item: 'cucumber, diced' },
      { qty: '1 cup', item: 'cherry tomatoes, halved' },
      { qty: '1/4', item: 'red onion, finely diced' },
      { qty: '1/3 cup', item: 'crumbled feta' },
      { qty: '1/4 cup', item: 'chopped fresh parsley' },
      { qty: '2 tbsp', item: 'chopped kalamata olives' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tbsp', item: 'red wine vinegar' },
      { qty: '1/2 tsp', item: 'dried oregano' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'In a large bowl combine chickpeas, cucumber, tomatoes, red onion, olives, and parsley.',
      'Whisk olive oil, red wine vinegar, oregano, salt, and pepper into a dressing.',
      'Pour the dressing over the salad and toss to coat.',
      'Fold in the feta, taste, and adjust seasoning.',
      'Serve right away or chill 15 minutes to let the flavors meld.',
    ],
    superAgeNote: 'Chickpeas anchor this no-cook salad with the legume fiber the JAMA Network Open study associates with healthier aging, alongside fresh vegetables.',
    nutrition: { cal: 420, protein: 16, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-kale-caesar-chicken-barley-croutons',
    name: 'Kale Caesar with Chicken and Barley Croutons',
    emoji: '🥗',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked pearl barley' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1/4 tsp', item: 'garlic powder' },
      { qty: '1 bunch', item: 'lacinato kale, stemmed and thinly sliced' },
      { qty: '1', item: 'cooked chicken breast, sliced' },
      { qty: '3 tbsp', item: 'plain Greek yogurt' },
      { qty: '2 tbsp', item: 'grated Parmesan, plus more to finish' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '1 tsp', item: 'Dijon mustard' },
      { qty: '1', item: 'anchovy fillet, minced (or 1/2 tsp Worcestershire)' },
      { qty: '1 clove', item: 'garlic, grated' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss cooked barley with olive oil and garlic powder and spread on a sheet pan.',
      'Bake 18-20 minutes, stirring once, until the barley is crisp and golden like croutons.',
      'Whisk yogurt, Parmesan, lemon juice, Dijon, anchovy, and grated garlic into a creamy dressing.',
      'Massage the sliced kale with a pinch of salt for 1 minute, then toss with the dressing.',
      'Top with sliced chicken, the crunchy barley croutons, and extra Parmesan.',
    ],
    superAgeNote: 'Whole-grain barley croutons and massaged kale deliver the fiber-rich carbs the JAMA Network Open study links to healthier aging, upgrading a classic Caesar.',
    nutrition: { cal: 460, protein: 40, fiber: 11 },
    added: '2026-07-27',
    isCustom: true,
    airfryer: [
      'Air fry the oiled barley at 390F (199C) for 10-12 minutes, shaking twice, until crisp and golden.',
    ],
  },
  {
    id: 'sa-lu-tuna-chickpea-salad',
    name: 'Tuna and Chickpea Salad',
    emoji: '🐟',
    category: 'lunch',
    time: '15 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 can (5 oz)', item: 'tuna in water, drained' },
      { qty: '1 stalk', item: 'celery, diced' },
      { qty: '1/4', item: 'red onion, finely diced' },
      { qty: '2 cups', item: 'arugula or baby spinach' },
      { qty: '2 tbsp', item: 'chopped fresh parsley' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1.5 tbsp', item: 'lemon juice' },
      { qty: '1 tsp', item: 'Dijon mustard' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'In a bowl, lightly mash about a third of the chickpeas to help the salad hold together.',
      'Add the remaining chickpeas, tuna, celery, red onion, and parsley.',
      'Whisk olive oil, lemon juice, Dijon, salt, and pepper, then fold into the salad.',
      'Pile onto a bed of arugula and serve as-is or in lettuce cups.',
    ],
    superAgeNote: 'Chickpeas bring the high-quality legume fiber tied to healthier aging in the JAMA Network Open study, while canned tuna adds lean protein for a fast lunch.',
    nutrition: { cal: 410, protein: 32, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-quinoa-tabbouleh',
    name: 'Quinoa Tabbouleh',
    emoji: '🥗',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa, cooled' },
      { qty: '1.5 cups', item: 'finely chopped flat-leaf parsley' },
      { qty: '1/4 cup', item: 'chopped fresh mint' },
      { qty: '1 cup', item: 'cherry tomatoes, finely diced' },
      { qty: '1', item: 'Persian cucumber, diced' },
      { qty: '2', item: 'green onions, sliced' },
      { qty: '3 tbsp', item: 'olive oil' },
      { qty: '3 tbsp', item: 'lemon juice' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Make sure the quinoa is fully cooled so the salad stays fresh and fluffy.',
      'Combine quinoa, parsley, mint, tomatoes, cucumber, and green onions in a bowl.',
      'Whisk olive oil, lemon juice, salt, and pepper.',
      'Pour over the salad and toss well, letting the herbs coat everything.',
      'Rest 10 minutes before serving so the quinoa soaks up the lemon dressing.',
    ],
    superAgeNote: 'Quinoa is a whole-grain source of the fiber-rich carbohydrates the JAMA Network Open study associates with healthier aging, carried by a mountain of fresh herbs.',
    nutrition: { cal: 340, protein: 9, fiber: 10 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-spinach-berry-quinoa-salad',
    name: 'Spinach, Berry and Quinoa Salad',
    emoji: '🫐',
    category: 'lunch',
    time: '20 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '4 cups', item: 'baby spinach' },
      { qty: '1 cup', item: 'cooked quinoa, cooled' },
      { qty: '1 cup', item: 'mixed berries (strawberries, blueberries)' },
      { qty: '1/4 cup', item: 'toasted walnuts, chopped' },
      { qty: '2 tbsp', item: 'pumpkin seeds' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tbsp', item: 'balsamic vinegar' },
      { qty: '1 tsp', item: 'maple syrup' },
      { qty: '1 tsp', item: 'Dijon mustard' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Whisk olive oil, balsamic vinegar, maple syrup, Dijon, salt, and pepper into a vinaigrette.',
      'In a large bowl, toss the spinach and cooled quinoa with most of the dressing.',
      'Add the berries and toss gently so they stay intact.',
      'Scatter walnuts and pumpkin seeds over the top and drizzle with the remaining dressing.',
      'Serve immediately while the greens are crisp.',
    ],
    superAgeNote: 'Berries and whole-grain quinoa together supply the fruit and whole-grain fiber the JAMA Network Open study links to healthier aging, all at a low carb-to-fiber ratio.',
    nutrition: { cal: 390, protein: 11, fiber: 11 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-kale-apple-crunch-salad',
    name: 'Kale and Apple Crunch Salad with Quinoa',
    emoji: '🍏',
    category: 'lunch',
    time: '20 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 bunch', item: 'kale, stemmed and thinly sliced' },
      { qty: '1 cup', item: 'cooked quinoa, cooled' },
      { qty: '1', item: 'crisp apple, thinly sliced' },
      { qty: '1/4 cup', item: 'dried cranberries' },
      { qty: '1/4 cup', item: 'toasted almonds, sliced' },
      { qty: '3 tbsp', item: 'olive oil' },
      { qty: '2 tbsp', item: 'apple cider vinegar' },
      { qty: '1 tsp', item: 'maple syrup' },
      { qty: '1 tsp', item: 'Dijon mustard' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Whisk olive oil, cider vinegar, maple syrup, Dijon, salt, and pepper into a dressing.',
      'Massage the sliced kale with a couple tablespoons of the dressing for 1-2 minutes until softened.',
      'Add the cooled quinoa and toss to combine.',
      'Fold in the apple slices and dried cranberries with the rest of the dressing.',
      'Top with toasted almonds for crunch and serve.',
    ],
    superAgeNote: 'Kale, apple, and quinoa combine leafy-green, fruit, and whole-grain fiber, the exact high-quality carbs the JAMA Network Open study ties to healthier aging.',
    nutrition: { cal: 420, protein: 10, fiber: 11 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-salmon-white-bean-salad',
    name: 'Salmon and White Bean Salad',
    emoji: '🐟',
    category: 'lunch',
    time: '15 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 can (15 oz)', item: 'cannellini beans, drained and rinsed' },
      { qty: '1 can (5 oz)', item: 'wild salmon, drained and flaked' },
      { qty: '1 cup', item: 'cherry tomatoes, halved' },
      { qty: '2 cups', item: 'baby arugula' },
      { qty: '1/4', item: 'red onion, thinly sliced' },
      { qty: '2 tbsp', item: 'chopped fresh dill' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1.5 tbsp', item: 'lemon juice' },
      { qty: '1 tsp', item: 'capers, drained' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'In a bowl combine white beans, tomatoes, red onion, capers, and dill.',
      'Whisk olive oil, lemon juice, salt, and pepper, then toss with the bean mixture.',
      'Gently fold in the flaked salmon so it stays in nice pieces.',
      'Serve over the arugula, or pile it into a bowl with the greens folded through.',
    ],
    superAgeNote: 'Cannellini beans deliver the legume fiber the JAMA Network Open study links to healthier aging, paired with omega-3-rich canned salmon for an easy protein boost.',
    nutrition: { cal: 430, protein: 33, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-chickpea-smash-sandwich',
    name: 'Chickpea Smash Salad Sandwich',
    emoji: '🥪',
    category: 'lunch',
    time: '15 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian'],
    ingredients: [
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '2 tbsp', item: 'plain Greek yogurt' },
      { qty: '1 tbsp', item: 'mayonnaise' },
      { qty: '1 stalk', item: 'celery, finely diced' },
      { qty: '2 tbsp', item: 'finely diced red onion' },
      { qty: '1 tbsp', item: 'chopped dill pickle' },
      { qty: '1 tsp', item: 'Dijon mustard' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '4 slices', item: 'whole-grain bread' },
      { qty: '2 leaves', item: 'lettuce' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Put the chickpeas in a bowl and mash with a fork, leaving some texture.',
      'Stir in yogurt, mayonnaise, celery, red onion, pickle, Dijon, and lemon juice.',
      'Season with salt and pepper and taste to adjust.',
      'Pile the chickpea salad onto two slices of bread, add lettuce, and close the sandwiches.',
      'Cut in half and serve.',
    ],
    superAgeNote: 'Mashed chickpeas on whole-grain bread stack legume and whole-grain fiber, the high-quality carbs the JAMA Network Open study associates with healthier aging.',
    nutrition: { cal: 400, protein: 18, fiber: 13 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-lentil-sloppy-joes',
    name: 'Lentil Sloppy Joes',
    emoji: '🥪',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan'],
    ingredients: [
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 small', item: 'onion, finely diced' },
      { qty: '1/2', item: 'green bell pepper, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1.5 cups', item: 'cooked brown lentils' },
      { qty: '1 cup', item: 'tomato sauce' },
      { qty: '1 tbsp', item: 'tomato paste' },
      { qty: '1 tbsp', item: 'maple syrup' },
      { qty: '1 tbsp', item: 'Worcestershire (or vegan Worcestershire)' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 tsp', item: 'chili powder' },
      { qty: '2', item: 'whole-grain buns, toasted' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Heat oil and cook onion and bell pepper 5 minutes until soft. Add garlic and cook 1 minute.',
      'Stir in smoked paprika and chili powder for 30 seconds.',
      'Add lentils, tomato sauce, tomato paste, maple syrup, and Worcestershire.',
      'Simmer 8-10 minutes until thick and saucy; season with salt and pepper.',
      'Spoon generously onto toasted buns and serve with a fork nearby.',
    ],
    superAgeNote: 'Lentils stand in for the meat here, providing the fiber-rich legume carbohydrates the JAMA Network Open study links to healthier aging in a familiar comfort-food format.',
    nutrition: { cal: 440, protein: 19, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-black-bean-quesadillas',
    name: 'Black Bean and Cheddar Quesadillas',
    emoji: '🌮',
    category: 'lunch',
    time: '20 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian'],
    ingredients: [
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1/2', item: 'onion, diced' },
      { qty: '1/2', item: 'red bell pepper, diced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1/2 tsp', item: 'chili powder' },
      { qty: '4', item: 'whole-grain or corn tortillas' },
      { qty: '1 cup', item: 'shredded cheddar or Monterey Jack' },
      { qty: '2 tbsp', item: 'chopped cilantro' },
      { qty: '1 pinch', item: 'salt' },
      { qty: '2 tbsp', item: 'salsa, for serving' },
    ],
    steps: [
      'Heat oil and cook onion and bell pepper 4 minutes. Add garlic, cumin, and chili powder; cook 1 minute.',
      'Add black beans with a splash of water and mash roughly into a chunky filling; season with salt and cilantro.',
      'Spread the bean filling over two tortillas, top with cheese, and close with the remaining tortillas.',
      'Toast in a dry skillet over medium heat 2-3 minutes per side until golden and the cheese melts.',
      'Cut into wedges and serve with salsa.',
    ],
    superAgeNote: 'Black beans give these quesadillas the legume fiber the JAMA Network Open study ties to healthier aging, keeping a favorite handheld lunch high-quality.',
    nutrition: { cal: 470, protein: 21, fiber: 14 },
    added: '2026-07-27',
    isCustom: true,
    airfryer: [
      'Air fry each assembled quesadilla at 360F (182C) for 6-8 minutes, flipping halfway, until crisp and the cheese is melted.',
    ],
  },
  {
    id: 'sa-lu-southwest-stuffed-sweet-potatoes',
    name: 'Southwest Stuffed Sweet Potatoes',
    emoji: '🍠',
    category: 'lunch',
    time: '45 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '2 medium', item: 'sweet potatoes' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '1 cup', item: 'corn kernels' },
      { qty: '1/2', item: 'red onion, diced' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1/2 tsp', item: 'smoked paprika' },
      { qty: '1', item: 'lime, juiced' },
      { qty: '1', item: 'avocado, sliced' },
      { qty: '1/4 cup', item: 'chopped cilantro' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Pierce the sweet potatoes and roast 40-45 minutes until very tender.',
      'Meanwhile, warm olive oil and saute red onion 3 minutes. Add black beans, corn, cumin, and paprika; cook 5 minutes.',
      'Stir lime juice into the bean mixture and season with salt and pepper.',
      'Split the roasted sweet potatoes lengthwise and fluff the insides with a fork.',
      'Pile in the black bean and corn filling, then top with avocado and cilantro.',
    ],
    superAgeNote: 'Fiber-rich sweet potato and black beans together are prime high-quality vegetable and legume carbs the JAMA Network Open study associates with healthier aging.',
    nutrition: { cal: 460, protein: 15, fiber: 17 },
    added: '2026-07-27',
    isCustom: true,
    airfryer: [
      'Air fry whole pierced sweet potatoes at 380F (193C) for 35-40 minutes, turning once, until a knife slides through easily.',
    ],
  },
  {
    id: 'sa-lu-chicken-black-bean-burrito-bowl',
    name: 'Chicken and Black Bean Burrito Bowl',
    emoji: '🌯',
    category: 'lunch',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'cooked brown rice or quinoa' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '2', item: 'chicken thighs, diced' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'chili powder' },
      { qty: '1 clove', item: 'garlic, minced' },
      { qty: '1 cup', item: 'shredded romaine' },
      { qty: '1 cup', item: 'cherry tomatoes, halved' },
      { qty: '1', item: 'avocado, sliced' },
      { qty: '1', item: 'lime, cut in wedges' },
      { qty: '1/4 cup', item: 'chopped cilantro' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Toss diced chicken with cumin, chili powder, salt, and pepper. Sear in olive oil 6-7 minutes until cooked through.',
      'Add garlic and the black beans to the pan and warm 3 minutes, stirring.',
      'Divide the quinoa between two bowls as a base.',
      'Top with the chicken-and-bean mixture, romaine, tomatoes, and avocado.',
      'Finish with cilantro and a squeeze of lime.',
    ],
    superAgeNote: 'Black beans plus a whole-grain base deliver the fiber-rich carbs the JAMA Network Open study links to healthier aging, while the chicken keeps this a hearty, high-protein bowl.',
    nutrition: { cal: 520, protein: 38, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
    airfryer: [
      'Air fry the seasoned diced chicken at 400F (204C) for 10-12 minutes, shaking halfway, until 165F (74C) inside.',
    ],
  },
  {
    id: 'sa-lu-warm-barley-roasted-veg-salad',
    name: 'Warm Barley Salad with Roasted Vegetables',
    emoji: '🥗',
    category: 'lunch',
    time: '40 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan'],
    ingredients: [
      { qty: '1 cup', item: 'cooked pearl barley, warm' },
      { qty: '2 cups', item: 'broccoli florets' },
      { qty: '1', item: 'red bell pepper, chopped' },
      { qty: '1', item: 'red onion, cut in wedges' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'dried thyme' },
      { qty: '2 cups', item: 'baby arugula' },
      { qty: '2 tbsp', item: 'toasted pine nuts or almonds' },
      { qty: '1 tbsp', item: 'balsamic vinegar' },
      { qty: '1 tsp', item: 'Dijon mustard' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Heat oven to 425F (220C). Toss broccoli, bell pepper, and red onion with 1 tbsp olive oil, thyme, salt, and pepper.',
      'Roast 22-25 minutes until caramelized at the edges.',
      'Whisk the remaining olive oil with balsamic vinegar and Dijon into a dressing.',
      'Toss the warm barley with the roasted vegetables and dressing.',
      'Fold in the arugula until it just wilts, then top with toasted nuts.',
    ],
    superAgeNote: 'Whole-grain barley with roasted broccoli and peppers layers whole-grain and vegetable fiber, the high-quality carbs the JAMA Network Open study ties to healthier aging.',
    nutrition: { cal: 410, protein: 12, fiber: 13 },
    added: '2026-07-27',
    isCustom: true,
    airfryer: [
      'Air fry the oiled vegetables at 390F (199C) for 14-16 minutes, shaking twice, until browned and tender.',
    ],
  },
  {
    id: 'sa-lu-chana-masala',
    name: 'Chana Masala (Chickpea Curry)',
    emoji: '🍛',
    category: 'lunch',
    time: '35 min',
    serves: 2,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 tbsp', item: 'oil' },
      { qty: '1', item: 'onion, finely chopped' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'grated fresh ginger' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'ground coriander' },
      { qty: '1/2 tsp', item: 'turmeric' },
      { qty: '1/2 tsp', item: 'garam masala' },
      { qty: '1 can (14 oz)', item: 'crushed tomatoes' },
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained' },
      { qty: '2 cups', item: 'chopped spinach' },
      { qty: '2 tbsp', item: 'chopped cilantro' },
      { qty: '1 pinch', item: 'salt' },
    ],
    steps: [
      'Heat oil and cook onion 6-7 minutes until deep golden. Add garlic and ginger; cook 1 minute.',
      'Stir in cumin, coriander, turmeric, and garam masala for 30 seconds until fragrant.',
      'Add crushed tomatoes and simmer 5 minutes until slightly thickened.',
      'Add chickpeas with a splash of water and simmer 12 minutes, mashing a few to thicken the sauce.',
      'Stir in spinach until wilted, season with salt, and finish with cilantro.',
    ],
    superAgeNote: 'Chickpeas are a high-fiber legume the JAMA Network Open study associates with healthier aging, and this Indian classic makes them a deeply flavorful, plant-forward lunch.',
    nutrition: { cal: 450, protein: 20, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-ginger-broccoli-chickpea-stir-fry',
    name: 'Ginger Broccoli and Chickpea Stir-Fry',
    emoji: '🥦',
    category: 'lunch',
    time: '25 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and patted dry' },
      { qty: '4 cups', item: 'broccoli florets' },
      { qty: '1', item: 'carrot, thinly sliced' },
      { qty: '1', item: 'red bell pepper, sliced' },
      { qty: '2 tbsp', item: 'oil' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'grated fresh ginger' },
      { qty: '3 tbsp', item: 'tamari (gluten-free soy sauce)' },
      { qty: '1 tbsp', item: 'rice vinegar' },
      { qty: '1 tsp', item: 'toasted sesame oil' },
      { qty: '1 tsp', item: 'maple syrup' },
      { qty: '1 tbsp', item: 'sesame seeds' },
    ],
    steps: [
      'Whisk tamari, rice vinegar, sesame oil, and maple syrup for the sauce and set aside.',
      'Heat 1 tbsp oil in a large skillet or wok and stir-fry the chickpeas 5 minutes until lightly crisp; remove.',
      'Add the remaining oil, then broccoli, carrot, and bell pepper. Stir-fry 5-6 minutes with a splash of water to steam-crisp.',
      'Add garlic and ginger for 1 minute, then return the chickpeas.',
      'Pour in the sauce, toss 1-2 minutes until glossy, and finish with sesame seeds. Serve over quinoa or brown rice if you like.',
    ],
    superAgeNote: 'Broccoli and chickpeas provide the vegetable and legume fiber the JAMA Network Open study links to healthier aging in a quick, savory stir-fry.',
    nutrition: { cal: 420, protein: 18, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
    airfryer: [
      'Air fry the drained chickpeas at 390F (199C) for 12-14 minutes until crisp, then toss with the stir-fried vegetables and sauce.',
    ],
  },
  {
    id: 'sa-lu-savory-oatmeal-egg-greens',
    name: 'Savory Oatmeal Bowl with Egg and Greens',
    emoji: '🍳',
    category: 'lunch',
    time: '20 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1 cup', item: 'rolled oats' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '3 cups', item: 'chopped kale or spinach' },
      { qty: '2', item: 'eggs' },
      { qty: '2 tbsp', item: 'grated Parmesan' },
      { qty: '2', item: 'green onions, sliced' },
      { qty: '1 tsp', item: 'hot sauce (optional)' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Simmer the oats in the broth 5-7 minutes, stirring, until creamy and thick. Season with salt and pepper.',
      'Meanwhile, heat olive oil and cook garlic 30 seconds, then add the greens and saute 3 minutes until wilted.',
      'Fry or soft-boil the eggs to your liking.',
      'Stir the Parmesan into the oats, then divide between two bowls.',
      'Top each with the sauteed greens, an egg, green onions, and a dash of hot sauce.',
    ],
    superAgeNote: 'Whole-grain oats are a high-fiber, minimally processed carb the JAMA Network Open study links to healthier aging, made savory with greens and a runny egg.',
    nutrition: { cal: 380, protein: 20, fiber: 10 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-lu-millet-roasted-veg-pilaf',
    name: 'Millet and Roasted Vegetable Pilaf',
    emoji: '🍚',
    category: 'lunch',
    time: '40 min',
    serves: 2,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '3/4 cup', item: 'millet, rinsed' },
      { qty: '1.5 cups', item: 'vegetable broth' },
      { qty: '1', item: 'zucchini, diced' },
      { qty: '1', item: 'red bell pepper, diced' },
      { qty: '1 cup', item: 'cherry tomatoes' },
      { qty: '3 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1/2 tsp', item: 'ground coriander' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained' },
      { qty: '1/4 cup', item: 'chopped parsley' },
      { qty: '1', item: 'lemon, juiced' },
      { qty: '1 pinch', item: 'salt and black pepper' },
    ],
    steps: [
      'Toast the millet in a dry pan 2 minutes until nutty, then add broth, bring to a boil, and simmer covered 18 minutes. Rest 5 minutes and fluff.',
      'Heat oven to 425F (220C). Toss zucchini, bell pepper, tomatoes, and chickpeas with 2 tbsp olive oil, cumin, coriander, salt, and pepper.',
      'Roast 22-25 minutes until the vegetables are tender and the chickpeas are crisp.',
      'Fold the roasted vegetables and chickpeas into the fluffed millet.',
      'Finish with the remaining olive oil, lemon juice, and parsley.',
    ],
    superAgeNote: 'Millet is a whole grain and, with chickpeas and roasted vegetables, provides the layered fiber-rich carbs the JAMA Network Open study associates with healthier aging.',
    nutrition: { cal: 480, protein: 16, fiber: 14 },
    added: '2026-07-27',
    isCustom: true,
    airfryer: [
      'Air fry the seasoned vegetables and chickpeas at 390F (199C) for 15-17 minutes, shaking twice, until tender and crisped.',
    ],
  },
];

(function () {
  if (typeof KANDY_RECIPES !== 'undefined') KANDY_RECIPES.push(...SUPERAGE_LUNCH);
  SUPERAGE_LUNCH.forEach(function (r) {
    if (r.airfryer && typeof AIRFRYER !== 'undefined') AIRFRYER[r.id] = r.airfryer;
    if (r.nutrition && typeof RECIPE_NUTRITION !== 'undefined') RECIPE_NUTRITION[r.id] = r.nutrition;
  });
})();
