// SuperAge Longevity-Carb SNACKS
// Real, makeable high-fiber snacks inspired by a 30-year JAMA Network Open study
// linking high-quality, fiber-rich carbohydrates to healthier aging.
// Hero longevity carbs: whole grains, fruits, vegetables, legumes, nuts and seeds.

const SUPERAGE_SNACKS = [
  {
    id: 'sa-sn-apple-cinnamon-oat-cups',
    name: 'Apple-Cinnamon Baked Oatmeal Cups',
    emoji: '🍎',
    category: 'snack',
    time: '35 min',
    serves: 12,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '3 cups', item: 'rolled oats' },
      { qty: '1 tsp', item: 'baking powder' },
      { qty: '2 tsp', item: 'ground cinnamon' },
      { qty: '2', item: 'apples, cored and finely diced (skin on)' },
      { qty: '2 tbsp', item: 'ground flaxseed' },
      { qty: '1.5 cups', item: 'unsweetened almond milk' },
      { qty: '3 tbsp', item: 'maple syrup' },
      { qty: '1 tsp', item: 'vanilla extract' },
    ],
    steps: [
      'Preheat the oven to 375F (190C) and line a 12-cup muffin tin with paper liners.',
      'Stir the flaxseed into the almond milk and let it sit 5 minutes to thicken.',
      'In a bowl, combine the oats, baking powder, and cinnamon.',
      'Add the flax-milk mixture, maple syrup, vanilla, and most of the diced apple; stir well.',
      'Divide among the muffin cups, press down gently, and top with the remaining apple.',
      'Bake 22 to 25 minutes until set and golden at the edges. Cool before removing.',
    ],
    superAgeNote: 'Whole-grain oats and skin-on apple are exactly the fiber-rich, high-quality carbs the JAMA study associated with healthier aging, delivering roughly 5g of fiber per cup.',
    nutrition: { cal: 150, protein: 4, fiber: 5 },
    airfryer: [
      'Use silicone muffin cups that fit your basket and work in batches.',
      'Air fry at 350F (175C) for 12 to 15 minutes until set and springy on top.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-smoky-roasted-chickpeas',
    name: 'Smoky Paprika Roasted Chickpeas',
    emoji: '🫘',
    category: 'snack',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '2 cans (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1.5 tsp', item: 'smoked paprika' },
      { qty: '0.5 tsp', item: 'garlic powder' },
      { qty: '0.5 tsp', item: 'ground cumin' },
      { qty: '0.5 tsp', item: 'salt' },
    ],
    steps: [
      'Preheat the oven to 400F (200C).',
      'Pat the chickpeas very dry with a towel, discarding any loose skins for extra crunch.',
      'Toss with olive oil, then spread on a parchment-lined baking sheet.',
      'Roast 30 to 35 minutes, shaking the pan halfway, until deeply crisp.',
      'Immediately toss the hot chickpeas with the paprika, garlic powder, cumin, and salt.',
      'Cool 5 minutes so they crisp further, then serve.',
    ],
    superAgeNote: 'Chickpeas are a legume the study highlights as a high-quality carbohydrate, and one crunchy serving carries about 6g of fiber plus plant protein.',
    nutrition: { cal: 175, protein: 8, fiber: 6 },
    airfryer: [
      'Air fry the oiled chickpeas at 390F (200C) for 15 to 18 minutes, shaking twice.',
      'Toss with the spices while hot, then let cool to crisp up.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-honey-cinnamon-chickpeas',
    name: 'Honey-Cinnamon Roasted Chickpeas',
    emoji: '🍯',
    category: 'snack',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '2 cans (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 tbsp', item: 'coconut oil, melted' },
      { qty: '2 tbsp', item: 'honey' },
      { qty: '1.5 tsp', item: 'ground cinnamon' },
      { qty: '1 tbsp', item: 'coconut sugar' },
      { qty: '1 pinch', item: 'salt' },
    ],
    steps: [
      'Preheat the oven to 375F (190C) and pat the chickpeas thoroughly dry.',
      'Toss with the melted coconut oil and roast on parchment for 25 minutes.',
      'Whisk the honey, cinnamon, coconut sugar, and salt in a bowl.',
      'Add the hot chickpeas, toss to coat, then return to the pan.',
      'Roast 8 to 10 minutes more, watching closely so the honey does not burn.',
      'Cool completely on the pan; they harden into a sweet, candied crunch.',
    ],
    superAgeNote: 'A sweeter take on a legume snack, these keep the fiber-rich chickpea (about 5g per serving) the study links to healthier aging while satisfying a dessert craving.',
    nutrition: { cal: 195, protein: 7, fiber: 5 },
    airfryer: [
      'Air fry the oiled chickpeas at 380F (195C) for 12 minutes, then toss with the honey mixture.',
      'Air fry 4 to 5 minutes more, then cool fully to harden.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-black-bean-brownie-bites',
    name: 'Black Bean Brownie Bites',
    emoji: '🍫',
    category: 'snack',
    time: '30 min',
    serves: 12,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '2', item: 'eggs' },
      { qty: '3 tbsp', item: 'cocoa powder' },
      { qty: '0.25 cup', item: 'maple syrup' },
      { qty: '2 tbsp', item: 'almond butter' },
      { qty: '1 tsp', item: 'vanilla extract' },
      { qty: '0.5 tsp', item: 'baking powder' },
      { qty: '0.25 cup', item: 'dark chocolate chips' },
    ],
    steps: [
      'Preheat the oven to 350F (175C) and grease a 12-cup mini muffin tin.',
      'Blend the black beans, eggs, cocoa, maple syrup, almond butter, vanilla, and baking powder until completely smooth.',
      'Stir in most of the chocolate chips by hand.',
      'Spoon into the muffin cups and top with the remaining chips.',
      'Bake 15 to 18 minutes until the tops are set. Cool in the pan before removing.',
    ],
    superAgeNote: 'Pureed black beans give these fudgy bites their structure, folding a legume the study ties to healthier aging into a treat with roughly 4g of fiber each.',
    nutrition: { cal: 110, protein: 4, fiber: 4 },
    airfryer: [
      'Use a silicone mini-muffin mold that fits the basket.',
      'Air fry at 320F (160C) for 12 to 14 minutes until set, then cool before unmolding.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-baked-kale-chips',
    name: 'Crispy Baked Kale Chips',
    emoji: '🥬',
    category: 'snack',
    time: '25 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 large bunch', item: 'curly kale' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '0.5 tsp', item: 'sea salt' },
      { qty: '2 tbsp', item: 'nutritional yeast' },
      { qty: '0.25 tsp', item: 'garlic powder' },
    ],
    steps: [
      'Preheat the oven to 300F (150C).',
      'Strip the kale leaves from the stems and tear into large chip-size pieces.',
      'Wash and dry the kale completely; any water left on will steam instead of crisp.',
      'Massage the leaves with olive oil, then toss with salt, nutritional yeast, and garlic powder.',
      'Spread in a single layer on two baking sheets, not overlapping.',
      'Bake 15 to 20 minutes until crisp and dry, rotating the pans halfway.',
    ],
    superAgeNote: 'Kale is a leafy green the study counts among high-quality, fiber-rich plant foods, and a big bowl of these chips lands around 3g of fiber for very few calories.',
    nutrition: { cal: 80, protein: 4, fiber: 3 },
    airfryer: [
      'Air fry the dressed kale at 300F (150C) for 5 to 7 minutes in small batches.',
      'Shake or check every 2 minutes, as thin kale crisps and can scorch fast.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-carrot-fries-yogurt-dip',
    name: 'Roasted Carrot Fries with Yogurt-Herb Dip',
    emoji: '🥕',
    category: 'snack',
    time: '35 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1.5 lb', item: 'carrots, cut into thin fry-shaped sticks' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '0.5 tsp', item: 'smoked paprika' },
      { qty: '0.5 tsp', item: 'salt' },
      { qty: '0.75 cup', item: 'plain Greek yogurt' },
      { qty: '1 tbsp', item: 'chopped fresh dill' },
      { qty: '1 tsp', item: 'lemon juice' },
      { qty: '1 pinch', item: 'garlic powder' },
    ],
    steps: [
      'Preheat the oven to 425F (220C).',
      'Toss the carrot sticks with olive oil, paprika, and salt.',
      'Spread in a single layer on a baking sheet, leaving space between them.',
      'Roast 25 to 28 minutes, flipping once, until browned and tender.',
      'Meanwhile, stir together the yogurt, dill, lemon juice, and garlic powder for the dip.',
      'Serve the carrot fries hot with the cool herb dip.',
    ],
    superAgeNote: 'Carrots are a fiber-rich vegetable the study associates with healthier aging, and the Greek yogurt dip adds protein for a balanced snack near 4g of fiber.',
    nutrition: { cal: 140, protein: 6, fiber: 5 },
    airfryer: [
      'Air fry the oiled carrot sticks at 400F (200C) for 14 to 16 minutes, shaking twice.',
      'Serve with the stirred-together yogurt dip.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-ranch-popcorn',
    name: 'Ranch-Seasoned Stovetop Popcorn',
    emoji: '🍿',
    category: 'snack',
    time: '10 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '0.33 cup', item: 'popcorn kernels' },
      { qty: '2 tbsp', item: 'olive oil, divided' },
      { qty: '1 tbsp', item: 'nutritional yeast' },
      { qty: '0.5 tsp', item: 'dried dill' },
      { qty: '0.5 tsp', item: 'onion powder' },
      { qty: '0.5 tsp', item: 'garlic powder' },
      { qty: '0.5 tsp', item: 'salt' },
    ],
    steps: [
      'Stir the nutritional yeast, dill, onion powder, garlic powder, and salt together in a small bowl.',
      'Heat 1 tablespoon oil in a large pot over medium-high with 3 test kernels and the lid on.',
      'When the test kernels pop, add the rest and cover, shaking the pot occasionally.',
      'Once popping slows to a few seconds between pops, remove from heat.',
      'Drizzle with the remaining oil, then sprinkle on the ranch seasoning and toss well.',
    ],
    superAgeNote: 'Popcorn is a whole grain, and the study links whole-grain carbs to healthier aging; this batch delivers about 4g of fiber without the additives of packaged versions.',
    nutrition: { cal: 160, protein: 4, fiber: 4 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-popcorn-trail-mix',
    name: 'Popcorn and Almond Trail Mix',
    emoji: '🍿',
    category: 'snack',
    time: '10 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '6 cups', item: 'air-popped popcorn' },
      { qty: '0.5 cup', item: 'raw almonds' },
      { qty: '0.5 cup', item: 'pumpkin seeds' },
      { qty: '0.5 cup', item: 'dried cranberries' },
      { qty: '0.25 cup', item: 'dark chocolate chips' },
      { qty: '0.5 tsp', item: 'ground cinnamon' },
    ],
    steps: [
      'Let the popcorn cool completely so the chocolate chips will not melt.',
      'In a large bowl, combine the popcorn, almonds, pumpkin seeds, and cranberries.',
      'Sprinkle in the cinnamon and toss to distribute.',
      'Add the chocolate chips last and toss gently.',
      'Store in an airtight container for up to a week.',
    ],
    superAgeNote: 'Built on whole-grain popcorn with nuts, seeds, and fruit, this mix layers several high-quality carbs the study connects to healthier aging for roughly 4g of fiber per portion.',
    nutrition: { cal: 210, protein: 6, fiber: 4 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-maple-oat-granola-clusters',
    name: 'Maple Oat Granola Clusters',
    emoji: '🥣',
    category: 'snack',
    time: '35 min',
    serves: 8,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '2.5 cups', item: 'rolled oats' },
      { qty: '0.5 cup', item: 'chopped pecans' },
      { qty: '2 tbsp', item: 'chia seeds' },
      { qty: '0.33 cup', item: 'maple syrup' },
      { qty: '3 tbsp', item: 'almond butter' },
      { qty: '2 tbsp', item: 'coconut oil, melted' },
      { qty: '1 tsp', item: 'vanilla extract' },
      { qty: '0.5 tsp', item: 'salt' },
    ],
    steps: [
      'Preheat the oven to 325F (160C) and line a baking sheet with parchment.',
      'Whisk the maple syrup, almond butter, coconut oil, vanilla, and salt until smooth.',
      'Fold in the oats, pecans, and chia seeds until fully coated.',
      'Press the mixture firmly into a compact slab on the pan; pressing helps clusters form.',
      'Bake 20 to 24 minutes until golden, without stirring.',
      'Cool completely, then break into clusters.',
    ],
    superAgeNote: 'Whole-grain oats anchor these clusters, and the study associates such fiber-rich grains with healthier aging; each serving carries about 5g of fiber plus omega-rich chia.',
    nutrition: { cal: 220, protein: 6, fiber: 5 },
    airfryer: [
      'Press the mixture into a parchment-lined air-fryer pan.',
      'Air fry at 300F (150C) for 12 to 15 minutes until golden, then cool fully before breaking.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-yogurt-berry-parfait',
    name: 'Greek Yogurt Berry Granola Parfait',
    emoji: '🫐',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1.5 cups', item: 'plain Greek yogurt' },
      { qty: '1 cup', item: 'mixed berries (blueberries, raspberries)' },
      { qty: '0.5 cup', item: 'oat granola' },
      { qty: '1 tbsp', item: 'chia seeds' },
      { qty: '2 tsp', item: 'honey' },
    ],
    steps: [
      'Stir the chia seeds into the yogurt and let sit 2 minutes to thicken.',
      'Spoon a layer of yogurt into the bottom of two glasses or jars.',
      'Add a layer of berries, then a layer of granola.',
      'Repeat the layers, finishing with berries on top.',
      'Drizzle with honey and serve, or chill until ready.',
    ],
    superAgeNote: 'Fiber-rich berries and whole-grain oat granola are high-quality carbs the study ties to healthier aging, while Greek yogurt adds the protein for staying power, at roughly 6g of fiber.',
    nutrition: { cal: 260, protein: 15, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-frozen-yogurt-berry-bark',
    name: 'Frozen Yogurt-Berry Bark',
    emoji: '🍓',
    category: 'snack',
    time: '15 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2 cups', item: 'plain Greek yogurt' },
      { qty: '2 tbsp', item: 'honey' },
      { qty: '0.5 tsp', item: 'vanilla extract' },
      { qty: '1 cup', item: 'raspberries and blueberries' },
      { qty: '0.33 cup', item: 'oat granola' },
      { qty: '2 tbsp', item: 'sliced almonds' },
    ],
    steps: [
      'Line a rimmed baking sheet with parchment paper.',
      'Stir the honey and vanilla into the yogurt until smooth.',
      'Spread the yogurt about a quarter inch thick over the parchment.',
      'Scatter the berries, granola, and almonds evenly over the top, pressing in lightly.',
      'Freeze at least 3 hours until solid.',
      'Break into shards and keep frozen; let it soften 1 minute before eating.',
    ],
    superAgeNote: 'This frozen treat leans on fiber-rich berries and oat granola, the kind of high-quality carbs the study links to healthier aging, with about 3g of fiber per shard.',
    nutrition: { cal: 130, protein: 8, fiber: 3 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-banana-oat-cookies',
    name: 'Three-Ingredient Banana-Oat Cookies',
    emoji: '🍪',
    category: 'snack',
    time: '25 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '2 large', item: 'ripe bananas, mashed' },
      { qty: '1.5 cups', item: 'rolled oats' },
      { qty: '0.25 cup', item: 'chopped walnuts' },
      { qty: '2 tbsp', item: 'dark chocolate chips' },
      { qty: '0.5 tsp', item: 'ground cinnamon' },
    ],
    steps: [
      'Preheat the oven to 350F (175C) and line a baking sheet with parchment.',
      'Mash the bananas well, then stir in the oats and cinnamon until no dry oats remain.',
      'Fold in the walnuts and chocolate chips.',
      'Scoop 12 mounds onto the sheet and flatten slightly with the back of a spoon.',
      'Bake 12 to 15 minutes until set and lightly golden. Cool on the pan.',
    ],
    superAgeNote: 'Whole-grain oats and banana form these naturally sweet cookies, folding in the fiber-rich grain the study associates with healthier aging at about 3g of fiber each.',
    nutrition: { cal: 130, protein: 3, fiber: 3 },
    airfryer: [
      'Place flattened cookies on parchment in the basket, spaced apart.',
      'Air fry at 330F (165C) for 8 to 10 minutes until set, working in batches.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-roasted-red-pepper-hummus',
    name: 'Quick Roasted Red Pepper Hummus with Veggie Dippers',
    emoji: '🫑',
    category: 'snack',
    time: '15 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '0.5 cup', item: 'jarred roasted red peppers, drained' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '1 small', item: 'garlic clove' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '0.5 tsp', item: 'ground cumin' },
      { qty: '0.5 tsp', item: 'salt' },
      { qty: '4 cups', item: 'carrot, cucumber, and bell pepper sticks' },
    ],
    steps: [
      'Add the chickpeas, roasted peppers, tahini, lemon juice, garlic, cumin, and salt to a food processor.',
      'Blend, drizzling in the olive oil, until very smooth.',
      'If needed, add 1 to 2 tablespoons cold water to loosen to a scoopable texture.',
      'Taste and adjust lemon and salt.',
      'Spread in a bowl, drizzle with a little more olive oil, and serve with the veggie sticks.',
    ],
    superAgeNote: 'Chickpeas plus a rainbow of raw vegetables stack two high-quality, fiber-rich carbs the study links to healthier aging, bringing roughly 5g of fiber per serving.',
    nutrition: { cal: 190, protein: 6, fiber: 5 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-apple-nachos',
    name: 'Apple Nachos with Granola and Almond Butter',
    emoji: '🍏',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2', item: 'apples, cored and thinly sliced (skin on)' },
      { qty: '3 tbsp', item: 'almond butter, warmed' },
      { qty: '0.33 cup', item: 'oat granola' },
      { qty: '2 tbsp', item: 'pumpkin seeds' },
      { qty: '1 tbsp', item: 'dark chocolate chips' },
      { qty: '1 pinch', item: 'flaky salt' },
    ],
    steps: [
      'Fan the apple slices out over a large plate in an overlapping layer.',
      'Warm the almond butter for a few seconds so it drizzles easily.',
      'Drizzle the almond butter back and forth over the apples.',
      'Scatter the granola, pumpkin seeds, and chocolate chips on top.',
      'Finish with a tiny pinch of flaky salt and serve immediately with forks.',
    ],
    superAgeNote: 'Skin-on apple and oat granola are fiber-rich, high-quality carbs the study ties to healthier aging, and this shareable plate lands around 6g of fiber per serving.',
    nutrition: { cal: 300, protein: 8, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-carrot-cake-bites',
    name: 'No-Bake Carrot Cake Energy Bites',
    emoji: '🥕',
    category: 'snack',
    time: '20 min',
    serves: 8,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1 cup', item: 'rolled oats' },
      { qty: '0.75 cup', item: 'finely grated carrot' },
      { qty: '0.5 cup', item: 'pitted dates' },
      { qty: '0.33 cup', item: 'walnuts' },
      { qty: '2 tbsp', item: 'ground flaxseed' },
      { qty: '1 tsp', item: 'ground cinnamon' },
      { qty: '0.25 tsp', item: 'ground ginger' },
      { qty: '2 tbsp', item: 'shredded unsweetened coconut' },
    ],
    steps: [
      'Squeeze excess moisture from the grated carrot with a paper towel.',
      'Pulse the dates and walnuts in a food processor until crumbly and sticky.',
      'Add the oats, carrot, flaxseed, cinnamon, and ginger; pulse until a dough forms.',
      'Roll into 16 bite-size balls, pressing firmly so they hold together.',
      'Roll each ball in the shredded coconut and chill 30 minutes to set.',
    ],
    superAgeNote: 'These bites combine whole-grain oats with fiber-rich carrot, both high-quality carbs the study associates with healthier aging, for about 3g of fiber per couple of bites.',
    nutrition: { cal: 120, protein: 3, fiber: 3 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-orange-oat-energy-balls',
    name: 'Orange-Oat Energy Balls',
    emoji: '🍊',
    category: 'snack',
    time: '20 min',
    serves: 8,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1.25 cups', item: 'rolled oats' },
      { qty: '0.5 cup', item: 'almond butter' },
      { qty: '3 tbsp', item: 'maple syrup' },
      { qty: '1 tbsp', item: 'orange zest' },
      { qty: '2 tbsp', item: 'fresh orange juice' },
      { qty: '2 tbsp', item: 'chia seeds' },
      { qty: '0.25 cup', item: 'chopped dried apricots' },
    ],
    steps: [
      'In a bowl, stir together the almond butter, maple syrup, orange zest, and orange juice.',
      'Add the oats, chia seeds, and dried apricots; mix until a sticky dough forms.',
      'If the dough is too soft, chill it 10 minutes to firm up.',
      'Roll into 16 balls, pressing firmly.',
      'Refrigerate at least 30 minutes before serving; store chilled up to a week.',
    ],
    superAgeNote: 'Whole-grain oats plus bright orange give these no-bake balls two of the fiber-rich carbs the study links to healthier aging, at roughly 3g of fiber per serving.',
    nutrition: { cal: 175, protein: 5, fiber: 4 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-parmesan-broccoli-bites',
    name: 'Parmesan Roasted Broccoli Bites',
    emoji: '🥦',
    category: 'snack',
    time: '30 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1 large head', item: 'broccoli, cut into small florets' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '0.33 cup', item: 'grated Parmesan cheese' },
      { qty: '0.5 tsp', item: 'garlic powder' },
      { qty: '0.5 tsp', item: 'salt' },
      { qty: '1 tsp', item: 'lemon zest' },
    ],
    steps: [
      'Preheat the oven to 425F (220C).',
      'Toss the florets with olive oil, garlic powder, and salt.',
      'Spread cut-side down on a baking sheet in a single layer.',
      'Roast 18 to 20 minutes until the edges are crisp and browned.',
      'Sprinkle the Parmesan over the hot broccoli and roast 3 minutes more to melt.',
      'Finish with lemon zest and serve warm.',
    ],
    superAgeNote: 'Broccoli is a fiber-rich vegetable the study counts among high-quality carbs tied to healthier aging, and a serving of these crispy bites carries about 4g of fiber.',
    nutrition: { cal: 150, protein: 7, fiber: 4 },
    airfryer: [
      'Air fry the oiled florets at 390F (200C) for 10 to 12 minutes, shaking once.',
      'Add the Parmesan and air fry 2 minutes more, then finish with lemon zest.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-crispy-roasted-lentils',
    name: 'Crispy Curry-Roasted Lentils',
    emoji: '🫘',
    category: 'snack',
    time: '35 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '2 cups', item: 'cooked brown or green lentils, well drained' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'curry powder' },
      { qty: '0.5 tsp', item: 'ground turmeric' },
      { qty: '0.5 tsp', item: 'salt' },
      { qty: '0.25 tsp', item: 'cayenne (optional)' },
    ],
    steps: [
      'Preheat the oven to 400F (200C).',
      'Pat the cooked lentils very dry with a towel; extra moisture keeps them from crisping.',
      'Toss with the olive oil, curry powder, turmeric, salt, and cayenne.',
      'Spread on a parchment-lined baking sheet in a thin layer.',
      'Roast 25 to 30 minutes, stirring twice, until crunchy.',
      'Cool on the pan, where they will crisp up further.',
    ],
    superAgeNote: 'Lentils are a legume the study highlights as a high-quality carbohydrate, and this crunchy snack keeps their fiber intact at roughly 7g per serving.',
    nutrition: { cal: 165, protein: 9, fiber: 7 },
    airfryer: [
      'Air fry the seasoned lentils at 380F (195C) for 12 to 15 minutes, shaking every few minutes.',
      'Cool fully before eating so they finish crisping.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-berry-chia-oat-pudding',
    name: 'Berry Chia Overnight Oat Pudding',
    emoji: '🫐',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '0.5 cup', item: 'rolled oats' },
      { qty: '3 tbsp', item: 'chia seeds' },
      { qty: '1.25 cups', item: 'unsweetened almond milk' },
      { qty: '1 tbsp', item: 'maple syrup' },
      { qty: '0.5 tsp', item: 'vanilla extract' },
      { qty: '1 cup', item: 'mixed berries' },
    ],
    steps: [
      'Stir the oats, chia seeds, almond milk, maple syrup, and vanilla together in a jar.',
      'Let it sit 5 minutes, then stir again to break up any chia clumps.',
      'Cover and refrigerate overnight, or at least 4 hours, until thick and spoonable.',
      'In the morning, stir and loosen with a splash of milk if needed.',
      'Top with the mixed berries and serve.',
    ],
    superAgeNote: 'Whole-grain oats, chia, and berries combine three fiber-rich foods the study associates with healthier aging, giving this make-ahead pudding around 8g of fiber per serving.',
    nutrition: { cal: 240, protein: 7, fiber: 8 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-quinoa-granola-bars',
    name: 'Toasted Quinoa Granola Bars',
    emoji: '🌾',
    category: 'snack',
    time: '40 min',
    serves: 10,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1.5 cups', item: 'rolled oats' },
      { qty: '0.5 cup', item: 'uncooked quinoa, rinsed' },
      { qty: '0.5 cup', item: 'chopped almonds' },
      { qty: '0.33 cup', item: 'honey' },
      { qty: '0.25 cup', item: 'almond butter' },
      { qty: '2 tbsp', item: 'coconut oil' },
      { qty: '0.33 cup', item: 'dried cherries' },
      { qty: '0.25 tsp', item: 'salt' },
    ],
    steps: [
      'Preheat the oven to 350F (175C) and line an 8-inch pan with parchment.',
      'Spread the oats, quinoa, and almonds on a baking sheet and toast 8 minutes until fragrant.',
      'Warm the honey, almond butter, and coconut oil in a saucepan until smooth.',
      'Stir the toasted oat mixture, dried cherries, and salt into the honey mixture.',
      'Press the mixture very firmly into the lined pan; firm packing prevents crumbling.',
      'Chill 1 hour until set, then lift out and cut into 10 bars.',
    ],
    superAgeNote: 'Quinoa and oats are whole grains the study associates with healthier aging as high-quality carbs, and each bar delivers roughly 4g of fiber plus complete plant protein.',
    nutrition: { cal: 210, protein: 6, fiber: 4 },
    airfryer: [
      'Toast the oats, quinoa, and almonds in the air fryer at 350F (175C) for 6 to 7 minutes, shaking often.',
      'Continue with the stovetop honey mixture, then press and chill as directed.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-orange-cranberry-scone-bites',
    name: 'Orange-Cranberry Oat Scone Bites',
    emoji: '🍊',
    category: 'snack',
    time: '30 min',
    serves: 8,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '1.5 cups', item: 'oat flour' },
      { qty: '1 cup', item: 'rolled oats' },
      { qty: '1.5 tsp', item: 'baking powder' },
      { qty: '3 tbsp', item: 'cold butter, cubed' },
      { qty: '1', item: 'egg' },
      { qty: '3 tbsp', item: 'maple syrup' },
      { qty: '1 tbsp', item: 'orange zest' },
      { qty: '3 tbsp', item: 'orange juice' },
      { qty: '0.33 cup', item: 'dried cranberries' },
    ],
    steps: [
      'Preheat the oven to 375F (190C) and line a baking sheet with parchment.',
      'Whisk the oat flour, oats, and baking powder together in a bowl.',
      'Cut in the cold butter with your fingers until the mixture looks like coarse crumbs.',
      'Stir in the egg, maple syrup, orange zest, orange juice, and cranberries to form a soft dough.',
      'Pat into a 1-inch-thick round, cut into 8 wedges, and separate them on the pan.',
      'Bake 15 to 18 minutes until golden at the edges. Cool before serving.',
    ],
    superAgeNote: 'Made with oat flour and whole oats plus orange, these bites feature the fiber-rich, high-quality carbs the study links to healthier aging at about 3g of fiber each.',
    nutrition: { cal: 180, protein: 5, fiber: 3 },
    airfryer: [
      'Place the wedges on parchment in the basket, spaced apart.',
      'Air fry at 340F (170C) for 10 to 12 minutes until golden, working in batches.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-oatmeal-raisin-nobake-bars',
    name: 'No-Bake Oatmeal Raisin Bars',
    emoji: '🍯',
    category: 'snack',
    time: '15 min',
    serves: 9,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2 cups', item: 'rolled oats' },
      { qty: '0.5 cup', item: 'peanut butter' },
      { qty: '0.33 cup', item: 'honey' },
      { qty: '0.5 cup', item: 'raisins' },
      { qty: '2 tbsp', item: 'ground flaxseed' },
      { qty: '1 tsp', item: 'ground cinnamon' },
      { qty: '0.5 tsp', item: 'vanilla extract' },
    ],
    steps: [
      'Line an 8-inch square pan with parchment paper.',
      'Warm the peanut butter and honey together until pourable and smooth.',
      'Stir in the vanilla, then mix in the oats, raisins, flaxseed, and cinnamon until coated.',
      'Press the mixture very firmly and evenly into the pan.',
      'Refrigerate at least 1 hour until firm, then lift out and cut into 9 bars.',
    ],
    superAgeNote: 'These no-bake bars are built on whole-grain oats, the fiber-rich carbohydrate the study associates with healthier aging, delivering about 4g of fiber per bar.',
    nutrition: { cal: 210, protein: 6, fiber: 4 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-lemon-herb-barley-cups',
    name: 'Lemon-Herb Barley Snack Cups',
    emoji: '🌾',
    category: 'snack',
    time: '30 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian'],
    ingredients: [
      { qty: '1 cup', item: 'cooked pearl barley, cooled' },
      { qty: '0.5 cup', item: 'canned chickpeas, rinsed' },
      { qty: '0.5 cup', item: 'diced cucumber' },
      { qty: '0.25 cup', item: 'diced red bell pepper' },
      { qty: '2 tbsp', item: 'chopped parsley' },
      { qty: '2 tbsp', item: 'crumbled feta' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '0.25 tsp', item: 'salt' },
    ],
    steps: [
      'Whisk the olive oil, lemon juice, and salt together in a bowl.',
      'Add the cooled barley, chickpeas, cucumber, bell pepper, and parsley.',
      'Toss until everything is evenly coated in the dressing.',
      'Fold in the crumbled feta.',
      'Spoon into small cups or jars; serve chilled or at room temperature.',
    ],
    superAgeNote: 'Barley is a whole grain the study links to healthier aging, and this savory cup pairs it with chickpeas and vegetables for roughly 6g of fiber per serving.',
    nutrition: { cal: 200, protein: 6, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-pear-ricotta-walnut',
    name: 'Pear Slices with Ricotta and Walnuts',
    emoji: '🍐',
    category: 'snack',
    time: '5 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2', item: 'ripe pears, cored and sliced (skin on)' },
      { qty: '0.5 cup', item: 'ricotta cheese' },
      { qty: '0.25 cup', item: 'chopped walnuts' },
      { qty: '2 tsp', item: 'honey' },
      { qty: '1 pinch', item: 'ground cinnamon' },
    ],
    steps: [
      'Arrange the pear slices on a plate.',
      'Dollop or spread a little ricotta onto each slice.',
      'Scatter the chopped walnuts over the top.',
      'Drizzle with honey and dust with cinnamon.',
      'Serve right away while the pears are crisp.',
    ],
    superAgeNote: 'A skin-on pear keeps its full fiber, the high-quality fruit carbohydrate the study associates with healthier aging, and this quick plate lands around 6g of fiber per serving.',
    nutrition: { cal: 250, protein: 8, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
];

(function () {
  if (typeof KANDY_RECIPES !== 'undefined') KANDY_RECIPES.push(...SUPERAGE_SNACKS);
  SUPERAGE_SNACKS.forEach(function (r) {
    if (r.airfryer && typeof AIRFRYER !== 'undefined') AIRFRYER[r.id] = r.airfryer;
    if (r.nutrition && typeof RECIPE_NUTRITION !== 'undefined') RECIPE_NUTRITION[r.id] = r.nutrition;
  });
})();
