// SuperAge Dinner Recipes
// Healthy, high-fiber "longevity carb" dinners inspired by a SuperAge article on a
// 30-year study (JAMA Network Open) linking high-quality, fiber-rich carbohydrates
// to healthier aging. Star foods: whole grains (quinoa, barley, millet), legumes
// (lentils, chickpeas, black beans), and vegetables (kale, spinach, broccoli, carrots).

const SUPERAGE_DINNER = [
  {
    id: 'sa-di-lentil-carrot-shepherds-pie-broccoli-mash',
    name: 'Lentil-Carrot Shepherd\'s Pie with Broccoli Mash',
    emoji: '🥧',
    category: 'dinner',
    time: '55 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'dried green lentils' },
      { qty: '3', item: 'carrots, diced' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '2 tbsp', item: 'tomato paste' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 large head', item: 'broccoli, cut into florets' },
      { qty: '2', item: 'russet potatoes, peeled and cubed' },
      { qty: '2 tbsp', item: 'plant milk' },
      { qty: '1 tsp', item: 'dried thyme' },
    ],
    steps: [
      'Simmer lentils in the broth with tomato paste until tender, about 25 minutes.',
      'Meanwhile saute onion and carrots in olive oil until softened, then stir into the lentils with thyme; season well.',
      'Boil potatoes and broccoli together until fork-tender, drain, then mash with plant milk until fluffy and green-flecked.',
      'Spread the lentil filling in a baking dish and top with the broccoli mash, roughing the surface with a fork.',
      'Bake at 400F (205C) for 20 minutes until the top is golden. Rest 5 minutes before serving.',
    ],
    superAgeNote: 'Green lentils and broccoli deliver a carb-to-fiber ratio well under 10:1, the kind of high-quality, fiber-rich carbohydrate the JAMA Network Open aging study linked to healthier midlife aging.',
    nutrition: { cal: 470, protein: 22, fiber: 19 },
    airfryer: [
      'Assemble the pie in an air-fryer-safe dish.',
      'Air-fry at 380F (193C) for 12 to 15 minutes until the broccoli mash top is crisped and golden.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-quinoa-stuffed-peppers-black-bean-spinach',
    name: 'Quinoa-Stuffed Bell Peppers with Black Beans and Spinach',
    emoji: '🫑',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '4', item: 'bell peppers, tops removed and seeded' },
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '3 cups', item: 'fresh spinach, chopped' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 cup', item: 'salsa' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook quinoa in the broth until fluffy, about 15 minutes.',
      'Stir the black beans, spinach, cumin, smoked paprika, and half the salsa into the warm quinoa until the spinach wilts.',
      'Brush the peppers with olive oil and pack them full of the quinoa mixture.',
      'Stand the peppers in a baking dish, spoon the rest of the salsa over the tops, and cover with foil.',
      'Bake at 375F (190C) for 30 minutes, uncovering for the last 10 so the tops brown.',
    ],
    superAgeNote: 'Quinoa and black beans are exactly the whole-grain and legume pairing the SuperAge piece highlights, giving each pepper 3g-plus of fiber per serving from real, minimally processed carbs.',
    nutrition: { cal: 440, protein: 19, fiber: 16 },
    airfryer: [
      'Place stuffed peppers upright in an air-fryer-safe dish.',
      'Air-fry at 360F (182C) for 15 to 18 minutes until the peppers are tender and the tops are lightly charred.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-broccoli-curry-over-barley',
    name: 'Chickpea and Broccoli Curry over Barley',
    emoji: '🍛',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'pearl barley' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 large head', item: 'broccoli, cut into florets' },
      { qty: '1 can (14 oz)', item: 'diced tomatoes' },
      { qty: '1 cup', item: 'light coconut milk' },
      { qty: '2 tbsp', item: 'curry powder' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook barley in plenty of salted water until tender, about 30 minutes, then drain.',
      'Saute onion and garlic in olive oil, then stir in curry powder and toast for 1 minute.',
      'Add tomatoes, coconut milk, and chickpeas; simmer 10 minutes.',
      'Add the broccoli and simmer 8 more minutes until crisp-tender and the sauce has thickened.',
      'Spoon the curry over bowls of warm barley.',
    ],
    superAgeNote: 'Barley is one of the star longevity grains in the SuperAge article, and pairing it with chickpeas keeps this bowl in the low carb-to-fiber range tied to healthier aging.',
    nutrition: { cal: 480, protein: 18, fiber: 17 },
    airfryer: [
      'Toss the broccoli florets with a little oil and air-fry at 380F (193C) for 10 minutes until charred at the edges.',
      'Fold the roasted broccoli into the curry just before serving for a deeper flavor.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-black-bean-broccoli-quinoa-casserole',
    name: 'Black Bean and Broccoli Quinoa Casserole',
    emoji: '🍲',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '1 large head', item: 'broccoli, chopped small' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 cup', item: 'shredded cheddar' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'garlic powder' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook quinoa in the broth until fluffy, about 15 minutes.',
      'Saute onion in olive oil until soft, then stir in cumin and garlic powder.',
      'Combine the quinoa, onion, black beans, broccoli, and half the cheese in a baking dish.',
      'Top with the remaining cheese.',
      'Bake at 400F (205C) for 25 minutes until bubbling and the top is golden.',
    ],
    superAgeNote: 'Quinoa and black beans together supply plant protein plus the fiber-rich, high-quality carbohydrate the JAMA study associated with better aging outcomes.',
    nutrition: { cal: 490, protein: 24, fiber: 15 },
    airfryer: [
      'Assemble in an air-fryer-safe dish.',
      'Air-fry at 380F (193C) for 12 to 14 minutes until the cheese top is melted and browned.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-millet-pilaf-roasted-carrots-kale-chickpeas',
    name: 'Millet Pilaf with Roasted Carrots, Kale and Chickpeas',
    emoji: '🥕',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'millet' },
      { qty: '4', item: 'carrots, cut into coins' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '4 cups', item: 'kale, stemmed and chopped' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'ground coriander' },
      { qty: '1', item: 'lemon, juiced' },
    ],
    steps: [
      'Toast the millet in a dry pan for 2 minutes, then simmer in the broth until fluffy, about 20 minutes.',
      'Toss carrots and chickpeas with 1 tbsp oil and coriander and roast at 425F (220C) for 25 minutes.',
      'Massage the kale with the remaining oil and a pinch of salt until softened.',
      'Fold the roasted carrots, chickpeas, and kale into the warm millet.',
      'Finish with lemon juice and season to taste.',
    ],
    superAgeNote: 'Millet is a gluten-free longevity grain, and layering it with chickpeas and carrots keeps the fiber high and the carb-to-fiber ratio low, just as the SuperAge article recommends.',
    nutrition: { cal: 460, protein: 18, fiber: 15 },
    airfryer: [
      'Air-fry the carrots and chickpeas at 400F (205C) for 15 to 18 minutes, shaking halfway, until the carrots caramelize and the chickpeas crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lentil-bolognese-over-barley',
    name: 'Lentil Bolognese over Barley',
    emoji: '🍝',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'pearl barley' },
      { qty: '1 cup', item: 'dried brown lentils' },
      { qty: '1 can (28 oz)', item: 'crushed tomatoes' },
      { qty: '1', item: 'onion, finely chopped' },
      { qty: '2', item: 'carrots, finely diced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '2 tsp', item: 'dried oregano' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook barley in salted water until tender, about 30 minutes, then drain.',
      'Saute onion, carrots, and garlic in olive oil until soft.',
      'Add lentils, crushed tomatoes, oregano, and 2 cups water; simmer 30 minutes until the lentils are tender and the sauce is thick.',
      'Season generously with salt and pepper.',
      'Serve the bolognese ladled over the warm barley.',
    ],
    superAgeNote: 'Swapping refined pasta for barley and building the sauce on lentils turns a comfort classic into the fiber-rich, whole-grain-and-legume meal the aging study favored.',
    nutrition: { cal: 500, protein: 23, fiber: 20 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-kale-black-bean-skillet-quinoa',
    name: 'Kale and Black Bean Skillet with Quinoa',
    emoji: '🥬',
    category: 'dinner',
    time: '35 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '5 cups', item: 'kale, stemmed and chopped' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1', item: 'lime, juiced' },
    ],
    steps: [
      'Cook quinoa in the broth until fluffy, about 15 minutes.',
      'In a large skillet, saute garlic in olive oil, then add kale and cook until wilted.',
      'Stir in the black beans, smoked paprika, and cumin; heat through.',
      'Fold in the cooked quinoa and toss until everything is combined.',
      'Finish with lime juice and season to taste.',
    ],
    superAgeNote: 'This one-skillet mix of quinoa, black beans, and kale is dense in leafy-green and legume fiber, keeping the carbohydrate quality high the way the SuperAge study describes.',
    nutrition: { cal: 430, protein: 19, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-tikka-masala-spinach-millet',
    name: 'Chickpea Tikka Masala with Spinach over Millet',
    emoji: '🍛',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'millet' },
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '4 cups', item: 'fresh spinach' },
      { qty: '1 can (14 oz)', item: 'crushed tomatoes' },
      { qty: '0.5 cup', item: 'plain yogurt' },
      { qty: '2 tbsp', item: 'garam masala' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Simmer millet in 2 cups water until fluffy, about 20 minutes.',
      'Saute onion and garlic in olive oil, then stir in garam masala and toast for 1 minute.',
      'Add tomatoes and chickpeas and simmer 12 minutes.',
      'Stir in the spinach until wilted, then remove from heat and swirl in the yogurt.',
      'Serve the masala over the warm millet.',
    ],
    superAgeNote: 'Chickpeas over millet make this creamy curry a legume-and-whole-grain plate rich in fiber, the high-quality carbohydrate pattern the JAMA aging study linked to healthier outcomes.',
    nutrition: { cal: 500, protein: 22, fiber: 16 },
    airfryer: [
      'Before simmering, air-fry the drained chickpeas at 400F (205C) for 12 minutes until crisp.',
      'Add them to the sauce in the last few minutes so they stay slightly firm.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-broccoli-chickpea-stir-fry-quinoa',
    name: 'Broccoli and Chickpea Stir-Fry over Quinoa',
    emoji: '🥦',
    category: 'dinner',
    time: '35 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 large head', item: 'broccoli, cut into florets' },
      { qty: '3 tbsp', item: 'tamari' },
      { qty: '1 tbsp', item: 'grated ginger' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'sesame oil' },
      { qty: '1 tsp', item: 'maple syrup' },
    ],
    steps: [
      'Cook quinoa in 2 cups water until fluffy, about 15 minutes.',
      'Heat sesame oil in a wok and stir-fry the broccoli until bright green and crisp-tender.',
      'Add chickpeas, ginger, and garlic and stir-fry 3 more minutes.',
      'Pour in the tamari and maple syrup and toss to glaze.',
      'Serve over the warm quinoa.',
    ],
    superAgeNote: 'Broccoli, chickpeas, and quinoa together load this stir-fry with fiber and keep it in the low carb-to-fiber range the SuperAge article ties to healthier aging.',
    nutrition: { cal: 450, protein: 19, fiber: 15 },
    airfryer: [
      'Toss broccoli and chickpeas with the sesame oil and air-fry at 390F (199C) for 12 minutes, shaking once.',
      'Toss with the tamari-ginger glaze off the heat, then serve over quinoa.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lentil-carrot-shepherds-pie-barley-topping',
    name: 'Lentil-Carrot Shepherd\'s Pie with Barley Topping',
    emoji: '🥧',
    category: 'dinner',
    time: '55 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'dried green lentils' },
      { qty: '1 cup', item: 'pearl barley' },
      { qty: '3', item: 'carrots, diced' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '2 tbsp', item: 'tomato paste' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'dried rosemary' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook the barley in salted water until tender, about 30 minutes, then drain and toss with 1 tbsp olive oil.',
      'Simmer lentils in the broth with tomato paste until tender, about 25 minutes.',
      'Saute onion and carrots in the remaining oil, stir into the lentils with rosemary, and season well.',
      'Spread the lentil filling in a baking dish and blanket it with the cooked barley.',
      'Bake at 400F (205C) for 20 minutes until the barley topping crisps. Rest 5 minutes.',
    ],
    superAgeNote: 'A chewy barley crust over a lentil-carrot base makes this pie a double dose of the whole-grain and legume fiber the JAMA aging study connected to healthier aging.',
    nutrition: { cal: 500, protein: 22, fiber: 20 },
    airfryer: [
      'Assemble the pie in an air-fryer-safe dish.',
      'Air-fry at 390F (199C) for 12 minutes until the barley topping turns golden and crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-black-bean-quinoa-chili-kale',
    name: 'Black Bean and Quinoa Chili with Kale',
    emoji: '🌶️',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '0.75 cup', item: 'quinoa, rinsed' },
      { qty: '2 cans (15 oz each)', item: 'black beans, drained and rinsed' },
      { qty: '4 cups', item: 'kale, stemmed and chopped' },
      { qty: '1 can (28 oz)', item: 'crushed tomatoes' },
      { qty: '2 tbsp', item: 'chili powder' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '3 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Saute onion in olive oil until soft, then stir in chili powder and cumin.',
      'Add crushed tomatoes, black beans, quinoa, and broth; bring to a simmer.',
      'Cook 20 minutes, stirring now and then, until the quinoa is tender and the chili thickens.',
      'Stir in the kale and simmer 5 more minutes until wilted.',
      'Season to taste and serve hot.',
    ],
    superAgeNote: 'Cooking quinoa right into the pot with black beans and kale builds a chili packed with the fiber-rich, high-quality carbohydrate the SuperAge article highlights.',
    nutrition: { cal: 440, protein: 20, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-roasted-carrot-tagine-millet',
    name: 'Chickpea and Roasted Carrot Tagine over Millet',
    emoji: '🍲',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'millet' },
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '4', item: 'carrots, cut into chunks' },
      { qty: '1 can (14 oz)', item: 'diced tomatoes' },
      { qty: '2 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'ground cinnamon' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '2 tbsp', item: 'chopped dried apricots' },
    ],
    steps: [
      'Simmer millet in 2 cups water until fluffy, about 20 minutes.',
      'Roast the carrots with 1 tbsp oil at 425F (220C) for 25 minutes until caramelized.',
      'Saute onion in the remaining oil, then add cumin, cinnamon, tomatoes, chickpeas, and apricots; simmer 15 minutes.',
      'Fold the roasted carrots into the tagine.',
      'Spoon the tagine over the warm millet.',
    ],
    superAgeNote: 'Chickpeas and millet anchor this warmly spiced tagine in the legume-and-whole-grain fiber the JAMA study associated with healthier aging.',
    nutrition: { cal: 490, protein: 18, fiber: 16 },
    airfryer: [
      'Air-fry the carrot chunks at 400F (205C) for 16 to 18 minutes until deeply caramelized, then fold into the tagine.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lentil-spinach-dal-barley',
    name: 'Lentil and Spinach Dal with Barley',
    emoji: '🍲',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'red lentils, rinsed' },
      { qty: '1 cup', item: 'pearl barley' },
      { qty: '5 cups', item: 'fresh spinach' },
      { qty: '1 tbsp', item: 'grated ginger' },
      { qty: '2 tsp', item: 'ground turmeric' },
      { qty: '2 tsp', item: 'ground cumin' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook barley in salted water until tender, about 30 minutes, then drain.',
      'Saute onion, ginger, turmeric, and cumin in olive oil until fragrant.',
      'Add the lentils and broth and simmer 20 minutes until the lentils break down into a soft dal.',
      'Stir in the spinach until wilted and season with salt.',
      'Serve the dal over or alongside the warm barley.',
    ],
    superAgeNote: 'Red lentils and barley together deliver soluble and insoluble fiber, keeping this dal well under the 10:1 carb-to-fiber ratio the SuperAge article recommends.',
    nutrition: { cal: 470, protein: 21, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-broccoli-carrot-black-bean-stir-fry-quinoa',
    name: 'Broccoli, Carrot and Black Bean Stir-Fry over Quinoa',
    emoji: '🥦',
    category: 'dinner',
    time: '35 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '1 head', item: 'broccoli, cut into florets' },
      { qty: '3', item: 'carrots, thinly sliced' },
      { qty: '3 tbsp', item: 'tamari' },
      { qty: '1 tbsp', item: 'grated ginger' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'sesame oil' },
    ],
    steps: [
      'Cook quinoa in 2 cups water until fluffy, about 15 minutes.',
      'Heat sesame oil and stir-fry the carrots and broccoli until crisp-tender.',
      'Add garlic, ginger, and black beans and stir-fry 3 more minutes.',
      'Pour in the tamari and toss to coat.',
      'Serve the stir-fry over the warm quinoa.',
    ],
    superAgeNote: 'Broccoli, carrots, and black beans over quinoa stack vegetable and legume fiber onto a whole grain, matching the high-quality carbohydrate pattern in the JAMA aging study.',
    nutrition: { cal: 440, protein: 18, fiber: 16 },
    airfryer: [
      'Air-fry the broccoli and carrots at 390F (199C) for 12 minutes, shaking once, until charred at the edges.',
      'Toss with the black beans and tamari, then serve over quinoa.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-millet-stuffed-kale-rolls-chickpea-marinara',
    name: 'Millet-Stuffed Kale Rolls with Chickpea Marinara',
    emoji: '🥬',
    category: 'dinner',
    time: '55 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '12 large', item: 'kale leaves, stems trimmed' },
      { qty: '1 cup', item: 'millet' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 jar (24 oz)', item: 'marinara sauce' },
      { qty: '1 tsp', item: 'dried basil' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Simmer millet in the broth until fluffy, about 20 minutes, then stir in the basil.',
      'Blanch the kale leaves in boiling water for 30 seconds to soften, then pat dry.',
      'Warm the marinara with the garlic and mashed chickpeas to make a chunky sauce.',
      'Spoon millet onto each kale leaf, roll up, and nestle seam-down in a baking dish.',
      'Cover the rolls with the chickpea marinara and bake at 375F (190C) for 25 minutes.',
    ],
    superAgeNote: 'Millet wrapped in kale and blanketed with chickpea marinara turns three longevity foods into one plate that is rich in fiber and low in refined carbs.',
    nutrition: { cal: 450, protein: 18, fiber: 15 },
    airfryer: [
      'Arrange the sauced rolls in an air-fryer-safe dish.',
      'Air-fry at 370F (188C) for 12 to 14 minutes until the tops are bubbling and lightly browned.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-vegetable-paella-barley',
    name: 'Chickpea and Vegetable Paella-Style Barley',
    emoji: '🥘',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'pearl barley' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1', item: 'red bell pepper, sliced' },
      { qty: '1 cup', item: 'frozen peas' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 pinch', item: 'saffron or 0.5 tsp turmeric' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '3.5 cups', item: 'vegetable broth' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Saute onion and bell pepper in olive oil until soft.',
      'Stir in the barley, smoked paprika, and saffron and toast for 2 minutes.',
      'Add the broth and chickpeas, bring to a simmer, then cook uncovered 30 minutes until the barley is tender.',
      'Scatter the peas over the top and cook 5 more minutes without stirring to build a light crust.',
      'Rest 5 minutes, then serve from the pan.',
    ],
    superAgeNote: 'Barley stands in for white rice here, so this paella keeps the chickpea-and-whole-grain fiber the SuperAge article ties to high-quality, longevity-friendly carbohydrates.',
    nutrition: { cal: 480, protein: 18, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-black-bean-broccoli-quinoa-bake',
    name: 'Black Bean and Broccoli Quinoa Bake',
    emoji: '🍲',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '1 head', item: 'broccoli, chopped small' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 cup', item: 'salsa verde' },
      { qty: '1 cup', item: 'shredded Monterey Jack' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook quinoa in the broth until fluffy, about 15 minutes.',
      'Toss the quinoa with black beans, broccoli, salsa verde, cumin, and half the cheese.',
      'Spread the mixture into an oiled baking dish and top with the remaining cheese.',
      'Bake at 400F (205C) for 25 minutes until the broccoli is tender and the top browns.',
      'Rest 5 minutes before serving.',
    ],
    superAgeNote: 'This baked casserole keeps quinoa, black beans, and broccoli front and center, all fiber-rich, high-quality carbs the JAMA aging study linked to healthier aging.',
    nutrition: { cal: 490, protein: 23, fiber: 15 },
    airfryer: [
      'Assemble in an air-fryer-safe dish.',
      'Air-fry at 380F (193C) for 12 to 15 minutes until the cheese top is golden and bubbling.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lentil-carrot-kale-soup-whole-grain-bread',
    name: 'Lentil, Carrot and Kale Soup with Whole-Grain Bread',
    emoji: '🍲',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'dried green lentils' },
      { qty: '3', item: 'carrots, diced' },
      { qty: '4 cups', item: 'kale, stemmed and chopped' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 tsp', item: 'dried thyme' },
      { qty: '6 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '4 slices', item: 'whole-grain bread' },
    ],
    steps: [
      'Saute onion, carrots, and garlic in olive oil until softened.',
      'Add the lentils, thyme, and broth and simmer 25 minutes until the lentils are tender.',
      'Stir in the kale and cook 5 more minutes until wilted.',
      'Season to taste with salt and pepper.',
      'Serve the soup with slices of whole-grain bread for dipping.',
    ],
    superAgeNote: 'Green lentils, kale, and a slice of whole-grain bread make this bowl a deeply fibrous meal built entirely on the high-quality carbohydrates the SuperAge article favors.',
    nutrition: { cal: 460, protein: 22, fiber: 19 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-spinach-coconut-curry-millet',
    name: 'Chickpea and Spinach Coconut Curry over Millet',
    emoji: '🍛',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'millet' },
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '5 cups', item: 'fresh spinach' },
      { qty: '1 can (14 oz)', item: 'light coconut milk' },
      { qty: '2 tbsp', item: 'curry powder' },
      { qty: '1 tbsp', item: 'grated ginger' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Simmer millet in 2 cups water until fluffy, about 20 minutes.',
      'Saute onion and ginger in olive oil, then stir in the curry powder.',
      'Add coconut milk and chickpeas and simmer 12 minutes until the sauce thickens.',
      'Stir in the spinach until wilted and season with salt.',
      'Spoon the curry over the warm millet.',
    ],
    superAgeNote: 'Chickpeas and millet keep this creamy coconut curry rich in legume and whole-grain fiber, the low carb-to-fiber pattern the JAMA study connected to healthier aging.',
    nutrition: { cal: 500, protein: 19, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-barley-risotto-roasted-broccoli-chickpeas',
    name: 'Barley Risotto with Roasted Broccoli and Chickpeas',
    emoji: '🍚',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'pearl barley' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 head', item: 'broccoli, cut into florets' },
      { qty: '5 cups', item: 'vegetable broth, kept warm' },
      { qty: '0.5 cup', item: 'grated Parmesan' },
      { qty: '1', item: 'onion, finely chopped' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1', item: 'lemon, zested' },
    ],
    steps: [
      'Roast the broccoli and chickpeas with 1 tbsp oil at 425F (220C) for 25 minutes.',
      'Saute onion in the remaining oil, then add the barley and toast for 2 minutes.',
      'Add the warm broth a ladle at a time, stirring, until the barley is creamy and tender, about 35 minutes.',
      'Stir in the Parmesan and lemon zest.',
      'Fold in the roasted broccoli and chickpeas and serve.',
    ],
    superAgeNote: 'Barley makes a naturally creamy risotto with far more fiber than arborio rice, and the roasted broccoli and chickpeas add the vegetable and legume carbs the SuperAge article highlights.',
    nutrition: { cal: 500, protein: 20, fiber: 17 },
    airfryer: [
      'Air-fry the broccoli and chickpeas at 400F (205C) for 15 minutes, shaking halfway, until crisp.',
      'Fold them into the finished risotto just before serving.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-black-bean-quinoa-stuffed-poblano-kale',
    name: 'Black Bean and Quinoa Stuffed Poblano Peppers with Kale',
    emoji: '🌶️',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '4 large', item: 'poblano peppers, halved and seeded' },
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '3 cups', item: 'kale, stemmed and chopped' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 cup', item: 'shredded pepper Jack' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook quinoa in the broth until fluffy, about 15 minutes.',
      'Saute the kale in olive oil until wilted, then stir it into the quinoa with the black beans and cumin.',
      'Pack the poblano halves with the filling and place them in a baking dish.',
      'Top with the shredded cheese.',
      'Bake at 400F (205C) for 25 minutes until the peppers soften and the cheese browns.',
    ],
    superAgeNote: 'Quinoa, black beans, and kale packed into poblanos make a plate dense in the fiber-rich, high-quality carbohydrate the JAMA aging study associated with healthier aging.',
    nutrition: { cal: 470, protein: 22, fiber: 15 },
    airfryer: [
      'Place stuffed poblano halves in an air-fryer-safe dish.',
      'Air-fry at 370F (188C) for 14 to 16 minutes until the peppers are tender and the cheese is bubbling.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-millet-chickpea-buddha-bowl-roasted-carrots',
    name: 'Millet and Chickpea Buddha Bowl with Roasted Carrots',
    emoji: '🥗',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'millet' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '4', item: 'carrots, cut into sticks' },
      { qty: '3 cups', item: 'baby spinach' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '1', item: 'lemon, juiced' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'ground cumin' },
    ],
    steps: [
      'Simmer millet in 2 cups water until fluffy, about 20 minutes.',
      'Toss the carrots and chickpeas with 1 tbsp oil and cumin and roast at 425F (220C) for 25 minutes.',
      'Whisk the tahini, lemon juice, remaining oil, and a splash of water into a pourable dressing.',
      'Divide the millet and spinach among bowls and top with the roasted carrots and chickpeas.',
      'Drizzle everything with the tahini dressing.',
    ],
    superAgeNote: 'This bowl layers millet, chickpeas, carrots, and spinach, hitting several of the SuperAge star foods at once for a naturally high-fiber, low carb-to-fiber meal.',
    nutrition: { cal: 480, protein: 18, fiber: 15 },
    airfryer: [
      'Air-fry the carrots and chickpeas at 400F (205C) for 16 minutes, shaking halfway, until caramelized and crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-kale-black-bean-enchilada-bake-quinoa',
    name: 'Kale and Black Bean Enchilada Bake with Quinoa',
    emoji: '🌮',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '2 cans (15 oz each)', item: 'black beans, drained and rinsed' },
      { qty: '4 cups', item: 'kale, stemmed and chopped' },
      { qty: '2 cups', item: 'red enchilada sauce' },
      { qty: '1 cup', item: 'shredded cheddar' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook quinoa in the broth until fluffy, about 15 minutes.',
      'Saute the kale in olive oil until wilted.',
      'Mix the quinoa, kale, black beans, cumin, and half the enchilada sauce, then spread into a baking dish.',
      'Pour the remaining sauce over the top and scatter with cheese.',
      'Bake at 400F (205C) for 25 minutes until bubbling and browned.',
    ],
    superAgeNote: 'Quinoa and black beans replace tortillas here, keeping this enchilada bake grounded in the whole-grain and legume fiber the JAMA study linked to healthier aging.',
    nutrition: { cal: 490, protein: 24, fiber: 17 },
    airfryer: [
      'Assemble in an air-fryer-safe dish.',
      'Air-fry at 380F (193C) for 12 to 14 minutes until the cheese top melts and crisps.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-broccoli-grain-bowl-peanut-barley',
    name: 'Chickpea and Broccoli Grain Bowl with Peanut Sauce and Barley',
    emoji: '🥜',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'pearl barley' },
      { qty: '1 can (15 oz)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 head', item: 'broccoli, cut into florets' },
      { qty: '3 tbsp', item: 'natural peanut butter' },
      { qty: '2 tbsp', item: 'tamari' },
      { qty: '1 tbsp', item: 'grated ginger' },
      { qty: '1', item: 'lime, juiced' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook the barley in salted water until tender, about 30 minutes, then drain.',
      'Roast the broccoli and chickpeas with the olive oil at 425F (220C) for 25 minutes.',
      'Whisk the peanut butter, tamari, ginger, lime juice, and a splash of water into a smooth sauce.',
      'Divide the barley among bowls and top with the roasted broccoli and chickpeas.',
      'Drizzle generously with the peanut sauce.',
    ],
    superAgeNote: 'Barley plus chickpeas and broccoli make a bowl heavy in whole-grain and legume fiber, the high-quality carbohydrate the SuperAge article ties to healthier aging.',
    nutrition: { cal: 520, protein: 20, fiber: 17 },
    airfryer: [
      'Air-fry the broccoli and chickpeas at 400F (205C) for 15 minutes, shaking halfway, until crisp.',
      'Pile over barley and finish with the peanut sauce.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lentil-carrot-curry-spinach-millet',
    name: 'Lentil and Carrot Curry with Spinach over Millet',
    emoji: '🍛',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'millet' },
      { qty: '1.5 cups', item: 'red lentils, rinsed' },
      { qty: '3', item: 'carrots, diced' },
      { qty: '4 cups', item: 'fresh spinach' },
      { qty: '2 tbsp', item: 'curry powder' },
      { qty: '1 can (14 oz)', item: 'diced tomatoes' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Simmer millet in 2 cups water until fluffy, about 20 minutes.',
      'Saute onion and carrots in olive oil, then stir in the curry powder.',
      'Add the lentils, tomatoes, and broth and simmer 20 minutes until the lentils are soft.',
      'Stir in the spinach until wilted and season with salt.',
      'Serve the curry over the warm millet.',
    ],
    superAgeNote: 'Red lentils, carrots, and spinach over millet keep this curry rich in the fiber-forward, high-quality carbohydrates the JAMA aging study favored.',
    nutrition: { cal: 480, protein: 21, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-black-bean-quinoa-skillet-roasted-broccoli',
    name: 'Black Bean and Quinoa Skillet with Roasted Broccoli',
    emoji: '🍳',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '1 head', item: 'broccoli, cut into florets' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1', item: 'lime, juiced' },
    ],
    steps: [
      'Roast the broccoli with 1 tbsp oil at 425F (220C) for 20 minutes until charred.',
      'Cook quinoa in the broth until fluffy, about 15 minutes.',
      'In a skillet, saute garlic in the remaining oil, then add black beans, smoked paprika, and cumin.',
      'Fold in the quinoa and roasted broccoli and heat through.',
      'Finish with lime juice and season to taste.',
    ],
    superAgeNote: 'Quinoa and black beans with roasted broccoli give this quick skillet the low carb-to-fiber ratio and whole-food carbs the SuperAge article recommends.',
    nutrition: { cal: 450, protein: 19, fiber: 16 },
    airfryer: [
      'Air-fry the broccoli at 400F (205C) for 12 minutes until crisp, then fold into the skillet.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-kale-barley-stew',
    name: 'Chickpea, Kale and Barley Stew',
    emoji: '🍲',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'pearl barley' },
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '5 cups', item: 'kale, stemmed and chopped' },
      { qty: '2', item: 'carrots, diced' },
      { qty: '1 can (14 oz)', item: 'diced tomatoes' },
      { qty: '1', item: 'onion, chopped' },
      { qty: '2 tsp', item: 'dried rosemary' },
      { qty: '6 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Saute onion and carrots in olive oil until softened.',
      'Add the barley, chickpeas, tomatoes, rosemary, and broth and bring to a simmer.',
      'Cook 35 minutes until the barley is tender and the stew has thickened.',
      'Stir in the kale and simmer 5 more minutes until wilted.',
      'Season well and serve hot.',
    ],
    superAgeNote: 'Barley, chickpeas, and kale simmered together create a hearty stew that is dense in the whole-grain and legume fiber the JAMA study linked to healthier aging.',
    nutrition: { cal: 470, protein: 20, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-millet-stuffed-peppers-black-beans-carrots',
    name: 'Millet-Stuffed Bell Peppers with Black Beans and Carrots',
    emoji: '🫑',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '4', item: 'bell peppers, tops removed and seeded' },
      { qty: '1 cup', item: 'millet' },
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '2', item: 'carrots, finely diced' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'chili powder' },
      { qty: '1 cup', item: 'salsa' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Simmer millet in the broth until fluffy, about 20 minutes.',
      'Saute the carrots in olive oil until softened, then stir into the millet with the black beans, cumin, chili powder, and half the salsa.',
      'Pack the bell peppers with the millet filling.',
      'Stand the peppers in a baking dish and top with the remaining salsa.',
      'Cover with foil and bake at 375F (190C) for 30 minutes, uncovering the last 10 to brown the tops.',
    ],
    superAgeNote: 'Millet and black beans stuffed into sweet peppers deliver 3g-plus of fiber per serving from real whole grains and legumes, the pattern the SuperAge article ties to healthier aging.',
    nutrition: { cal: 450, protein: 18, fiber: 15 },
    airfryer: [
      'Stand the stuffed peppers in an air-fryer-safe dish.',
      'Air-fry at 360F (182C) for 15 to 18 minutes until the peppers are tender and the tops char lightly.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lentil-broccoli-shepherds-pie-quinoa-carrot',
    name: 'Lentil and Broccoli Shepherd\'s Pie with Quinoa-Carrot Topping',
    emoji: '🥧',
    category: 'dinner',
    time: '55 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'dried green lentils' },
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '1 head', item: 'broccoli, chopped small' },
      { qty: '3', item: 'carrots, grated' },
      { qty: '2 tbsp', item: 'tomato paste' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'dried thyme' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook quinoa in 2 cups water until fluffy, about 15 minutes, then stir in the grated carrots and 1 tbsp oil.',
      'Simmer the lentils in the broth with tomato paste and thyme until tender, about 25 minutes.',
      'Steam the broccoli until just tender and fold it into the lentils; season well.',
      'Spread the lentil-broccoli filling in a baking dish and top with the quinoa-carrot mixture.',
      'Bake at 400F (205C) for 20 minutes until the topping crisps. Rest 5 minutes before serving.',
    ],
    superAgeNote: 'A quinoa-and-carrot crust over lentils and broccoli makes this pie a stack of longevity star foods, keeping it well under the 10:1 carb-to-fiber ratio the JAMA study highlighted.',
    nutrition: { cal: 480, protein: 23, fiber: 19 },
    airfryer: [
      'Assemble the pie in an air-fryer-safe dish.',
      'Air-fry at 390F (199C) for 12 minutes until the quinoa-carrot topping turns golden and crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
];

(function () {
  if (typeof KANDY_RECIPES !== 'undefined') KANDY_RECIPES.push(...SUPERAGE_DINNER);
  SUPERAGE_DINNER.forEach(function (r) {
    if (r.airfryer && typeof AIRFRYER !== 'undefined') AIRFRYER[r.id] = r.airfryer;
    if (r.nutrition && typeof RECIPE_NUTRITION !== 'undefined') RECIPE_NUTRITION[r.id] = r.nutrition;
  });
})();
