// SuperAge Longevity-Carb SNACKS
// Healthy, high-fiber snacks inspired by a 30-year study (JAMA Network Open)
// linking high-quality, fiber-rich carbohydrates to healthier aging.
// Stars: whole grains, fruits, vegetables, legumes, nuts and seeds.

const SUPERAGE_SNACKS = [
  {
    id: 'sa-sn-apple-almond-butter',
    name: 'Apple Slices with Almond Butter',
    emoji: '🍎',
    category: 'snack',
    time: '5 min',
    serves: 1,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1', item: 'apple, cored and sliced' },
      { qty: '2 tbsp', item: 'almond butter' },
      { qty: '1 pinch', item: 'ground cinnamon' },
    ],
    steps: [
      'Core the apple and slice it into thin wedges.',
      'Spread or dollop the almond butter for dipping.',
      'Dust with cinnamon and serve right away.',
    ],
    superAgeNote: 'A whole apple keeps its skin-and-pulp fiber intact, and pairing it with almond butter adds protein and healthy fats for a slow, steady snack that reflects the study emphasis on fiber-rich fruit.',
    nutrition: { cal: 265, protein: 7, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-orange-walnuts',
    name: 'Orange Segments with Walnuts',
    emoji: '🍊',
    category: 'snack',
    time: '5 min',
    serves: 1,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1', item: 'orange, peeled and segmented' },
      { qty: '2 tbsp', item: 'walnut halves' },
    ],
    steps: [
      'Peel the orange and separate it into segments.',
      'Arrange the segments on a plate with the walnuts alongside.',
      'Eat the whole segments rather than juicing to keep the fiber.',
    ],
    superAgeNote: 'Whole oranges deliver fiber and vitamin C that juice loses, and the walnuts add omega-3 fats, matching the study focus on fiber-rich whole fruit for healthier aging.',
    nutrition: { cal: 195, protein: 5, fiber: 5 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-berry-chia-pudding',
    name: 'Berry and Chia Pudding Cup',
    emoji: '🫐',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '3 tbsp', item: 'chia seeds' },
      { qty: '1 cup', item: 'unsweetened almond milk' },
      { qty: '1 cup', item: 'mixed berries' },
      { qty: '1 tsp', item: 'maple syrup' },
      { qty: '1/2 tsp', item: 'vanilla extract' },
    ],
    steps: [
      'Whisk the chia seeds, almond milk, maple syrup and vanilla in a jar.',
      'Rest 5 minutes, whisk again to break up clumps, then chill until thickened.',
      'Spoon into two cups and top with the mixed berries.',
    ],
    superAgeNote: 'Chia seeds and berries stack up soluble fiber for a very low carb-to-fiber ratio, echoing the study link between fiber-rich carbohydrates and healthier aging.',
    nutrition: { cal: 175, protein: 5, fiber: 11 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-popcorn-nutritional-yeast',
    name: 'Air-Popped Popcorn with Nutritional Yeast',
    emoji: '🍿',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1/3 cup', item: 'popcorn kernels' },
      { qty: '2 tbsp', item: 'nutritional yeast' },
      { qty: '1 tsp', item: 'olive oil' },
      { qty: '1/4 tsp', item: 'fine salt' },
    ],
    steps: [
      'Air-pop the popcorn kernels into a large bowl.',
      'Drizzle with the olive oil and toss so the seasoning sticks.',
      'Sprinkle the nutritional yeast and salt, tossing to coat evenly.',
    ],
    superAgeNote: 'Popcorn is a whole grain, so a big bowl brings real fiber for very few calories, fitting the study preference for minimally processed, fiber-rich carbs.',
    nutrition: { cal: 160, protein: 6, fiber: 5 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-roasted-chickpeas',
    name: 'Roasted Chickpeas',
    emoji: '🫛',
    category: 'snack',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 can', item: 'chickpeas, drained and rinsed' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1/2 tsp', item: 'ground cumin' },
      { qty: '1/2 tsp', item: 'smoked paprika' },
      { qty: '1/4 tsp', item: 'salt' },
    ],
    steps: [
      'Pat the chickpeas very dry and toss with the oil, cumin, paprika and salt.',
      'Spread on a lined tray and roast at 400F (200C) for 30 to 35 minutes, shaking twice.',
      'Cool for a few minutes so they crisp up before serving.',
    ],
    superAgeNote: 'Chickpeas are a legume high in fiber and plant protein, one of the study star foods for turning a crunchy snack into a longevity-friendly carb.',
    nutrition: { cal: 180, protein: 8, fiber: 7 },
    airfryer: [
      'Toss the seasoned chickpeas in the basket in a single layer.',
      'Air fry at 390F (200C) for 15 to 18 minutes, shaking every 5 minutes, until crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-carrot-sticks-hummus',
    name: 'Carrot Sticks with Hummus',
    emoji: '🥕',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '3', item: 'carrots, cut into sticks' },
      { qty: '1/2 cup', item: 'hummus' },
      { qty: '1 pinch', item: 'smoked paprika for garnish' },
    ],
    steps: [
      'Peel and cut the carrots into sturdy dipping sticks.',
      'Spoon the hummus into a small bowl and dust with paprika.',
      'Serve the carrots alongside for dipping.',
    ],
    superAgeNote: 'Carrots bring vegetable fiber and beta-carotene while chickpea hummus adds legume fiber and protein, a double dose of the study star foods.',
    nutrition: { cal: 210, protein: 7, fiber: 8 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-broccoli-lemon-tahini',
    name: 'Broccoli Florets with Lemon-Tahini Dip',
    emoji: '🥦',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2 cups', item: 'broccoli florets' },
      { qty: '3 tbsp', item: 'tahini' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '2 tbsp', item: 'water' },
      { qty: '1 pinch', item: 'salt' },
    ],
    steps: [
      'Cut the broccoli into bite-size florets for dipping.',
      'Whisk the tahini, lemon juice, water and salt until smooth and pourable.',
      'Serve the raw florets with the lemon-tahini dip.',
    ],
    superAgeNote: 'Broccoli is a high-fiber cruciferous vegetable, and the sesame tahini adds minerals, keeping this snack squarely in the study fiber-rich vegetable category.',
    nutrition: { cal: 220, protein: 8, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-berries-greek-yogurt',
    name: 'Mixed Berries with Greek Yogurt',
    emoji: '🍓',
    category: 'snack',
    time: '5 min',
    serves: 1,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '3/4 cup', item: 'plain Greek yogurt' },
      { qty: '1 cup', item: 'mixed berries' },
      { qty: '1 tbsp', item: 'ground flaxseed' },
    ],
    steps: [
      'Spoon the Greek yogurt into a bowl.',
      'Top with the mixed berries.',
      'Sprinkle the flaxseed over the top and serve.',
    ],
    superAgeNote: 'Berries are among the most fiber-dense fruits, and the flaxseed lowers the carb-to-fiber ratio further while the yogurt adds protein, in line with the study on fiber-rich carbs.',
    nutrition: { cal: 210, protein: 18, fiber: 7 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-apple-oat-cookie-bites',
    name: 'Apple-Oat Cookie Bites',
    emoji: '🍪',
    category: 'snack',
    time: '25 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan'],
    ingredients: [
      { qty: '1.5 cups', item: 'rolled oats' },
      { qty: '1', item: 'apple, grated' },
      { qty: '1', item: 'ripe banana, mashed' },
      { qty: '1/4 cup', item: 'chopped walnuts' },
      { qty: '1 tsp', item: 'ground cinnamon' },
    ],
    steps: [
      'Mix the oats, grated apple, mashed banana, walnuts and cinnamon into a stiff dough.',
      'Scoop small mounds onto a lined tray and flatten slightly.',
      'Bake at 350F (175C) for 15 minutes until set and golden at the edges.',
    ],
    superAgeNote: 'Rolled oats and apple bring beta-glucan and fruit fiber together in a naturally sweetened bite, reflecting the study preference for whole-grain, fiber-rich carbs.',
    nutrition: { cal: 150, protein: 4, fiber: 4 },
    airfryer: [
      'Place the flattened bites on parchment in the basket, spaced apart.',
      'Air fry at 330F (165C) for 9 to 11 minutes until firm and lightly browned.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-orange-almond-energy-balls',
    name: 'Orange-Almond Energy Balls',
    emoji: '🍊',
    category: 'snack',
    time: '15 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1 cup', item: 'rolled oats' },
      { qty: '1/2 cup', item: 'almond butter' },
      { qty: '1/4 cup', item: 'ground almonds' },
      { qty: '1 tbsp', item: 'orange zest' },
      { qty: '2 tbsp', item: 'maple syrup' },
    ],
    steps: [
      'Stir the oats, almond butter, ground almonds, orange zest and maple syrup into a sticky dough.',
      'Roll into small balls with damp hands.',
      'Chill for at least 20 minutes to firm up before serving.',
    ],
    superAgeNote: 'These no-bake balls combine whole-grain oats with almonds and bright orange zest, delivering fiber and healthy fats that fit the study longevity-carb pattern.',
    nutrition: { cal: 185, protein: 6, fiber: 4 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-black-bean-brownie-bites',
    name: 'Black Bean Brownie Bites',
    emoji: '🍫',
    category: 'snack',
    time: '30 min',
    serves: 8,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 can', item: 'black beans, drained and rinsed' },
      { qty: '1/3 cup', item: 'cocoa powder' },
      { qty: '1/3 cup', item: 'maple syrup' },
      { qty: '1/4 cup', item: 'rolled oats' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'vanilla extract' },
    ],
    steps: [
      'Blend the black beans, cocoa, maple syrup, oats, oil and vanilla into a smooth batter.',
      'Spoon into a lined mini-muffin tin.',
      'Bake at 350F (175C) for 18 to 20 minutes, then cool before lifting out.',
    ],
    superAgeNote: 'Black beans are a fiber-rich legume that gives these fudgy bites real staying power, one of the study star foods hidden inside a treat.',
    nutrition: { cal: 120, protein: 4, fiber: 5 },
    airfryer: [
      'Use silicone mini-muffin cups that fit the basket.',
      'Air fry at 330F (165C) for 12 to 14 minutes until the tops are set.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-popcorn-berry-trail-mix',
    name: 'Popcorn and Dried Berry Trail Mix',
    emoji: '🍿',
    category: 'snack',
    time: '10 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '4 cups', item: 'air-popped popcorn' },
      { qty: '1/3 cup', item: 'unsweetened dried blueberries' },
      { qty: '1/3 cup', item: 'almonds' },
      { qty: '2 tbsp', item: 'pumpkin seeds' },
    ],
    steps: [
      'Add the cooled popcorn to a large bowl.',
      'Scatter in the dried blueberries, almonds and pumpkin seeds.',
      'Toss gently and portion into snack bags or cups.',
    ],
    superAgeNote: 'Whole-grain popcorn plus dried berries and seeds makes a crunchy mix with more fiber and less sugar than candy-based trail mix, matching the study carb-quality message.',
    nutrition: { cal: 190, protein: 6, fiber: 5 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-quinoa-berry-energy-bites',
    name: 'Quinoa and Berry Energy Bites',
    emoji: '🫐',
    category: 'snack',
    time: '15 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa, cooled' },
      { qty: '3/4 cup', item: 'rolled oats' },
      { qty: '1/3 cup', item: 'almond butter' },
      { qty: '1/3 cup', item: 'unsweetened dried berries' },
      { qty: '2 tbsp', item: 'maple syrup' },
    ],
    steps: [
      'Combine the cooled quinoa, oats, almond butter, dried berries and maple syrup.',
      'Press and roll the mix into firm bite-size balls.',
      'Chill 20 minutes so they hold their shape before serving.',
    ],
    superAgeNote: 'Quinoa and oats are two whole grains that team with berries here for a fiber-rich, protein-boosted bite in the spirit of the study longevity carbs.',
    nutrition: { cal: 175, protein: 6, fiber: 4 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-roasted-carrot-chips',
    name: 'Roasted Carrot Chips',
    emoji: '🥕',
    category: 'snack',
    time: '35 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '4', item: 'carrots, thinly sliced into coins' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1/2 tsp', item: 'garlic powder' },
      { qty: '1/4 tsp', item: 'salt' },
    ],
    steps: [
      'Slice the carrots into thin, even coins and toss with the oil, garlic powder and salt.',
      'Spread in a single layer on a lined tray.',
      'Roast at 375F (190C) for 20 to 25 minutes, flipping once, until crisp at the edges.',
    ],
    superAgeNote: 'Turning carrots into chips keeps their vegetable fiber while satisfying a crunchy craving, one of the study fiber-rich vegetables done a new way.',
    nutrition: { cal: 130, protein: 2, fiber: 5 },
    airfryer: [
      'Arrange the carrot coins in a single layer, working in batches if needed.',
      'Air fry at 360F (180C) for 12 to 15 minutes, shaking twice, until crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-baked-kale-chips',
    name: 'Baked Kale Chips',
    emoji: '🥬',
    category: 'snack',
    time: '20 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 bunch', item: 'kale, stems removed and torn' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1/4 tsp', item: 'salt' },
      { qty: '1 tbsp', item: 'nutritional yeast' },
    ],
    steps: [
      'Dry the kale thoroughly and massage with the olive oil and salt.',
      'Spread in a single layer and sprinkle with nutritional yeast.',
      'Bake at 300F (150C) for 12 to 15 minutes until crisp but still green.',
    ],
    superAgeNote: 'Kale is a leafy green loaded with fiber and vitamin K, and baking it into chips keeps this study star vegetable front and center.',
    nutrition: { cal: 110, protein: 4, fiber: 4 },
    airfryer: [
      'Add the dressed kale loosely to the basket without packing it.',
      'Air fry at 300F (150C) for 5 to 7 minutes, tossing once, until crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-apple-cinnamon-walnut-butter',
    name: 'Apple Slices with Cinnamon Walnut Butter',
    emoji: '🍎',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2', item: 'apples, sliced' },
      { qty: '1 cup', item: 'walnuts' },
      { qty: '1 tsp', item: 'ground cinnamon' },
      { qty: '1 tsp', item: 'maple syrup' },
    ],
    steps: [
      'Blend the walnuts, cinnamon and maple syrup into a spreadable butter.',
      'Slice the apples into wedges.',
      'Serve the wedges with the cinnamon walnut butter for dipping.',
    ],
    superAgeNote: 'Whole apples carry the fiber the study highlights, and homemade walnut butter adds omega-3 fats without the added sugar of jarred spreads.',
    nutrition: { cal: 320, protein: 7, fiber: 7 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-chickpea-orange-salad-cup',
    name: 'Chickpea and Orange Salad Cup',
    emoji: '🥗',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1 can', item: 'chickpeas, drained and rinsed' },
      { qty: '1', item: 'orange, peeled and chopped' },
      { qty: '2 tbsp', item: 'chopped parsley' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1 tbsp', item: 'lemon juice' },
    ],
    steps: [
      'Combine the chickpeas, chopped orange and parsley in a bowl.',
      'Whisk the olive oil and lemon juice and pour over.',
      'Toss gently and spoon into cups to serve.',
    ],
    superAgeNote: 'Chickpeas and whole orange pieces pair a fiber-rich legume with fiber-rich fruit, a direct nod to two of the study star food groups.',
    nutrition: { cal: 240, protein: 9, fiber: 8 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-berry-oat-snack-bars',
    name: 'Berry-Oat Snack Bars',
    emoji: '🍓',
    category: 'snack',
    time: '35 min',
    serves: 8,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan'],
    ingredients: [
      { qty: '2 cups', item: 'rolled oats' },
      { qty: '2', item: 'ripe bananas, mashed' },
      { qty: '1 cup', item: 'mixed berries' },
      { qty: '1/4 cup', item: 'ground flaxseed' },
      { qty: '1/4 cup', item: 'chopped almonds' },
    ],
    steps: [
      'Mix the oats, mashed banana, flaxseed and almonds, then fold in the berries.',
      'Press firmly into a lined baking pan.',
      'Bake at 350F (175C) for 22 to 25 minutes, cool, then cut into bars.',
    ],
    superAgeNote: 'Oats, berries and flaxseed layer whole-grain and fruit fiber into a portable bar with a low carb-to-fiber ratio, right in line with the study.',
    nutrition: { cal: 175, protein: 5, fiber: 5 },
    airfryer: [
      'Bake the pressed mixture in a small air-fryer-safe pan.',
      'Air fry at 330F (165C) for 15 to 18 minutes until set, then cool before slicing.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-roasted-broccoli-parmesan',
    name: 'Roasted Broccoli Bites with Parmesan',
    emoji: '🥦',
    category: 'snack',
    time: '30 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '3 cups', item: 'broccoli florets' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '3 tbsp', item: 'grated parmesan' },
      { qty: '1/4 tsp', item: 'salt' },
      { qty: '1 pinch', item: 'black pepper' },
    ],
    steps: [
      'Toss the broccoli florets with the oil, salt and pepper.',
      'Spread on a tray and roast at 425F (220C) for 18 to 20 minutes until browned.',
      'Sprinkle with parmesan in the last 3 minutes so it melts and crisps.',
    ],
    superAgeNote: 'Broccoli is a fiber-rich cruciferous vegetable, and roasting deepens its flavor so this study star food eats like a treat.',
    nutrition: { cal: 165, protein: 9, fiber: 6 },
    airfryer: [
      'Add the oiled florets to the basket in a single layer.',
      'Air fry at 390F (200C) for 10 to 12 minutes, then top with parmesan and cook 2 more minutes.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-millet-berry-crisp-bites',
    name: 'Millet-Berry Crisp Bites',
    emoji: '🫐',
    category: 'snack',
    time: '30 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 cup', item: 'cooked millet, cooled' },
      { qty: '3/4 cup', item: 'rolled oats' },
      { qty: '1', item: 'ripe banana, mashed' },
      { qty: '3/4 cup', item: 'mixed berries' },
      { qty: '2 tbsp', item: 'almond butter' },
    ],
    steps: [
      'Stir the millet, oats, mashed banana and almond butter together, then fold in the berries.',
      'Scoop mounds onto a lined tray and press flat.',
      'Bake at 350F (175C) for 18 to 20 minutes until the edges are crisp.',
    ],
    superAgeNote: 'Millet and oats are whole grains, and pairing them with berries keeps these crisp bites high in fiber as the study on longevity carbs recommends.',
    nutrition: { cal: 160, protein: 4, fiber: 4 },
    airfryer: [
      'Place the flattened bites on parchment in the basket.',
      'Air fry at 330F (165C) for 11 to 13 minutes until crisp at the edges.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-carrot-apple-slaw-cup',
    name: 'Carrot and Apple Slaw Cup',
    emoji: '🥕',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2', item: 'carrots, grated' },
      { qty: '1', item: 'apple, grated' },
      { qty: '2 tbsp', item: 'raisins' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '1 tbsp', item: 'sunflower seeds' },
    ],
    steps: [
      'Grate the carrots and apple into a bowl.',
      'Toss with the raisins, lemon juice and sunflower seeds.',
      'Spoon into cups and serve chilled.',
    ],
    superAgeNote: 'This raw slaw pairs carrots and apple so vegetable and fruit fiber stay fully intact, exactly the minimally processed carbs the study favors.',
    nutrition: { cal: 155, protein: 3, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-popcorn-smoked-paprika',
    name: 'Popcorn with Smoked Paprika',
    emoji: '🍿',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1/3 cup', item: 'popcorn kernels' },
      { qty: '1 tsp', item: 'olive oil' },
      { qty: '3/4 tsp', item: 'smoked paprika' },
      { qty: '1/4 tsp', item: 'salt' },
    ],
    steps: [
      'Air-pop the popcorn kernels into a big bowl.',
      'Drizzle with the olive oil and toss to coat.',
      'Sprinkle the smoked paprika and salt, tossing until evenly seasoned.',
    ],
    superAgeNote: 'Popcorn is a whole grain, so this smoky bowl delivers fiber for very few calories, matching the study emphasis on minimally processed carbs.',
    nutrition: { cal: 150, protein: 4, fiber: 5 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-lentil-carrot-dip',
    name: 'Lentil and Carrot Dip with Veggie Sticks',
    emoji: '🥕',
    category: 'snack',
    time: '15 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1 cup', item: 'cooked red lentils, cooled' },
      { qty: '1', item: 'carrot, cooked and chopped' },
      { qty: '2 tbsp', item: 'tahini' },
      { qty: '1 tbsp', item: 'lemon juice' },
      { qty: '2 cups', item: 'assorted veggie sticks' },
    ],
    steps: [
      'Blend the lentils, carrot, tahini and lemon juice into a smooth dip.',
      'Season to taste and spoon into a bowl.',
      'Serve with the veggie sticks for dipping.',
    ],
    superAgeNote: 'Lentils are a fiber-and-protein-rich legume, and blended with carrot they make a dip built on two of the study star food groups.',
    nutrition: { cal: 175, protein: 8, fiber: 7 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-orange-dark-chocolate',
    name: 'Orange Slices with Dark Chocolate Shavings',
    emoji: '🍊',
    category: 'snack',
    time: '5 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2', item: 'oranges, peeled and sliced' },
      { qty: '2 tbsp', item: 'dark chocolate shavings' },
      { qty: '1 pinch', item: 'flaky sea salt' },
    ],
    steps: [
      'Peel and slice the oranges into rounds.',
      'Arrange on a plate and scatter the dark chocolate shavings over the top.',
      'Finish with a pinch of flaky salt and serve.',
    ],
    superAgeNote: 'Whole oranges provide fruit fiber and vitamin C, and a little dark chocolate satisfies a sweet craving without turning this into a low-quality carb, in keeping with the study.',
    nutrition: { cal: 145, protein: 3, fiber: 5 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-barley-berry-trail-mix',
    name: 'Barley and Berry Trail Mix',
    emoji: '🌾',
    category: 'snack',
    time: '15 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'no-cook'],
    ingredients: [
      { qty: '2 cups', item: 'toasted puffed barley' },
      { qty: '1/3 cup', item: 'unsweetened dried berries' },
      { qty: '1/3 cup', item: 'walnut pieces' },
      { qty: '2 tbsp', item: 'pumpkin seeds' },
    ],
    steps: [
      'Combine the puffed barley, dried berries, walnuts and pumpkin seeds in a bowl.',
      'Toss until evenly mixed.',
      'Portion into cups or bags for grab-and-go snacking.',
    ],
    superAgeNote: 'Barley is a whole grain especially high in beta-glucan fiber, so this mix with berries and seeds fits the study focus on fiber-rich carbs. (Contains barley, so not gluten-free.)',
    nutrition: { cal: 195, protein: 6, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-spiced-chickpeas-orange-zest',
    name: 'Spiced Roasted Chickpeas with Orange Zest',
    emoji: '🫛',
    category: 'snack',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 can', item: 'chickpeas, drained and rinsed' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1/2 tsp', item: 'ground coriander' },
      { qty: '1/2 tsp', item: 'ground cumin' },
      { qty: '1 tbsp', item: 'orange zest' },
      { qty: '1/4 tsp', item: 'salt' },
    ],
    steps: [
      'Pat the chickpeas dry and toss with the oil, coriander, cumin and salt.',
      'Roast at 400F (200C) for 30 to 35 minutes, shaking twice, until crisp.',
      'Toss with the fresh orange zest right after roasting.',
    ],
    superAgeNote: 'Chickpeas bring legume fiber and protein while the orange zest adds brightness, combining two study star foods in one crunchy snack.',
    nutrition: { cal: 185, protein: 8, fiber: 7 },
    airfryer: [
      'Add the seasoned chickpeas to the basket in a single layer.',
      'Air fry at 390F (200C) for 15 to 18 minutes, shaking every 5 minutes, then toss with orange zest.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-apple-almond-oat-bites',
    name: 'Apple and Almond Butter Oat Bites',
    emoji: '🍎',
    category: 'snack',
    time: '15 min',
    serves: 6,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1 cup', item: 'rolled oats' },
      { qty: '1', item: 'apple, grated and squeezed dry' },
      { qty: '1/3 cup', item: 'almond butter' },
      { qty: '2 tbsp', item: 'ground flaxseed' },
      { qty: '1 tsp', item: 'ground cinnamon' },
    ],
    steps: [
      'Mix the oats, grated apple, almond butter, flaxseed and cinnamon into a sticky dough.',
      'Roll into small balls with damp hands.',
      'Chill 20 minutes so they set before serving.',
    ],
    superAgeNote: 'Oats, apple and flaxseed stack whole-grain and fruit fiber in a no-bake bite, a portable version of the study fiber-rich carbs.',
    nutrition: { cal: 165, protein: 5, fiber: 5 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-broccoli-carrot-slaw-bites',
    name: 'Broccoli and Carrot Slaw Bites with Lemon',
    emoji: '🥦',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '2 cups', item: 'shredded broccoli slaw' },
      { qty: '1', item: 'carrot, grated' },
      { qty: '2 tbsp', item: 'lemon juice' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '2 tbsp', item: 'sunflower seeds' },
    ],
    steps: [
      'Toss the broccoli slaw and grated carrot in a bowl.',
      'Dress with the lemon juice and olive oil and toss to coat.',
      'Fold in the sunflower seeds and scoop into small cups.',
    ],
    superAgeNote: 'Raw broccoli and carrot keep all their vegetable fiber, and the lemon dressing makes this crunchy slaw a fresh take on the study star vegetables.',
    nutrition: { cal: 150, protein: 5, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-berry-quinoa-parfait-cup',
    name: 'Berry and Quinoa Parfait Cup',
    emoji: '🫐',
    category: 'snack',
    time: '10 min',
    serves: 2,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '1 cup', item: 'cooked quinoa, cooled' },
      { qty: '3/4 cup', item: 'plain Greek yogurt' },
      { qty: '1 cup', item: 'mixed berries' },
      { qty: '1 tbsp', item: 'chopped pistachios' },
    ],
    steps: [
      'Layer half the quinoa and yogurt in two cups.',
      'Add the berries, then repeat the layers.',
      'Top with the chopped pistachios and serve.',
    ],
    superAgeNote: 'Quinoa is a whole grain and berries are a top-fiber fruit, so this parfait pairs two study star foods with protein-rich yogurt.',
    nutrition: { cal: 230, protein: 13, fiber: 6 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-sn-popcorn-apple-walnut-mix',
    name: 'Popcorn, Apple and Walnut Snack Mix',
    emoji: '🍿',
    category: 'snack',
    time: '10 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'no-cook'],
    ingredients: [
      { qty: '4 cups', item: 'air-popped popcorn' },
      { qty: '1/2 cup', item: 'chopped dried apple' },
      { qty: '1/3 cup', item: 'walnut pieces' },
      { qty: '1/2 tsp', item: 'ground cinnamon' },
    ],
    steps: [
      'Add the cooled popcorn to a large bowl.',
      'Toss in the dried apple and walnut pieces.',
      'Dust with cinnamon, toss again and portion out.',
    ],
    superAgeNote: 'Whole-grain popcorn with apple and walnuts brings fiber and healthy fats to a sweet-and-savory mix, in line with the study on high-quality carbs.',
    nutrition: { cal: 200, protein: 4, fiber: 5 },
    added: '2026-07-27',
    isCustom: true,
  },
];

(function () {
  if (typeof KANDY_RECIPES !== 'undefined') KANDY_RECIPES.push(...SUPERAGE_SNACKS);
  SUPERAGE_SNACKS.forEach(function (r) {
    if (r.airfryer && typeof AIRFRYER !== 'undefined') AIRFRYER[r.id] = r.airfryer;
    if (r.nutrition && typeof RECIPE_NUTRITION !== 'undefined') RECIPE_NUTRITION[r.id] = r.nutrition;
  });
})();
