// SuperAge Dinner Recipes
// Healthy, high-fiber "longevity carb" dinners inspired by a SuperAge article on a
// 30-year study (JAMA Network Open) linking high-quality, fiber-rich carbohydrates
// to healthier aging. Hero foods: whole grains (quinoa, barley, millet, oats),
// legumes (lentils, chickpeas, black beans, white beans), fruit, and vegetables
// (kale, spinach, broccoli, carrots). Real, recognizable weeknight dinners.

const SUPERAGE_DINNER = [
  {
    id: 'sa-di-turkey-black-bean-chili',
    name: 'Turkey and Black Bean Chili',
    emoji: '🌶️',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 lb', item: 'lean ground turkey' },
      { qty: '1', item: 'onion, diced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1', item: 'red bell pepper, diced' },
      { qty: '2 tbsp', item: 'tomato paste' },
      { qty: '2 tbsp', item: 'chili powder' },
      { qty: '1 tbsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '2 cans (15 oz each)', item: 'black beans, drained and rinsed' },
      { qty: '1 can (28 oz)', item: 'crushed tomatoes' },
      { qty: '1 cup', item: 'chicken or vegetable broth' },
      { qty: '1 tbsp', item: 'olive oil' },
      { qty: '1', item: 'lime, juiced' },
    ],
    steps: [
      'Heat olive oil in a large pot over medium-high and brown the turkey, breaking it up, until no longer pink, about 6 minutes.',
      'Add onion, garlic, and bell pepper and cook until softened, 5 minutes.',
      'Stir in tomato paste, chili powder, cumin, and smoked paprika and toast for 1 minute until fragrant.',
      'Add black beans, crushed tomatoes, and broth. Bring to a simmer.',
      'Simmer uncovered for 25 minutes, stirring occasionally, until thickened. Finish with lime juice and season to taste.',
    ],
    superAgeNote: 'Black beans are the hero longevity carb here, delivering fiber-rich, high-quality carbohydrate with a carb-to-fiber ratio well under 10:1, the pattern the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 440, protein: 34, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lentil-bolognese-whole-grain-pasta',
    name: 'Lentil Bolognese over Whole-Grain Pasta',
    emoji: '🍝',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'dried brown lentils, rinsed' },
      { qty: '1', item: 'onion, finely diced' },
      { qty: '2', item: 'carrots, finely diced' },
      { qty: '2 stalks', item: 'celery, finely diced' },
      { qty: '4 cloves', item: 'garlic, minced' },
      { qty: '3 tbsp', item: 'tomato paste' },
      { qty: '1 can (28 oz)', item: 'crushed tomatoes' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'dried oregano' },
      { qty: '1 tsp', item: 'dried basil' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '12 oz', item: 'whole-grain spaghetti' },
    ],
    steps: [
      'Heat olive oil in a deep skillet and cook onion, carrot, and celery until soft and lightly caramelized, about 8 minutes.',
      'Add garlic and tomato paste and cook 2 minutes until the paste darkens.',
      'Stir in lentils, crushed tomatoes, broth, oregano, and basil. Simmer, partially covered, for 30 minutes until the lentils are tender and the sauce is thick.',
      'Meanwhile cook the whole-grain spaghetti in salted water until al dente, then drain.',
      'Toss the pasta with the sauce, loosening with a splash of pasta water, and season to taste.',
    ],
    superAgeNote: 'Lentils plus whole-grain pasta stack two hero longevity carbs, giving a fiber-dense meal of the high-quality carbohydrate the JAMA Network Open aging study linked to better midlife health.',
    nutrition: { cal: 520, protein: 24, fiber: 20 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-tikka-masala-basmati',
    name: 'Chickpea Tikka Masala with Basmati Rice',
    emoji: '🍛',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '1', item: 'onion, finely diced' },
      { qty: '4 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'fresh ginger, grated' },
      { qty: '2 tbsp', item: 'garam masala' },
      { qty: '1 tsp', item: 'ground turmeric' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '2 tbsp', item: 'tomato paste' },
      { qty: '1 can (15 oz)', item: 'crushed tomatoes' },
      { qty: '1/2 cup', item: 'plain yogurt' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1.5 cups', item: 'basmati rice' },
      { qty: '3 cups', item: 'fresh spinach' },
    ],
    steps: [
      'Cook the basmati rice according to package directions and keep warm.',
      'Heat olive oil and saute onion until golden, 6 minutes, then add garlic and ginger for 1 minute.',
      'Stir in garam masala, turmeric, paprika, and tomato paste and toast 1 minute until fragrant.',
      'Add crushed tomatoes and chickpeas, simmer 12 minutes, then stir in spinach until wilted.',
      'Off the heat, swirl in the yogurt so the sauce turns creamy. Season and serve over the basmati.',
    ],
    superAgeNote: 'Chickpeas carry the fiber load in this curry, a high-quality carbohydrate the JAMA Network Open study associated with healthier aging, with well over 3g of fiber per serving.',
    nutrition: { cal: 500, protein: 19, fiber: 15 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lemon-herb-salmon-barley-pilaf',
    name: 'Lemon-Herb Salmon with Barley Pilaf and Broccoli',
    emoji: '🐟',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'high-protein'],
    ingredients: [
      { qty: '4 fillets (5 oz each)', item: 'salmon' },
      { qty: '1 cup', item: 'pearl barley' },
      { qty: '3 cups', item: 'vegetable broth' },
      { qty: '1', item: 'shallot, minced' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '1 large head', item: 'broccoli, cut into florets' },
      { qty: '1', item: 'lemon, half zested and juiced, half sliced' },
      { qty: '2 tbsp', item: 'fresh dill, chopped' },
      { qty: '2 tbsp', item: 'fresh parsley, chopped' },
      { qty: '3 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Saute the shallot and garlic in 1 tbsp olive oil, add barley and toast 1 minute, then pour in broth and simmer covered 35 minutes until tender.',
      'Toss broccoli with 1 tbsp olive oil and roast at 425F (220C) for 18 minutes until charred at the edges.',
      'Pat the salmon dry, rub with 1 tbsp olive oil, lemon zest, salt, and pepper, and top each fillet with a lemon slice.',
      'Roast the salmon at 425F (220C) for 12 minutes until it flakes.',
      'Fold lemon juice, dill, and parsley into the barley, then plate with the broccoli and salmon.',
    ],
    superAgeNote: 'Pearl barley and broccoli are the hero longevity carbs, both fiber-rich, high-quality carbohydrates of the kind the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 560, protein: 38, fiber: 13 },
    airfryer: [
      'Air-fry the broccoli at 390F (199C) for 10 minutes, shaking halfway.',
      'Air-fry the salmon fillets at 400F (204C) for 8 to 10 minutes until they flake.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-sheet-pan-chicken-quinoa-carrots',
    name: 'Sheet-Pan Chicken with Quinoa and Roasted Carrots',
    emoji: '🍗',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '4', item: 'bone-in chicken thighs' },
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '2 cups', item: 'chicken broth' },
      { qty: '1 lb', item: 'carrots, cut into batons' },
      { qty: '1', item: 'red onion, cut into wedges' },
      { qty: '2 tsp', item: 'smoked paprika' },
      { qty: '1 tsp', item: 'garlic powder' },
      { qty: '1 tsp', item: 'dried thyme' },
      { qty: '3 tbsp', item: 'olive oil' },
      { qty: '1', item: 'lemon, cut into wedges' },
    ],
    steps: [
      'Toss carrots and onion with 2 tbsp olive oil, paprika, garlic powder, thyme, salt, and pepper on a sheet pan.',
      'Rub the chicken thighs with the remaining oil and seasoning and nestle them among the vegetables, skin up.',
      'Roast at 425F (220C) for 35 minutes until the chicken reaches 175F (79C) and the carrots are caramelized.',
      'Meanwhile simmer the quinoa in the broth, covered, for 15 minutes, then fluff with a fork.',
      'Serve the chicken and carrots over the quinoa with lemon wedges to squeeze over the top.',
    ],
    superAgeNote: 'Quinoa and carrots supply the fiber-rich, high-quality carbohydrate the JAMA Network Open study associated with healthier aging, keeping the carb-to-fiber ratio low.',
    nutrition: { cal: 540, protein: 32, fiber: 12 },
    airfryer: [
      'Air-fry the carrots and onion at 390F (199C) for 14 minutes, shaking once.',
      'Air-fry the chicken thighs at 380F (193C) for 18 to 20 minutes until they reach 175F (79C).',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-black-bean-sweet-potato-enchilada-bake',
    name: 'Black Bean and Sweet-Potato Enchilada Bake',
    emoji: '🫔',
    category: 'dinner',
    time: '55 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '2', item: 'sweet potatoes, peeled and diced small' },
      { qty: '2 cans (15 oz each)', item: 'black beans, drained and rinsed' },
      { qty: '1', item: 'onion, diced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '2 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'chili powder' },
      { qty: '10', item: 'corn tortillas, halved' },
      { qty: '1 can (19 oz)', item: 'red enchilada sauce' },
      { qty: '1.5 cups', item: 'shredded cheese' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '3', item: 'green onions, sliced' },
    ],
    steps: [
      'Saute the sweet potato in olive oil with a splash of water, covered, until nearly tender, 10 minutes.',
      'Add onion, garlic, cumin, and chili powder and cook 4 minutes, then fold in the black beans.',
      'Spread a thin layer of enchilada sauce in a baking dish, then layer tortillas, filling, and sauce twice, finishing with sauce and the cheese.',
      'Bake at 400F (205C) for 25 minutes until bubbling and the cheese is melted.',
      'Scatter green onions over the top and let it rest 5 minutes before cutting.',
    ],
    superAgeNote: 'Black beans and sweet potato provide the hero longevity carbs, fiber-rich, high-quality carbohydrates the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 560, protein: 22, fiber: 18 },
    airfryer: [
      'Assemble the bake in an air-fryer-safe dish.',
      'Air-fry at 350F (177C) for 12 to 15 minutes until the cheese top is crisped and bubbling.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-lentil-vegetable-shepherds-pie',
    name: 'Lentil and Vegetable Shepherd\'s Pie',
    emoji: '🥧',
    category: 'dinner',
    time: '55 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'dried green lentils, rinsed' },
      { qty: '1', item: 'onion, diced' },
      { qty: '2', item: 'carrots, diced' },
      { qty: '1 cup', item: 'frozen peas' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '2 tbsp', item: 'tomato paste' },
      { qty: '1 tbsp', item: 'soy sauce' },
      { qty: '3 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'dried rosemary' },
      { qty: '3', item: 'russet potatoes, peeled and cubed' },
      { qty: '3 tbsp', item: 'plant milk' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Saute onion, carrot, and garlic in olive oil until softened, 6 minutes.',
      'Stir in tomato paste and rosemary, then add lentils, soy sauce, and broth. Simmer 30 minutes until the lentils are tender and saucy, folding in the peas at the end.',
      'Boil the potatoes until fork-tender, drain, and mash with plant milk, salt, and pepper until fluffy.',
      'Spread the lentil filling in a baking dish and blanket with the mash, roughing the top with a fork.',
      'Bake at 400F (205C) for 22 minutes until golden. Rest 5 minutes before serving.',
    ],
    superAgeNote: 'Green lentils are the hero longevity carb, a high-quality, fiber-rich carbohydrate with a carb-to-fiber ratio well under 10:1, the pattern the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 480, protein: 24, fiber: 19 },
    airfryer: [
      'Assemble the pie in an air-fryer-safe dish.',
      'Air-fry at 380F (193C) for 12 to 15 minutes until the mash top is golden and crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chicken-vegetable-barley-risotto',
    name: 'Chicken and Vegetable Barley Risotto',
    emoji: '🍲',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'high-protein'],
    ingredients: [
      { qty: '1 cup', item: 'pearl barley' },
      { qty: '2', item: 'boneless chicken breasts, diced' },
      { qty: '1', item: 'onion, finely diced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '8 oz', item: 'cremini mushrooms, sliced' },
      { qty: '2', item: 'carrots, diced' },
      { qty: '5 cups', item: 'warm chicken broth' },
      { qty: '1/2 cup', item: 'grated Parmesan' },
      { qty: '2 cups', item: 'baby spinach' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1 tsp', item: 'fresh thyme' },
    ],
    steps: [
      'Brown the diced chicken in 1 tbsp olive oil, then set aside.',
      'In the same pan, soften onion, garlic, carrot, and mushrooms in the remaining oil, 6 minutes.',
      'Add the barley and thyme and toast 1 minute, then add warm broth one ladle at a time, stirring, until each addition is absorbed, about 35 minutes.',
      'When the barley is creamy and tender, return the chicken and fold in the spinach until wilted.',
      'Stir in the Parmesan off the heat, season, and serve at once.',
    ],
    superAgeNote: 'Barley stands in for rice as the hero longevity carb, a fiber-rich, high-quality carbohydrate of the kind the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 530, protein: 34, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-turkey-quinoa-stuffed-peppers',
    name: 'Turkey-Quinoa Stuffed Peppers',
    emoji: '🫑',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '4', item: 'bell peppers, tops removed and seeded' },
      { qty: '1 lb', item: 'lean ground turkey' },
      { qty: '3/4 cup', item: 'quinoa, rinsed' },
      { qty: '1.5 cups', item: 'chicken broth' },
      { qty: '1', item: 'onion, diced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 can (15 oz)', item: 'fire-roasted diced tomatoes' },
      { qty: '1 cup', item: 'shredded cheese' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Simmer the quinoa in the broth, covered, for 15 minutes, then fluff.',
      'Brown the turkey in olive oil with onion and garlic, then stir in cumin, paprika, and the tomatoes and cook 5 minutes.',
      'Fold the cooked quinoa into the turkey mixture and season well.',
      'Stand the peppers in a baking dish, fill with the mixture, top with cheese, and add a splash of water to the dish.',
      'Cover with foil and bake at 375F (190C) for 30 minutes, then uncover 10 minutes more until the peppers are tender.',
    ],
    superAgeNote: 'Quinoa is the hero longevity carb tucked inside each pepper, a fiber-rich, high-quality carbohydrate the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 470, protein: 33, fiber: 12 },
    airfryer: [
      'Air-fry the filled peppers in an air-fryer-safe dish at 360F (182C) for 15 to 18 minutes until the peppers soften and the cheese browns.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chickpea-spinach-coconut-curry',
    name: 'Chickpea and Spinach Coconut Curry over Rice',
    emoji: '🥥',
    category: 'dinner',
    time: '35 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '1', item: 'onion, diced' },
      { qty: '4 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'fresh ginger, grated' },
      { qty: '2 tbsp', item: 'curry powder' },
      { qty: '1 tsp', item: 'ground turmeric' },
      { qty: '1 can (14 oz)', item: 'light coconut milk' },
      { qty: '1 can (15 oz)', item: 'diced tomatoes' },
      { qty: '5 cups', item: 'fresh spinach' },
      { qty: '1.5 cups', item: 'brown rice' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1', item: 'lime, juiced' },
    ],
    steps: [
      'Cook the brown rice according to package directions and keep warm.',
      'Saute onion in olive oil until soft, then add garlic, ginger, curry powder, and turmeric and toast 1 minute.',
      'Add tomatoes, coconut milk, and chickpeas and simmer 15 minutes until slightly thickened.',
      'Stir in the spinach until wilted and finish with lime juice; season to taste.',
      'Serve the curry ladled over the brown rice.',
    ],
    superAgeNote: 'Chickpeas and brown rice pair two hero longevity carbs, the fiber-rich, high-quality carbohydrates the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 520, protein: 18, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-mediterranean-baked-cod-chickpeas-kale',
    name: 'Mediterranean Baked Cod with Chickpeas and Kale',
    emoji: '🐟',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '4 fillets (6 oz each)', item: 'cod' },
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '1 bunch', item: 'kale, stemmed and torn' },
      { qty: '1', item: 'onion, sliced' },
      { qty: '4 cloves', item: 'garlic, sliced' },
      { qty: '1 pint', item: 'cherry tomatoes' },
      { qty: '2 tsp', item: 'dried oregano' },
      { qty: '1', item: 'lemon, half juiced, half sliced' },
      { qty: '3 tbsp', item: 'olive oil' },
      { qty: '1/4 tsp', item: 'red pepper flakes' },
    ],
    steps: [
      'Saute onion and garlic in 2 tbsp olive oil until soft, add chickpeas, tomatoes, oregano, and pepper flakes and cook until the tomatoes burst, 8 minutes.',
      'Fold in the kale and cook until wilted, then spread the mixture in a baking dish.',
      'Nestle the cod fillets on top, drizzle with the remaining oil and lemon juice, and lay lemon slices over the fish.',
      'Bake at 400F (205C) for 15 minutes until the cod is opaque and flakes easily.',
      'Season and serve straight from the dish.',
    ],
    superAgeNote: 'Chickpeas are the hero longevity carb under the cod, a high-quality, fiber-rich carbohydrate the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 480, protein: 40, fiber: 14 },
    airfryer: [
      'Air-fry the cod fillets at 380F (193C) for 8 to 10 minutes until opaque, and serve over the stovetop chickpeas and kale.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-turkey-lentil-meatballs-marinara',
    name: 'Turkey-Lentil Meatballs with Marinara',
    emoji: '🍝',
    category: 'dinner',
    time: '50 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'high-protein'],
    ingredients: [
      { qty: '1 lb', item: 'lean ground turkey' },
      { qty: '1 cup', item: 'cooked brown lentils' },
      { qty: '1', item: 'egg' },
      { qty: '1/2 cup', item: 'whole-wheat breadcrumbs' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1 tsp', item: 'dried oregano' },
      { qty: '1/4 cup', item: 'chopped parsley' },
      { qty: '1 jar (24 oz)', item: 'marinara sauce' },
      { qty: '12 oz', item: 'whole-wheat spaghetti' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Mash the cooked lentils slightly, then combine with turkey, egg, breadcrumbs, garlic, oregano, parsley, salt, and pepper and roll into 16 meatballs.',
      'Brown the meatballs in olive oil on all sides, about 6 minutes.',
      'Pour in the marinara, cover, and simmer 20 minutes until the meatballs are cooked through.',
      'Meanwhile cook the whole-wheat spaghetti until al dente and drain.',
      'Serve the meatballs and sauce over the spaghetti.',
    ],
    superAgeNote: 'Brown lentils folded into the meatballs and whole-wheat pasta both count as hero longevity carbs, fiber-rich, high-quality carbohydrates the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 580, protein: 38, fiber: 15 },
    airfryer: [
      'Air-fry the raw meatballs at 380F (193C) for 12 minutes until browned and cooked through, then simmer briefly in the marinara.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-beef-barley-stew',
    name: 'Beef and Barley Stew',
    emoji: '🍲',
    category: 'dinner',
    time: '75 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'high-protein'],
    ingredients: [
      { qty: '1 lb', item: 'lean beef chuck, cubed' },
      { qty: '3/4 cup', item: 'pearl barley' },
      { qty: '1', item: 'onion, diced' },
      { qty: '3', item: 'carrots, sliced' },
      { qty: '2 stalks', item: 'celery, sliced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '8 oz', item: 'mushrooms, quartered' },
      { qty: '2 tbsp', item: 'tomato paste' },
      { qty: '6 cups', item: 'beef broth' },
      { qty: '1 tsp', item: 'dried thyme' },
      { qty: '2', item: 'bay leaves' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Season the beef and brown it in olive oil in batches, then set aside.',
      'Soften onion, carrot, celery, garlic, and mushrooms in the same pot, 6 minutes, then stir in the tomato paste.',
      'Return the beef, add broth, barley, thyme, and bay leaves, and bring to a simmer.',
      'Cover and simmer gently for 50 minutes until the beef is tender and the barley is plump.',
      'Discard the bay leaves, season, and serve.',
    ],
    superAgeNote: 'Barley is the hero longevity carb that thickens this stew, a fiber-rich, high-quality carbohydrate the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 520, protein: 34, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-black-bean-quinoa-burgers',
    name: 'Black Bean and Quinoa Burgers',
    emoji: '🍔',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 can (15 oz)', item: 'black beans, drained and rinsed' },
      { qty: '1 cup', item: 'cooked quinoa' },
      { qty: '1/2 cup', item: 'rolled oats (gluten-free)' },
      { qty: '1', item: 'small onion, grated' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'ground flaxseed plus 3 tbsp water' },
      { qty: '1 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '4', item: 'gluten-free buns or lettuce wraps' },
    ],
    steps: [
      'Stir the flax with water and let it gel for 5 minutes.',
      'Mash the black beans coarsely, then mix in quinoa, oats, onion, garlic, cumin, paprika, the flax egg, salt, and pepper.',
      'Form four firm patties and chill 10 minutes so they hold together.',
      'Pan-fry in olive oil over medium heat for 4 minutes a side until a crust forms.',
      'Serve on buns or lettuce wraps with your favorite toppings.',
    ],
    superAgeNote: 'Black beans and quinoa are the hero longevity carbs in every patty, fiber-rich, high-quality carbohydrates the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 430, protein: 17, fiber: 15 },
    airfryer: [
      'Air-fry the chilled patties at 375F (190C) for 12 minutes, flipping once, until crisp and heated through.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-chicken-kale-barley-skillet',
    name: 'Chicken, Kale, and Barley Skillet',
    emoji: '🍳',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'high-protein'],
    ingredients: [
      { qty: '2', item: 'boneless chicken breasts, diced' },
      { qty: '1 cup', item: 'pearl barley' },
      { qty: '3 cups', item: 'chicken broth' },
      { qty: '1 bunch', item: 'kale, stemmed and chopped' },
      { qty: '1', item: 'onion, diced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '1', item: 'red bell pepper, diced' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 tsp', item: 'dried oregano' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1', item: 'lemon, juiced' },
    ],
    steps: [
      'Brown the diced chicken in 1 tbsp olive oil, season, and set aside.',
      'Soften onion, garlic, and bell pepper in the remaining oil, then add barley, paprika, and oregano and toast 1 minute.',
      'Pour in the broth, cover, and simmer 30 minutes until the barley is tender.',
      'Fold in the kale and the browned chicken and cook until the kale wilts and the chicken is heated through.',
      'Finish with lemon juice, season, and serve from the skillet.',
    ],
    superAgeNote: 'Barley and kale are the hero longevity carbs in this one-pan supper, fiber-rich, high-quality carbohydrates the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 490, protein: 33, fiber: 13 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-salmon-cakes-greens',
    name: 'Salmon Cakes with Lemony Greens',
    emoji: '🐟',
    category: 'dinner',
    time: '35 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '2 cans (6 oz each)', item: 'salmon, drained' },
      { qty: '1 can (15 oz)', item: 'white beans, drained, rinsed, and mashed' },
      { qty: '1/2 cup', item: 'rolled oats (gluten-free)' },
      { qty: '1', item: 'egg' },
      { qty: '3', item: 'green onions, sliced' },
      { qty: '2 tbsp', item: 'chopped dill' },
      { qty: '1', item: 'lemon, zested and juiced' },
      { qty: '6 cups', item: 'baby kale or spinach' },
      { qty: '2 cloves', item: 'garlic, minced' },
      { qty: '3 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Combine salmon, mashed white beans, oats, egg, green onion, dill, lemon zest, salt, and pepper and form eight cakes.',
      'Pan-fry the cakes in 2 tbsp olive oil for 3 to 4 minutes a side until golden and set.',
      'In the same pan, warm the remaining oil and garlic, then wilt the greens for 2 minutes.',
      'Finish the greens with lemon juice and season.',
      'Plate the salmon cakes over the lemony greens.',
    ],
    superAgeNote: 'Mashed white beans bind the cakes and act as the hero longevity carb, a fiber-rich, high-quality carbohydrate the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 460, protein: 32, fiber: 12 },
    airfryer: [
      'Air-fry the salmon cakes at 380F (193C) for 10 to 12 minutes, flipping once, until golden and crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-broccoli-chickpea-coconut-curry',
    name: 'Broccoli and Chickpea Coconut Curry',
    emoji: '🥦',
    category: 'dinner',
    time: '35 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '1 large head', item: 'broccoli, cut into florets' },
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '1', item: 'onion, diced' },
      { qty: '4 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'fresh ginger, grated' },
      { qty: '3 tbsp', item: 'red curry paste' },
      { qty: '1 can (14 oz)', item: 'light coconut milk' },
      { qty: '1 cup', item: 'vegetable broth' },
      { qty: '1.5 cups', item: 'brown rice' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1', item: 'lime, juiced' },
    ],
    steps: [
      'Cook the brown rice according to package directions and keep warm.',
      'Saute onion in olive oil, then add garlic, ginger, and curry paste and cook 1 minute until fragrant.',
      'Pour in coconut milk and broth, add the chickpeas, and simmer 8 minutes.',
      'Add the broccoli and simmer 6 minutes more until crisp-tender.',
      'Finish with lime juice, season, and serve over the brown rice.',
    ],
    superAgeNote: 'Broccoli, chickpeas, and brown rice stack three hero longevity carbs, the fiber-rich, high-quality carbohydrates the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 510, protein: 18, fiber: 17 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-moroccan-chickpea-carrot-tagine-millet',
    name: 'Moroccan Chickpea and Carrot Tagine over Millet',
    emoji: '🍲',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '4', item: 'carrots, cut into chunks' },
      { qty: '1', item: 'onion, diced' },
      { qty: '4 cloves', item: 'garlic, minced' },
      { qty: '2 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'ground cinnamon' },
      { qty: '1 tsp', item: 'ground ginger' },
      { qty: '1 can (15 oz)', item: 'diced tomatoes' },
      { qty: '2 cups', item: 'vegetable broth' },
      { qty: '1/3 cup', item: 'dried apricots, chopped' },
      { qty: '1 cup', item: 'millet' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Toast the millet in a dry pot 2 minutes, add 2 cups water, and simmer covered 18 minutes, then fluff.',
      'Saute onion in olive oil, add garlic, cumin, cinnamon, and ginger and toast 1 minute.',
      'Add carrots, tomatoes, broth, chickpeas, and apricots and bring to a simmer.',
      'Cover and simmer 25 minutes until the carrots are tender and the sauce is jammy.',
      'Season and serve the tagine over the fluffy millet.',
    ],
    superAgeNote: 'Millet, chickpeas, and carrots are the hero longevity carbs here, fiber-rich, high-quality carbohydrates the JAMA Network Open study associated with healthier aging, brightened with a little dried fruit.',
    nutrition: { cal: 520, protein: 17, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-tuscan-white-bean-kale-soup',
    name: 'Tuscan White Bean and Kale Soup',
    emoji: '🍜',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free'],
    ingredients: [
      { qty: '3 cans (15 oz each)', item: 'cannellini beans, drained and rinsed' },
      { qty: '1 bunch', item: 'kale, stemmed and torn' },
      { qty: '1', item: 'onion, diced' },
      { qty: '2', item: 'carrots, diced' },
      { qty: '2 stalks', item: 'celery, diced' },
      { qty: '4 cloves', item: 'garlic, minced' },
      { qty: '1 can (15 oz)', item: 'diced tomatoes' },
      { qty: '6 cups', item: 'vegetable broth' },
      { qty: '1 tsp', item: 'dried rosemary' },
      { qty: '1/4 tsp', item: 'red pepper flakes' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Soften onion, carrot, celery, and garlic in olive oil, 7 minutes.',
      'Add rosemary and pepper flakes, then the tomatoes, broth, and beans.',
      'Mash about a cup of the beans against the side of the pot to thicken the broth.',
      'Simmer 15 minutes, then stir in the kale and cook until tender, 5 minutes more.',
      'Season generously and finish each bowl with a drizzle of olive oil.',
    ],
    superAgeNote: 'Cannellini beans and kale are the hero longevity carbs in this rustic soup, fiber-rich, high-quality carbohydrates the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 400, protein: 18, fiber: 17 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-baked-falafel-quinoa-tabbouleh-bowls',
    name: 'Baked Falafel Bowls with Quinoa Tabbouleh',
    emoji: '🥙',
    category: 'dinner',
    time: '45 min',
    serves: 4,
    difficulty: 'medium',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '2 cans (15 oz each)', item: 'chickpeas, drained and rinsed' },
      { qty: '1/2', item: 'onion, roughly chopped' },
      { qty: '4 cloves', item: 'garlic' },
      { qty: '1 cup', item: 'parsley, packed' },
      { qty: '2 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'ground coriander' },
      { qty: '3 tbsp', item: 'chickpea flour' },
      { qty: '1 cup', item: 'quinoa, rinsed' },
      { qty: '2', item: 'tomatoes, diced' },
      { qty: '1', item: 'cucumber, diced' },
      { qty: '1', item: 'lemon, juiced' },
      { qty: '3 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Simmer the quinoa in 2 cups water, covered, 15 minutes, then cool and toss with tomato, cucumber, half the lemon juice, and 1 tbsp olive oil for the tabbouleh.',
      'Pulse chickpeas, onion, garlic, half the parsley, cumin, coriander, and chickpea flour into a coarse dough.',
      'Roll into 16 balls, flatten slightly, and brush with the remaining oil.',
      'Bake at 400F (205C) for 25 minutes, flipping once, until golden and crisp.',
      'Build bowls with the quinoa tabbouleh, falafel, remaining parsley, and a squeeze of lemon.',
    ],
    superAgeNote: 'Chickpeas and quinoa are the hero longevity carbs in these bowls, fiber-rich, high-quality carbohydrates the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 500, protein: 20, fiber: 16 },
    airfryer: [
      'Air-fry the falafel at 380F (193C) for 14 to 16 minutes, flipping once, until deeply golden and crisp.',
    ],
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-shrimp-broccoli-stir-fry-brown-rice',
    name: 'Shrimp and Broccoli Stir-Fry over Brown Rice',
    emoji: '🍤',
    category: 'dinner',
    time: '30 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1 lb', item: 'shrimp, peeled and deveined' },
      { qty: '1 large head', item: 'broccoli, cut into florets' },
      { qty: '2', item: 'carrots, thinly sliced' },
      { qty: '4 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'fresh ginger, grated' },
      { qty: '3 tbsp', item: 'tamari' },
      { qty: '1 tbsp', item: 'rice vinegar' },
      { qty: '1 tsp', item: 'honey' },
      { qty: '1 tbsp', item: 'cornstarch' },
      { qty: '1.5 cups', item: 'brown rice' },
      { qty: '2 tbsp', item: 'sesame oil' },
    ],
    steps: [
      'Cook the brown rice according to package directions and keep warm.',
      'Whisk tamari, rice vinegar, honey, cornstarch, and 1/3 cup water into a sauce.',
      'Stir-fry broccoli and carrots in 1 tbsp sesame oil over high heat for 4 minutes, adding a splash of water to steam, then remove.',
      'Add the remaining oil, garlic, and ginger, then the shrimp, and cook until pink, 3 minutes.',
      'Return the vegetables, pour in the sauce, and toss until glossy. Serve over the brown rice.',
    ],
    superAgeNote: 'Broccoli and brown rice are the hero longevity carbs in this stir-fry, fiber-rich, high-quality carbohydrates the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 470, protein: 30, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-huevos-rancheros-black-beans',
    name: 'Huevos Rancheros with Smoky Black Beans',
    emoji: '🍳',
    category: 'dinner',
    time: '30 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '2 cans (15 oz each)', item: 'black beans, drained and rinsed' },
      { qty: '8', item: 'eggs' },
      { qty: '8', item: 'corn tortillas' },
      { qty: '1', item: 'onion, diced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '2 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 cup', item: 'salsa' },
      { qty: '1', item: 'avocado, sliced' },
      { qty: '2 tbsp', item: 'olive oil' },
      { qty: '1/4 cup', item: 'chopped cilantro' },
    ],
    steps: [
      'Saute onion and garlic in 1 tbsp olive oil, add cumin and paprika, then the black beans and a splash of water; mash lightly and keep warm.',
      'Warm the corn tortillas in a dry skillet until pliable and lightly toasted.',
      'Fry the eggs in the remaining oil to your liking, keeping the yolks soft.',
      'Layer each plate with two tortillas, the smoky beans, and two eggs.',
      'Top with salsa, avocado, and cilantro and serve.',
    ],
    superAgeNote: 'Black beans are the hero longevity carb on the plate, a fiber-rich, high-quality carbohydrate the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 500, protein: 25, fiber: 16 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-spinach-lentil-dal-brown-rice',
    name: 'Spinach and Red Lentil Dal over Brown Rice',
    emoji: '🍛',
    category: 'dinner',
    time: '40 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: [
      { qty: '1.5 cups', item: 'red lentils, rinsed' },
      { qty: '1', item: 'onion, diced' },
      { qty: '4 cloves', item: 'garlic, minced' },
      { qty: '1 tbsp', item: 'fresh ginger, grated' },
      { qty: '2 tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'ground turmeric' },
      { qty: '1 tsp', item: 'garam masala' },
      { qty: '1 can (15 oz)', item: 'diced tomatoes' },
      { qty: '4 cups', item: 'vegetable broth' },
      { qty: '5 cups', item: 'fresh spinach' },
      { qty: '1.5 cups', item: 'brown rice' },
      { qty: '2 tbsp', item: 'olive oil' },
    ],
    steps: [
      'Cook the brown rice according to package directions and keep warm.',
      'Saute onion in olive oil, then add garlic, ginger, cumin, turmeric, and garam masala and toast 1 minute.',
      'Add the lentils, tomatoes, and broth and simmer 20 minutes until the lentils break down into a creamy dal.',
      'Stir in the spinach until wilted and season well.',
      'Serve the dal over the brown rice.',
    ],
    superAgeNote: 'Red lentils and brown rice are the hero longevity carbs in this dal, fiber-rich, high-quality carbohydrates the JAMA Network Open study linked to healthier aging.',
    nutrition: { cal: 510, protein: 24, fiber: 18 },
    added: '2026-07-27',
    isCustom: true,
  },
  {
    id: 'sa-di-kimchi-brown-rice-edamame-egg',
    name: 'Kimchi Fried Brown Rice with Edamame and Egg',
    emoji: '🍚',
    category: 'dinner',
    time: '30 min',
    serves: 4,
    difficulty: 'easy',
    tags: ['super-age', 'high-fiber', 'vegetarian', 'gluten-free'],
    ingredients: [
      { qty: '4 cups', item: 'cooked and chilled brown rice' },
      { qty: '1.5 cups', item: 'shelled edamame' },
      { qty: '1 cup', item: 'kimchi, chopped' },
      { qty: '4', item: 'eggs' },
      { qty: '1', item: 'carrot, grated' },
      { qty: '4', item: 'green onions, sliced' },
      { qty: '3 cloves', item: 'garlic, minced' },
      { qty: '2 tbsp', item: 'tamari' },
      { qty: '1 tbsp', item: 'gochujang' },
      { qty: '2 tbsp', item: 'sesame oil' },
      { qty: '1 tbsp', item: 'toasted sesame seeds' },
    ],
    steps: [
      'Heat 1 tbsp sesame oil in a wide skillet and cook the garlic, carrot, and white parts of the green onion for 2 minutes.',
      'Add the kimchi and gochujang and fry 2 minutes until fragrant and jammy.',
      'Push the vegetables aside, add the remaining oil, and stir in the chilled brown rice, pressing it flat to crisp for a few minutes.',
      'Fold in the edamame and tamari and toss until everything is hot and coated.',
      'Fry the eggs separately with runny yolks, then top each bowl of fried rice with an egg, green onion tops, and sesame seeds.',
    ],
    superAgeNote: 'Brown rice and edamame are the hero longevity carbs in this fried rice, fiber-rich, high-quality carbohydrates the JAMA Network Open study associated with healthier aging.',
    nutrition: { cal: 470, protein: 19, fiber: 12 },
    added: '2026-07-27',
    isCustom: true,
  },
];

(function () {
  if (typeof KANDY_RECIPES !== 'undefined') KANDY_RECIPES.push(...SUPERAGE_DINNER);
  SUPERAGE_DINNER.forEach(function (r) {
    if (r.airfryer && typeof AIRFRYER !== 'undefined') AIRFRYER[r.id] = r.airfryer;
    if (r.nutrition && typeof RECIPE_NUTRITION !== 'undefined') RECIPE_NUTRITION[r.id] = r.nutrition;
  });
})();
